### ISSUE TITLE
RStudio unable to detect new release

### ISSUE THREAD

**Issue by apsalverda** [rstudio/rstudio#10745]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2021.09.0 Build 351
    OS Version      : macOS Monterey 12.2.1
    R Version       : 4.1.0

### Steps to reproduce the problem
Select Help->Check for updates in the menu bar

### Describe the problem in detail
RStudio opens a window: "No update available. You're using the newest version of RStudio."

### Describe the behavior you expected
I expected RStudio to detect the lastest release (2022.02.0)

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [ ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by lsigut** [comment]
Hi, I have the same issue and I vaguely remember that I got some pop-up window before telling me about available update. Since I did not want to be actively asked to update, there was some option like "never ask again" that I clicked on. However, it also made my own attempts to update not successful as above ("No update available. You're using the newest version of RStudio."). Do you know which file should be perhaps deleted so the updates start working again?

**Comment by apsalverda** [comment]
@lsigut I'm not sure that I'm experiencing the same issue; I don't remember ever having indicated that I did not want to be asked to install updates.

**Comment by jgutman** [comment]
Loosely related to #10660 -- as part of sorting out this issue, it would be nice if we could also expose in the API the method we use here to check for RStudio updates. This came up recently in a devtools issue

**Comment by melissa-barca** [comment]
Unfortunately 2021.09.0 was released passing the unescaped plus sign in the version url in the check for updates request, and therefore, 2021.09.0 will never be able to properly check for updates. This was tracked in #9911 and the fix was backported to 2021.09.1

I just checked 2021.09.1 and 2021.09.2 and get the "Upgrade Available" response in both cases:

![image](https://user-images.githubusercontent.com/5323711/159307992-1c1750e2-315b-41f8-9dd7-5da260083fee.png)

![image](https://user-images.githubusercontent.com/5323711/159308470-7eb5505e-145d-411d-a0c6-e331efaed16e.png)

Ron - you may have only seen this once and missed it with 2021.09.1 because if you click "Ignore Update" you won't see "Update Available" again until there is an upgrade past 2022.02.0. You can get around this by clearing `~/.local/share/rstudio/client-state/updates.persistent` 
^ @lsigut I believe that should answer your question as well. 

We should be able to close this, but moving to test for QA to take a look.

**Comment by lsigut** [comment]
Thank you for pointing me there. FYI the updates.persistent had this content:
```
{
    "ignoredUpdates": {
        "updates": [
            "1.2.5042"
        ]
    }
}
```

**Comment by apsalverda** [comment]
@melissa-barca 
`~/.local/share/rstudio/client-state/updates.persistent` does not exist on my machine (but `~/.local/share/rstudio/client-state/updates.persistent` does).

**Comment by melissa-barca** [comment]
@apsalverda this file will only exist if you've selected "Ignore Update" which I don't believe was your issue. We're not able to update 2021.09.0 to get Check for Updates working but the issue was resolved in 2021.09.1.

**Comment by ronblum** [comment]
@melissa-barca Do we have control over how the update dialog works, or is this completely controlled by MacOS? (I haven't tried on other platforms yet) Technically, I didn't click on "Ignore Update"—I typed the <kbd>Esc</kbd> key to get the menu out of the way, as in, "I don't want to decide right now." But the dialog took it to be the equivalent of "Ignore Update." I think if anything it should've treated it as "Remind Later".

**Comment by ronblum** [comment]
@MariaSemple Will do!

**Comment by MariaSemple** [comment]
Verified fixed on 2021.09.2+382:
![image](https://user-images.githubusercontent.com/37987486/162488147-184e5630-9312-465d-a01b-4f47c97510e0.png)

**Comment by math-mcshane** [comment]
Hi @MariaSemple and @melissa-barca , I just wanted to note that I had the same issue with 2022.07.1 Build 554. It appears that the issue persisted after April 8th and should be re-opened. 

I used the menu (Help -> Check for Updates) to check for RStudio updates (probably for the third or fourth time in the past month), and it reported that I was using the newest version. I checked the website on a whim (I was looking for a new feature that must be in a future release, which was mentioned in #5424). 

![image](https://user-images.githubusercontent.com/48807452/199827089-24a993f1-f8f4-42cc-855d-d4b896b26ab0.png)

## System Info

```
RStudio Edition : Desktop
RStudio Version : 2022.07.1 Build 554
OS Version      : Windows 11 Home, Version 22H2, OS build 22621.674
R Version       : 4.2.1
```

**Comment by mikebessuille** [comment]
We need to fix this urgently so that SW 2022.07.1 will prompt to upgrade to 2022.07.2, and so that, when 2022.12.0. is released, that 2022.07.x will prompt to upgrade to 2022.12

**Comment by timtmok** [comment]
New active and passive files have been deployed.

**Comment by ronblum** [comment]
Verified on MacOS 13 in
- RStudio Desktop Pro 1.4.1743
- RStudio Desktop 2022.07.1-554 Electron
- RStudio Desktop 2022.07.1-554 Qt
