### ISSUE TITLE
Electron 2022.06.0-daily+343 on OpenSUSE Tumbleweed starts with InitializeSandbox() GPU warning

### ISSUE THREAD

**Issue by gsgxnet** [rstudio/rstudio#11114]
OpenSUSE Tumbleweed (rolling release, refreshed at April 30th) works generally as intended using `2022.06.0-daily+343` OpenSUSE 15 electron build <https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/opensuse15/> without having to set in your environment `export RSTUDIO_CHROMIUM_ARGUMENTS="--no-sandbox"`.

One issue remains (or is new?) - when starting from bash by `/usr/bin/rstudio &` I can see these warnings: 
```
[20765:0501/105924.463898:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is desktop, ANGLE is 
[20765:0501/105924.482149:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```
This might be caused by the special circumstance of my setup, a dual GPU Laptop, one Intel embedded, one NVidia.

_Originally posted by @gsgxnet in https://github.com/rstudio/rstudio/issues/9854#issuecomment-1114179177_

**Comment by gsgxnet** [comment]
Had verified that with build 351, I still get the same 
`[11220:0504/002324.605248:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.` warning. 
As stated before, the machine is an Dual-GPU (Optimus kind) DELL laptop - Precision 5520 type.  
The nvidia GPU is only used for R-`torch` or `pytorch` etc GPU acceleration.
```
nvidia-smi
Wed May  4 00:32:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.01   Driver Version: 470.103.01   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M1200        Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   48C    P0    N/A /  N/A |      0MiB /  4046MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```
otherwise not in use.   

`lshw -C display`  
```
  *-display                 
       description: 3D controller
       product: GM107GLM [Quadro M1200 Mobile]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a2
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:16 memory:ec000000-ecffffff memory:c0000000-cfffffff memory:d0000000-d1ffffff ioport:e000(size=128) memory:ed000000-ed07ffff
  *-display
       description: VGA compatible controller
       product: HD Graphics P630
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       logical name: /dev/fb0
       version: 04
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm vga_controller bus_master cap_list rom fb
       configuration: depth=32 driver=i915 latency=0 resolution=3840,2160
       resources: irq:144 memory:eb000000-ebffffff memory:80000000-8fffffff ioport:f000(size=64) memory:c0000-dffff
```

**Comment by ronblum** [comment]
@gsgxnet Thank you for opening this issue!

**Comment by prdm0** [comment]
On Arch Linux and derived distributions the problem continues. A good source of comments on how to resolve it is found [**here**](https://aur.archlinux.org/packages/rstudio-desktop-bin). So far, they're using workarounds, like running `rstudio-bin --no-sandbox` or making changes to the rstudio.desktop file.

**Comment by mikebessuille** [comment]
@gsgxnet are you still seeing that warning with the latest build?  Any other issues you're seeing?

**Comment by kevinushey** [comment]
@prdm0: I think the issues you're seeing should be resolved in the upcoming Electron builds of RStudio; `--no-sandox` should no longer be required once that's been released.

**Comment by ronblum** [comment]
Using RStudio Desktop 2022.12.0-daily+280 on openSUSE 15.4, I get the following error, so I'm reopening this.

```
vmware@localhost:~> [37935:1021/125157.321775:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
MESA-LOADER: failed to retrieve device information
[37935:1021/125157.465226:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
[37935:1021/125157.465597:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
```

The "failed to export buffer" error messages appears 21 times, I believe.

Granted:
1) openSUSE is not exactly the same SLES.
2) This is Leap, not Tumbleweed (though note that only Leap is supported).
3) The errors aren't identical.

But since errors still occur with Electron in Elsbeth Geranium, I figured I'd use the same issue. @kevinushey Let me know if you prefer that I open a separate issue for this instead.

**Comment by gsgxnet** [comment]
> @gsgxnet are you still seeing that warning with the latest build? Any other issues you're seeing?

@mikebessuille sorry mist that request while in holidays. See reply to @ronblum

**Comment by gsgxnet** [comment]
> Using RStudio Desktop 2022.12.0-daily+280 on openSUSE 15.4, I get the following error, so I'm reopening this.
> 
**here:** RStudio 2022.11.0-daily+236 "Elsbeth Geranium" Daily (613104930024b90843c71d509d5edf1ca06653f3, 2022-09-30) for OpenSUSE 15  
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2022.11.0-daily+236 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36
  
and
  
RStudio 2022.12.0-daily+284 "Elsbeth Geranium" Daily (1675d5d7a716a464208179336d3a99b1aaae90e4, 2022-10-21) for OpenSUSE 15
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2022.12.0-daily+284 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36

on Tumbleweed, version about 10 days behind latest

> ```
> vmware@localhost:~> [37935:1021/125157.321775:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> MESA-LOADER: failed to retrieve device information
> [37935:1021/125157.465226:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
> [37935:1021/125157.465597:ERROR:gbm_wrapper.cc(292)] Failed to export buffer to dma_buf: No such file or directory (2)
> ```
> 
> The "failed to export buffer" error messages appears 21 times, I believe.
> 
I see (11 236): 
```
/usr/bin/rstudio &
[1] 24208
~> [24245:1022/164945.903271:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
```

and (12 284):  

```
~> [31625:1022/171546.759791:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE is 
```

> Granted:
> 
> 1. openSUSE is not exactly the same SLES.  

yes, but now days very similar, partially the same repos AFAIK. Especially with 15.4
 
> 2. This is Leap, not Tumbleweed (though note that only Leap is supported).  

yes, as stated before, using the SLES 15 RStudio version under Leap 15 or Tumbleweed might produce errors not seen under SLES

> 
> 3. The errors aren't identical.  

true

> 
> But since errors still occur with Electron in Elsbeth Geranium, I figured I'd use the same issue. @kevinushey Let me know if you prefer that I open a separate issue for this instead.

**Comment by gsgxnet** [comment]
> @gsgxnet apart from the warnings and errors showing, are there any other symptoms? @jgutman we should figure out how serious these errors are. I'm not seeing anything in this ticket that makes it sound serious enough for Elsbeth, at this point.

@mikebessuille you might be right, for this seems to be only an annoying message. But it is not a warning, it says **ERROR**: 
`ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is desktop, ANGLE `
Whether it matters or not is up to you.  If not, perhaps you could change the coding in a way that it does emit a warning and not an error.  
Closing seems appropriate.
