### ISSUE TITLE
Find in Files no longer works after updating to 2202.07.1

### ISSUE THREAD

**Issue by AdrianHordyk** [rstudio/rstudio#11680]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36
    OS Version      :  Windows 10 V21H1
    R Version       :  4.2.1

### Steps to reproduce the problem
Enter a search term in 'Find in Files' under 'Edit' menu

### Describe the problem in detail
Find in Files returns nothing at all - 'No results found' regardless of what is entered in the Find dialog box.

I've noticed content of 'Search in' is now of the form: '~/GitHub/MyRepo' whereas before it was of the form: 'C:/users/user/documents/GitHub/MyRepo'.

Manually browsing to the R Project directory does not change anything. I use this feature all the time and haven't experienced this problem until updating to latest version of RStudio yesterday. 

Also tried deleting the .Rproj file.

Same problem occurs in all my R projects.

### Describe the behavior you expected

Search contents to appear in the 'Find in Files' section. 

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report! A couple other things that will be helpful:

- Do you have the [ ] Exclude files matched by .gitignore option set? (Is your project managed by git?)
- If you run the code `Sys.setenv(RSTUDIO_GREP_DEBUG = 1)` in the console, and then perform the search, what debug output do you see in the console?
- What version of Git for Windows do you have installed? If `git` is on the PATH, then `system("git --version")` should be the easiest way to check.

**Comment by AdrianHordyk** [comment]
> Do you have the [ ] Exclude files matched by .gitignore option set? (Is your project managed by git?)

Yes, managed by git. Have tried with both option set and not.

> If you run the code `Sys.setenv(RSTUDIO_GREP_DEBUG = 1)` in the console, and then perform the search, what debug output do you see in the console?

```
git "-c" "core.quotepath=false" "-c" "grep.lineNumber=true" "-c" "grep.column=false" "-c" "grep.patternType=default" "-c" "grep.extendedRegexp=false" "-c" "grep.fullName=false" "-C" "C:/Users/User/Documents/GitHub/MERA_site_latest" "grep" "-I" "--untracked" "--no-exclude-standard" "-rHn" "--color=always" "-i" "-F" "-f" "C:/Users/User/AppData/Local/Temp/Rtmpk1KDb9/rs_grepeb86e967881.txt"
stderr: error: unknown switch `r'
```


> What version of Git for Windows do you have installed? If git is on the PATH, then system("git --version") should be the easiest way to check.

git version 2.17.1.windows.2

## Note:
I've now found that the problem only seems to occur when I'm searching within any sub-directory in `~/GitHub` - where all my git-managed R projects are located. 
The search works fine for other locations, eg files in my Google Drive 'G:/My Drive/...'

In that case, the debug output in the console looks like:
```
"C:/Program Files/RStudio/bin/gnugrep/3.0/grep" "--binary-files=without-match" "-rHn" "--color=always" "-i" "-F" "-f" "C:/Users/User/AppData/Local/Temp/RtmpOwIQD1/rs_grep28642a6a5eba.txt" "--include=*.r" "--include=*.R" "--include=*.rnw" "--include=*.Rnw" "--include=*.rmd" "--include=*.Rmd" "--include=*.rmarkdown" "--include=*.Rmarkdown" "--include=*.qmd" "--include=*.Qmd" "--include=*.md" "--include=*.rhtml" "--include=*.Rhtml" "--include=*.h" "--include=*.hpp" "--include=*.c" "--include=*.cpp"
```

**Comment by ronblum** [comment]
@kevinushey Could it be related to issue #11635 that we're seeing in the 2022.10.0 builds? That release is Electron, though.

**Comment by kevinushey** [comment]
@ronblum I don't think so; in this particular case, it seems like `git grep` is being passed some flags it doesn't understand. At least, that's what the error message:

> stderr: error: unknown switch `r'

hints at. So this should be a separate issue.

**Comment by kevinushey** [comment]
> git version 2.17.1.windows.2

This is a pretty old version of git. Can you upgrade to the latest version of Git for Windows?

https://github.com/git-for-windows/git/releases/tag/v2.37.1.windows.1

**Comment by kevinushey** [comment]
That said, I think `git grep` is recursive by default, so if we wanted to support older versions of `git grep` we could just remove that flag. See:

https://git-scm.com/docs/git-grep#Documentation/git-grep.txt--r

**Comment by AdrianHordyk** [comment]
> This is a pretty old version of git. Can you upgrade to the latest version of Git for Windows?

Problem is fixed after updating git. Thanks!

**Comment by ronblum** [comment]
@AdrianHordyk Thanks for letting us know, and I'm glad that it works!

**Comment by samuelreuther** [comment]
Hi everybody,
as many others this function "find in files" together with "replace" saves me a lot of time and manual work.
As for now I could not fix the problem as described above (I'm depending on lots of other people to do system changes).
But I did find a small loophole to still get the function to work somehow (I have no idea why this works, though):
   => run the function "find in files" as you do usually
   => if no results are found, then re-run the function "find in files" again and again (sometimes it takes up to 10 tries)
Hope, this is helpful to others, too!
