### ISSUE TITLE
RMarkdown stops/pauses compiling when encountering a chunk with base R plots

### ISSUE THREAD

**Issue by taymourheikal** [rstudio/rstudio#11849]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.07.1 Build 554
    OS Version      :  macOS Monterey (version 12.3)
    R Version       :  4.2.1 (2022-06-23)

### Steps to reproduce the problem

-- Load the following packages:
```
<img width="972" alt="Screen Shot 2022-08-26 at 8 12 41 PM" src="https://user-images.githubusercontent.com/6901465/186967122-661c1dca-f6de-4bcc-844d-42c1689fc8cc.png">

 [1] gtools_3.9.3    digest_0.6.29   jsonlite_1.8.0  evaluate_0.16   rlang_1.0.4     cli_3.3.0      
 [7] remotes_2.4.2   gdata_2.18.0.1  rstudioapi_0.14 rmarkdown_2.16  tools_4.2.1     gotop_0.1.2    
[13] xfun_0.32       yaml_2.3.5      fastmap_1.1.0   compiler_4.2.1  htmltools_0.5.3 knitr_1.40
```
-- Have the following error:
```
Error in .rs.parsePackageDependencies(contents, extension) :
object 'partition_yaml_front_matter' not found
```
-- Start new .Rmd file with default ```summary(cars)``` and ```plot(pressure)``` and knit to HTML.

### Describe the problem in detail

Knitting RMarkdown won't continue rendering any **HTML files with base R plots without any errors**. The _Render_ window in RStudio shows that the **chunk with the plots is where the compiling has an issue**. It's been stuck here for at least 5 minutes.
```
|..........                                                            |  14%
  ordinary text without R code

  |....................                                                  |  29%


processing file: Untitled.Rmd
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |..............................                                        |  43%
  ordinary text without R code

  |........................................                              |  57%
label: cars
  |..................................................                    |  71%
  ordinary text without R code

  |............................................................          |  86%
label: pressure (with options) 
List of 1
 $ echo: logi FALSE

```
Commenting out plots like ```#plot(pressure)``` successfully renders the file immediately.

**Rendering is successful with ```ggplot2::ggplot(pressure)``` but doesn't display the plot as desired (screenshot attached).**

### Describe the behavior you expected

Plots are usually displayed without issue when compiling and rendering RMarkdown files.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Thanks for the bug report -- however, I'm not able to reproduce. Can you provide any other details? Is there anything unique about your R installation or how you've configured R / RStudio?

In addition, do you see the same behavior outside of RStudio if you render with e.g.

```
R -e 'rmarkdown::render("Untitled.Rmd")'
```

As an aside:

> Error in .rs.parsePackageDependencies(contents, extension) :
> object 'partition_yaml_front_matter' not found

This is likely unrelated; see https://github.com/rstudio/rstudio/issues/11552 for more details.

**Comment by dcaud** [comment]
Similar problem here. 

Rstudio never finishes rendering the default default rmarkdown template (copying the code into the github issue doesn't render the underlying markdown). However, all I did was File > New File > Markdown and then save and then hit the Knit button within Rstudio. It hangs toward the end of rendering. If I comment out this line:

```
plot(pressure)
```
making:

```
#plot(pressure)
```

Then the rendering works and I have an HTML file saved to disk.

I read elsewhere that some rmarkdown bug was fixed in a daily release of rstudio so I updated to a daily build, but the same problem persisted.

Heres my sessionInfo():

R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.2.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_4.2.1   fastmap_1.1.0    rsconnect_0.8.27 cli_3.3.0       
 [5] htmltools_0.5.3  tools_4.2.1      rstudioapi_0.14  yaml_2.3.5      
 [9] rmarkdown_2.16   knitr_1.40       xfun_0.32        digest_0.6.29   
[13] rlang_1.0.4      evaluate_0.16

**Comment by taymourheikal** [comment]
@kevinushey 
Thanks for the reply.

Yes, I get the same issue outside of RStudio: I have a Python script that calls an RMarkdown. When I call that Python script from Terminal, it halts at any chunk with base R plots. When I comment the R plot chunks out, it works.

Other details:
In trying to find a fix, I ran into #11552 (I thought the yaml error was related to my issue). Accordingly, I figured I'd try loading rlang up-front in ~/.Rprofile as was suggested. I ran ```startup::install()```  with the following output:
```
Creating R profile directory: '~/.Rprofile.d'
Creating R environment directory: '~/.Renviron.d'
Created new R startup file with 'startup::startup()': '~/.Rprofile'
[1] "~/.Rprofile"
```

I fell short of figuring out how to load rlang in ~/.Rprofile, but I think the above shows that I hadn't toyed around with .Renviron.d or .Rprofile before on this machine.
Note: I was already encountering my issue before I ran the above.

**Comment by taymourheikal** [comment]
I just tried downgrading some packages that may be causing the issue:
```remotes::install_version("rlang", "1.0.2")```
```remotes::install_version("htmltools", "0.5.2")```
```remotes::install_version("rmarkdown", "2.15")```
But the issue persists.

**Comment by taymourheikal** [comment]
Sorry for the repeated bombardment, but I just realized this isn't unique to RMarkdowns.
Trying a simple:
```plot(c(1,2,3),c(1,2,3))```
doesn't work either...

**Comment by dcaud** [comment]
I upgrading my Mac's operating system and now I no longer see this problem -- this shouldn't be needed and may not work for anyone else, but I thought it may be helpful for others in a bind. I wish Rstudio could make more informative error messages so that this didn't take 5+ hours of my time.
