### ISSUE TITLE
Error: Rstudio was unable to autosave this file

### ISSUE THREAD

**Issue by DiegoJArg** [rstudio/rstudio#11932]
### System details
RStudio 2022.07.1+554 "Spotted Wakerobin" Release (7872775ebddc40635780ca1ed238934c3345c5de, 2022-07-22) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.8 Chrome/69.0.3497.128 Safari/537.36

### Steps to reproduce the problem
Wake up laptop with a previous R-session open, and try to continue working. Error will appear after a few seconds.

### Describe the problem in detail
Attaching a Photo and Logs.
I don't know for sure if they relate, but logs at the same moment.
Inspecting the Log I note the time is wrong, since now it should be 07:42:37, probably related to this TCP error.
It is referencing to "C:\Users\jenkins", which is not an user of my desktop.

> 2022-09-11T10:42:37.011423Z [rsession-Note15] ERROR system error 10060 (Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder) [host: 127.0.0.1:64766, uri: /rpc/console_input, address: 127.0.0.1, port: 64766]; OCCURRED AT void __cdecl rstudio::core::http::TcpIpAsyncConnector::handleConnect(const class rstudio_boost::system::error_code &,class rstudio_boost::asio::ip::basic_resolver_iterator<class rstudio_boost::asio::ip::tcp>) C:\Users\jenkins\workspace\ide\open-source-pipeline\spotted-wakerobin\src\cpp\core\include\core/http/TcpIpAsyncConnector.hpp:210; LOGGED FROM: void __cdecl rstudio::session::modules::rmarkdown::notebook::`anonymous-namespace'::NotebookQueue::consoleThreadMain(void) C:\Users\jenkins\workspace\ide\open-source-pipeline\spotted-wakerobin\src\cpp\session\modules\rmarkdown\NotebookQueue.cpp:526

### Describe the behavior you expected
No errors

![Captura](https://user-images.githubusercontent.com/25246225/189523895-1f0e260d-5bb6-417a-925f-7e086f91e744.JPG)
[rsession-Note15.log](https://github.com/rstudio/rstudio/files/9542322/rsession-Note15.log)

**Comment by ronblum** [comment]
@DiegoJArg Thank you for raising this issue! I don't think we've run into this, but I'll mark it for review. By chance are you using a remote drive?

@kevinushey or @timtmok do you know what might be going on here or how to proceed?

**Comment by DiegoJArg** [comment]
No remote drive. But I have the files in a second partition D: which is exFAT formated. Could probably have a delay after waking up of hibernation?

**Comment by kevinushey** [comment]
> It is referencing to "C:\Users\jenkins", which is not an user of my desktop.

This is unrelated; this is just the path that was used when RStudio was built locally (so that's the path to the source file that was used when RStudio was compiled on the build machine).

Does the issue resolve itself if you restart the R session? Do you see any other issues when within this state?

**Comment by DiegoJArg** [comment]
That unrelated path is being outputed on the Logs as part of an error message. If doesn't provide information, It may be unrelated there too.
The problem get solved after restart, up to the next hibernation.

**Comment by timtmok** [comment]
The error sounds like it's the session failing after resuming from hibernation. If restarting the session resolves the issue, it would be a better experience if the IDE restarted the session.

**Comment by lijiaqi-github** [comment]
I have same the problem.

**Comment by Tripartio** [comment]
I updated to the latest versions on three different Windows 11 computers: R 4.3.1 and RStudio 2023.06.2 Build 451. I keep on getting this annoying pop-up error every 15 minutes or so. It is hard to make reproducible, but it always happens in the middle of typing. I suspect that it is triggered by an autocomplete step somewhere in RStudio.

**Comment by ACSoupir** [comment]
Hey, @timtmok . That is correct. Seems to be a rather intermittent issue. Sometimes within minutes of opening a project and other times doesn't happen at all.

Opening a new script and pasting the one that will no longer save, then overwriting the script that doesn't save still works so it's on a file-by-file basis (or window by window? not sure the appropriate term).

The autosave warning along with no longer being able to save the file manually seems to be the issue.

**Comment by serkor1** [comment]
Yeah, so this has been an ongoing issue for me as well. It doesn't matter whether my source file is in the cloud, or local. This is a rather serious bug, as it requires you to copy and paste everything to a new script, otherwise you will lose all the progress between last save, and the moment the error pops up.

**Comment by neellab-umd** [comment]
I started having this issue yesterday (14 October 2023) and it has now happened twice.  The first time it was after hibernation but the other was within 10 minutes of opening RStudio and starting a new R session in a project. My files are in the cloud but mirrored on my SSD. Once the message comes up, I am unable to manually save the script even when I change name or change from a cloud to a local directory.   Agree with previous posts that this is a serious problem that limits ability to work in RStudio without having to cut and paste out to another program and then remember to paste back into my scripts. 

RStudio 2023.09.0+463 "Desert Sunflower" Release (b51c81cc303d4b52b010767e5b30438beb904641, 2023-09-25) for windows.

R version 4.3.1 (2023-06-16 ucrt) 

My Windows Information is 
Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎8/‎17/‎2023
OS build	22621.2428
Experience	Windows Feature Experience Pack 1000.22674.1000.0

**Comment by Tripartio** [comment]
I cannot clearly trace any regular pattern to this except that it suspect it might be related to RStudio's autocomplete feature. I remember a somewhat similar bug from last year that was clearly linked to when RStudio tried to automatically suggest completed function or variable names. That was eventually fixed. This bug is a bit different but I suspect that it might be triggered by the same name suggestion event. I don't know if that makes sense.

I do not usually use RStudio on the cloud; I mainly use it on Windows (two Windows 11 machines and one Windows 10). Fortunately, on my local computers, there is no data lost--the problem is simply an annoyance. They all have the same problem. Here are my specs on the computer from which I'm writing this. 

Edición	Windows 11 Pro
Versión	22H2
Instalado el	‎04/‎12/‎2022
Versión del sistema operativo	22621.2428
Experiencia	Windows Feature Experience Pack 1000.22674.1000.0

R version 4.3.1 (2023-06-16 ucrt) -- "Beagle Scouts"
Copyright (C) 2023 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

RStudio 2023.09.0+463 "Desert Sunflower" Release (b51c81cc303d4b52b010767e5b30438beb904641, 2023-09-25) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.09.0+463 Chrome/114.0.5735.289 Electron/25.5.0 Safari/537.36

**Comment by dkiser-c** [comment]
I'm getting the same error messages. I'm working in R version 4.3.1 "Beagle Scouts" and RStudio 2023.06.2 "Mountain Hydrangea". My OS is Microsoft Windows Server 2019 Datacenter. I was wondering if it had something to do with being a virtual machine, but that's outside my wheel-house. Sometimes it works to copy and paste my script to a new file in the same RStudio instance, and sometimes it doesn't. Sometimes the errors begin again shortly after restarting RStudio.

**Comment by serkor1** [comment]
I have noticed that when this issue comes up, and you wait a bit - you are still able to save. It happens that it creates a conflicted file, but it saves nevertheless. 

For me the problem arises sporadically. Running on Ubuntu 20.04, 22.04 and Zorin OS 16. Latest R and R Studio  versions.

**Comment by dkiser-c** [comment]
Going to Tools > Global Options > Code > Saving, unchecking the boxes for "Always save R scripts before sourcing" and "Automatically save when editor loses focus", and changing the option for "When editor is idle" to "Do nothing" seems to have stopped the error from happening for me. I'm sure it's not the ideal solution, but maybe a decent temporary fix.

**Comment by neellab-umd** [comment]
dkieser-C - Thanks for a potential solution - the first I have seen!  All of those except "Always save R scripts before sourcing" were already off for me.  I can't see that it will matter, but I turned off "Always save R scripts before sourcing"  and will hope for the best.

**Comment by lijiaqi-github** [comment]
My situation is, I have the same settings with dkiser-c, but I still met this issue. However, in the latest version, this issue almost doesn't happen anymore.

**Comment by Tripartio** [comment]
I still face this regularly and randomly, on three different Windows computers, even with the latest version of RStudio (2023.12.1+402). I'm surprised that in over a year, with such a blatant bug, there has been no action whatsoever taken to isolate and correct it.

**Comment by serkor1** [comment]
> I still face this regularly and randomly, on three different Windows computers, even with the latest version of RStudio (2023.12.1+402). I'm surprised that in over a year, with such a blatant bug, there has been no action whatsoever taken to isolate and correct it.

@Tripartio are you using any kind of cloud for your scripts and projects? I moved away from using cloud-linked folders and the frequency of this error occurring dropped dramatically.

**Comment by jmcastagnetto** [comment]
Just to add a data point. After updating RStudio (on Ubuntu 22.04.4 LTS) to the latest version (vide infra), I am encountering the same issue with projects that are on the local disk, and that previously had not shown this problem: e.g. a project I created back in early 2018. Similar issues with newly created projects that might have a few lines of code on an unnamed buffer.

Often after quiting and restarting it keeps working, but usually with some loss of code.

```
RStudio 2023.12.1+402 "Ocean Storm" Release (4da58325ffcff29d157d9264087d4b1ab27f7204, 2024-01-29) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.12.1+402 Chrome/116.0.5845.190 Electron/26.2.4 Safari/537.36
```

Just for completeness, here is R version I got installed:

```bash
$ R --version
R version 4.3.3 (2024-02-29) -- "Angel Food Cake"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.
```

**Comment by kevinushey** [comment]
@jmcastagnetto, the next time this issue occurs, can you share what you see when you execute this from a Terminal?

```
pgrep rsession
```

I ask because I've seen something similar in the past when older `rsession` processes were, for some reason, still alive in the background -- I wonder if you're seeing something similar.

**Comment by jmcastagnetto** [comment]
@kevinushey 
> @jmcastagnetto, the next time this issue occurs, can you share what you see when you execute this from a Terminal?
> 
> ```
> pgrep rsession
> ```
> 
> I ask because I've seen something similar in the past when older `rsession` processes were, for some reason, still alive in the background -- I wonder if you're seeing something similar.

Sure thing will do and report the results. So far has not happened today :crossed_fingers:

**Comment by jmcastagnetto** [comment]
@kevinushey 

After updating R to 4.4, I have not experienced thus issue anymore in RStudio under Ubuntu 22.04 or 24.04 (tried on my 2 boxes).

**Comment by kevinushey** [comment]
That's great to hear! Please let us know if the issue happens to arise again.

**Comment by tripartio** [comment]
I have upgraded to R 4.4.0 and RStudio for Windows 2024.04.1 Build 748; both are the latest versions as of today.

On one hand, I can confirm that the bug comes up much less frequently. It's been over a week since I had it.

On the other hand, unfortunately, it popped up just now while auto-suggesting something for me:

![image](https://github.com/rstudio/rstudio/assets/7702487/5ce89c2d-f0a5-45d5-9378-0be659325ab4)

So, the bug is not yet gone. :-(

**Comment by serkor1** [comment]
Has this bug even been officially addressed by the devs?

**Comment by abalter** [comment]
This is still a bug for me.

**Comment by kevinushey** [comment]
https://github.com/rstudio/rstudio/pull/15200 should help ensure that RStudio doesn't attempt to auto-save documents in situations where it's likely to fail (e.g. during a session restart, or after a session is already quitting), but it's plausible that this issue could still occur in other scenarios.

**Comment by gtritchie** [comment]
Moved to Later, we'll see if the improvements in #15200 make a difference in the upcoming Kousa Dogwood (2024.12) release, and take another look if the problem is still happening.

**Comment by MasaKusar** [comment]
It became an issue for me when I updated to 2024.12. 

I get either the above autosave issue or one of the "Unable to establish connection with R session when executing ..." popups, depending on what I'd just tried to do. This was not an issue previously. Wiping everything and reinstalling the newest R and RStudio has not helped.

This is happening on two computers running Windows 10.

**Comment by kevinushey** [comment]
@MasaKusar: can you please file a separate issue with more details regarding what you're seeing?
