### ISSUE TITLE
Verbose testthat output

### ISSUE THREAD

**Issue by dpprdan** [rstudio/rstudio#11969]
### System details

    RStudio Edition : Desktop
	RStudio Version : RStudio 2022.11.0-daily+173 "Elsbeth Geranium" Daily (76585f6cb30fff5acca8555a3634e1241fef7a40, 2022-09-09) for Windows
                      Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+173 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36
    OS Version      : Windows 10 x64 (build 19044)
    R Version       :  4.2.1 (2022-06-23 ucrt)

### Steps to reproduce the problem

1. Create new file test.R with 

	```r
    test_that("multiplication works", {
    	  expect_equal(2 * 2, 4)
          expect_equal(2 * 3, 6)
	})
    ```

2. Execute tests with "Run Tests" button (testthat needs to be installed).

Update: Repo with the test file and steps to reproduce: [dpprdan/test.testthat](https://github.com/dpprdan/test.testthat)

### Describe the problem in detail

Output shown in test window:

```r
==> Testing R file using 'testthat'


══ Testing test-test.R ═════════════════════════════════════════════════════════

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 1 ]
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 2 ] Done!

Test complete
```

I.e. the testthat results output is rather verbose with one line per expectation (plus one).

### Describe the behavior you expected

Just one 

	[ FAIL 0 | WARN 0 | SKIP 0 | PASS 0 ]

line that updates itself after every expectation until all tests are finished. 

cf. https://github.com/r-lib/testthat/issues/1561

Gabor thinks this is [should be fixed in RStudio](https://github.com/r-lib/testthat/issues/1561#issuecomment-1244036921):

 > It is not expected, the IDE probably had some assumptions about testthat output, which do not hold any more.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by romainfrancois** [comment]
@dpprdan can you share your `sessioninfo::package_info("testthat")`, in particular do you have latest `cli`

```r
> sessioninfo::package_info("testthat")
 package   * version    date (UTC) lib source
 brio        1.1.3      2021-11-30 [1] CRAN (R 4.2.0)
 callr       3.7.2      2022-08-22 [1] CRAN (R 4.2.0)
 cli         3.4.0      2022-09-08 [1] CRAN (R 4.2.0)
 crayon      1.5.1      2022-03-26 [1] CRAN (R 4.2.0)
 desc        1.4.2      2022-09-08 [1] CRAN (R 4.2.0)
 diffobj     0.3.5      2021-10-05 [1] CRAN (R 4.2.0)
 digest      0.6.29     2021-12-01 [1] CRAN (R 4.2.0)
 ellipsis    0.3.2      2021-04-29 [1] CRAN (R 4.2.0)
 evaluate    0.16       2022-08-09 [1] CRAN (R 4.2.0)
 fansi       1.0.3      2022-03-24 [1] CRAN (R 4.2.0)
 fs          1.5.2      2021-12-08 [1] CRAN (R 4.2.0)
 glue        1.6.2      2022-02-24 [1] CRAN (R 4.2.0)
 jsonlite    1.8.0      2022-02-22 [1] CRAN (R 4.2.0)
 lifecycle   1.0.2      2022-09-09 [1] CRAN (R 4.2.0)
 magrittr    2.0.3      2022-03-30 [1] CRAN (R 4.2.0)
 pillar      1.8.1      2022-08-19 [1] CRAN (R 4.2.0)
 pkgconfig   2.0.3      2019-09-22 [1] CRAN (R 4.2.0)
 pkgload     1.3.0      2022-06-27 [1] CRAN (R 4.2.0)
 praise      1.0.0      2015-08-11 [1] CRAN (R 4.2.0)
 processx    3.7.0      2022-07-07 [1] CRAN (R 4.2.0)
 ps          1.7.1      2022-06-18 [1] CRAN (R 4.2.0)
 R6          2.5.1      2021-08-19 [1] CRAN (R 4.2.0)
 rematch2    2.1.2      2020-05-01 [1] CRAN (R 4.2.0)
 rlang       1.0.5      2022-08-31 [1] CRAN (R 4.2.0)
 rprojroot   2.0.3      2022-04-02 [1] CRAN (R 4.2.0)
 testthat    3.1.4      2022-04-26 [1] CRAN (R 4.2.0)
 tibble      3.1.8      2022-07-22 [1] CRAN (R 4.2.0)
 utf8        1.2.2      2021-07-24 [1] CRAN (R 4.2.0)
 vctrs       0.4.1.9000 2022-09-23 [1] Github (r-lib/vctrs@0a219ba)
 waldo       0.4.0      2022-03-16 [1] CRAN (R 4.2.0)
 withr       2.5.0      2022-03-03 [1] CRAN (R 4.2.0)

 [1] /Users/romainfrancois/.R/library/4.2
 [2] /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library
```

This also works for me with latest rstudio daily (elsbeth-geranium series) and latest all packages. I believe this was fixed with joint work in `cli` and rstudio. 

<img width="451" alt="image" src="https://user-images.githubusercontent.com/2625526/191914466-56fe6a79-0b7a-4594-be6b-c0b405383782.png">

**Comment by dpprdan** [comment]
I still saw the same problem yesterday with elsbeth-geranium and latest testthat (GH) and cli (CRAN 3.4.0), see full session info:
https://github.com/r-lib/testthat/issues/1561#issuecomment-1254879773

Could this be a Windows-only problem (now)? You, Davis and Hadley are on Mac I assume?

Will double-check on another Windows machine later.

**Comment by dpprdan** [comment]
Checked again inside a Windows Sandbox with latest RStudio daily, testhat and cli, same result. 

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

```
RStudio 2022.11.0-daily+210 "Elsbeth Geranium" Daily (7cb497c2e59769c49857efaffac8fa03cf4edae8, 2022-09-23) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2022.11.0-daily+210 Chrome/102.0.5005.167 Electron/19.0.10 Safari/537.36
```

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.2.1 (2022-06-23 ucrt)
#>  os       Windows 10 x64 (build 19041)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  English_United States.utf8
#>  ctype    English_United States.utf8
#>  tz       Europe/Berlin
#>  date     2022-09-23
#>  pandoc   2.19.2 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  brio          1.1.3      2021-11-30 [1] CRAN (R 4.2.1)
#>  cli           3.4.0.9000 2022-09-23 [1] Github (r-lib/cli@af229bc)
#>  digest        0.6.29     2021-12-01 [1] CRAN (R 4.2.1)
#>  evaluate      0.16       2022-08-09 [1] CRAN (R 4.2.1)
#>  fastmap       1.1.0      2021-01-25 [1] CRAN (R 4.2.1)
#>  fs            1.5.2      2021-12-08 [1] CRAN (R 4.2.1)
#>  glue          1.6.2      2022-02-24 [1] CRAN (R 4.2.1)
#>  highr         0.9        2021-04-16 [1] CRAN (R 4.2.1)
#>  htmltools     0.5.3      2022-07-18 [1] CRAN (R 4.2.1)
#>  knitr         1.40       2022-08-24 [1] CRAN (R 4.2.1)
#>  lifecycle     1.0.2      2022-09-09 [1] CRAN (R 4.2.1)
#>  magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.2.1)
#>  R6            2.5.1      2021-08-19 [1] CRAN (R 4.2.1)
#>  reprex        2.0.2      2022-08-17 [1] CRAN (R 4.2.1)
#>  rlang         1.0.5      2022-08-31 [1] CRAN (R 4.2.1)
#>  rmarkdown     2.16       2022-08-24 [1] CRAN (R 4.2.1)
#>  rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.2.1)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.2.1)
#>  stringi       1.7.8      2022-07-11 [1] CRAN (R 4.2.1)
#>  stringr       1.4.1      2022-08-20 [1] CRAN (R 4.2.1)
#>  testthat    * 3.1.4.9000 2022-09-23 [1] Github (r-lib/testthat@1c9947d)
#>  withr         2.5.0      2022-03-03 [1] CRAN (R 4.2.1)
#>  xfun          0.33       2022-09-12 [1] CRAN (R 4.2.1)
#>  yaml          2.3.5      2022-02-21 [1] CRAN (R 4.2.1)
#> 
#>  [1] C:/Program Files/R/R-4.2.1/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

FWIW I created a repo with the test file and steps to reproduce https://github.com/dpprdan/test-testthat

**Comment by dpprdan** [comment]
This is still an issue with a recent daily and dev versions of testthat and cli.

<details>
<summary>Session Info</summary>

```
RStudio 2023.08.0-daily+172 "Desert Sunflower" Daily (a90f3a9d8c4ffa765e737483f491413d1f80aad8, 2023-07-04) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.08.0-daily+172 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
```

```
─ Session info ─────────────────────────────────────────────────────────────────────────────
 setting  value
 version  R version 4.3.1 (2023-06-16 ucrt)
 os       Windows 10 x64 (build 19041)
 system   x86_64, mingw32
 ui       RStudio
 language (EN)
 collate  English_United States.utf8
 ctype    English_United States.utf8
 tz       Europe/Berlin
 date     2023-07-06
 rstudio  2023.08.0-daily+172 Desert Sunflower (desktop)
 pandoc   NA

─ Packages ─────────────────────────────────────────────────────────────────────────────────
 package     * version    date (UTC) lib source
 brio          1.1.3      2021-11-30 [1] CRAN (R 4.3.1)
 cli           3.6.1.9000 2023-07-04 [1] Github (r-lib/cli@7eb56eb)
 desc          1.4.2      2022-09-08 [1] CRAN (R 4.3.1)
 glue          1.6.2      2022-02-24 [1] CRAN (R 4.3.1)
 magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.3.1)
 pkgload       1.3.2      2022-11-16 [1] CRAN (R 4.3.1)
 R6            2.5.1      2021-08-19 [1] CRAN (R 4.3.1)
 rlang         1.1.1      2023-04-28 [1] CRAN (R 4.3.1)
 rprojroot     2.0.3      2022-04-02 [1] CRAN (R 4.3.1)
 rstudioapi    0.14       2022-08-22 [1] CRAN (R 4.3.1)
 sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.3.1)
 testthat    * 3.1.9.9000 2023-07-04 [1] Github (r-lib/testthat@d40b74f)
 waldo         0.5.1      2023-05-08 [1] CRAN (R 4.3.1)
 withr         2.5.0      2022-03-03 [1] CRAN (R 4.3.1)

 [1] C:/Program Files/R/R-4.3.1/library

────────────────────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by kevinushey** [comment]
Interestingly, this is an issue with single-file tests, but not with `devtools::test()`?

**Comment by kevinushey** [comment]
We set some environment variables so that `cli` etc. can figure out where console output is being written:

https://github.com/rstudio/rstudio/blob/93434d9a8ed4b5da8da74f16c5f624770f95e300/src/cpp/session/modules/build/SessionBuild.cpp#L312-L323

Maybe we need to be setting those when testing single files as well?

https://github.com/rstudio/rstudio/blob/93434d9a8ed4b5da8da74f16c5f624770f95e300/src/cpp/session/modules/build/SessionBuild.cpp#L869-L872

**Comment by dpprdan** [comment]
> Interestingly, this is an issue with single-file tests, but not with devtools::test()?

With the Build > Test button (same with `devtools::test()` in the console):
```r
==> devtools::test()

ℹ Testing test.testthat
✔ | F W S  OK | Context
✔ |         2 | testthat                                                       

══ Results ════════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 2 ]
```

All other variants I could think of look fine in the console:

```r
> devtools::test_active_file()
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 2 ]
> testthat::test_file(path = "tests/testthat/test-testthat.R")
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 2 ]
> testthat::test_local()
✔ | F W S  OK | Context
✔ |         2 | testthat                                                                      

══ Results ═══════════════════════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 2 ]

🧿 Your tests look perfect 🧿
> testthat::test_dir(path = "tests/testthat/")
✔ | F W S  OK | Context
✔ |         2 | testthat                                                                      

══ Results ═══════════════════════════════════════════════════════════════════════════════════
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 2 ]
```

So AFAICT this only happens when running tests via the "Run Tests" button on a single file. 

> Maybe we need to be setting those [env vars] when testing single files as well?

Maybe. Note however that [it works on Hadleys machine](https://github.com/r-lib/testthat/issues/1561#issuecomment-1254926719), i.e. it seems to be a Windows-only problem (haven't (because cannot easily) tested on Windows 11).

**Comment by kevinushey** [comment]
Here's an example of the output we're getting from the test process:

```
== RESPONSE ======
{
  "result": [
    {
      "id": 228,
      "type": "build_output",
      "data": {
        "type": 1,
        "output": "\r\n[ FAIL 0 | WARN 0 | SKIP 0 | PASS 11 ]\r\n[ FAIL 0 | WARN 0 | SKIP 0 | PASS 12 ]\r\n[ FAIL 0 | WARN 0 | SKIP 0 | PASS 13 ]\r\n[ FAIL 0 | WARN 0 | SKIP 0 | PASS 14 ]"
      }
    }
  ],
  "ep": "false"
}
```

So, for some reason, `testthat` is indeed emitting newlines when displaying output, and that's causing the issue here.

**Comment by dpprdan** [comment]
So back to https://github.com/r-lib/testthat/issues/1561 @kevinushey?

**Comment by kevinushey** [comment]
Hmm, I'm not sure if I can conclude that just yet. It _does_ work on non-Windows machines, so I think we'll have to do some more work to confirm if the issue is on the IDE side or not.

**Comment by kevinushey** [comment]
I wrote down some investigation in https://github.com/r-lib/testthat/issues/1561#issuecomment-1629770700 -- I think we'll have to change RStudio to accommodate here.

**Comment by dpprdan** [comment]
I am seeing some new behaviour in RStudio which might possibly be related.

When I start a background job (Source > Source as Background Job...) the "Background Jobs" tab shows the following:

```
 ■                                  0% |  ETA: 45m
 ■                                  0% |  ETA: 36m
 ■                                  0% |  ETA: 36m
 ■                                  0% |  ETA: 35m
 ■                                  1% |  ETA: 32m
 ■                                  1% |  ETA: 30m
 ■                                  1% |  ETA: 30m
 ■                                  1% |  ETA: 29m
 ■                                  1% |  ETA: 29m
 ■■                                 2% |  ETA: 28m
 ■■                                 2% |  ETA: 28m
 ■■                                 2% |  ETA: 28m
 ■■                                 2% |  ETA: 27m
 ■■                                 2% |  ETA: 26m
 ■■                                 3% |  ETA: 26m
 ■■                                 3% |  ETA: 26m
 ■■                                 3% |  ETA: 26m
 ■■                                 3% |  ETA: 25m
 ■■                                 4% |  ETA: 25m
 ■■                                 4% |  ETA: 24m
 ■■                                 4% |  ETA: 24m
 ■■                                 4% |  ETA: 23m
 ■■                                 5% |  ETA: 23m
 ■■■                             
...
```

with a new line appearing every 3-4 seconds. I assume this is also {cli} output?

```
RStudio 2023.06.1+524 "Mountain Hydrangea" Release (547dcf861cac0253a8abb52c135e44e02ba407a1, 2023-07-07) for windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.06.1+524 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
```

**Comment by kevinushey** [comment]
Thanks @olivroy!

**Comment by ronblum** [comment]
Verified in RStudio Desktop 2024.07.0-daily+219 on Windows 11. Checked several versions of `testthat`: 3.2.1 (current) , 3.1.9 (a year old), and 3.1.2 (from https://github.com/r-lib/testthat/issues/1561).
