### ISSUE TITLE
"Find in Files" returns "(No results found)" in latest RStudio IDE version on a cloud drive

### ISSUE THREAD

**Issue by bison3** [rstudio/rstudio#11994]
### System details

    RStudio Edition : Desktop
    RStudio Version :  2022.07.1 Build 554
    OS Version      :  Windows 10 Pro 21H2
    R Version       :  4.1.2

### Steps to reproduce the problem
This can, hopefully, be recreated by running the latest version of RStudio with the latest version of GIT on the latest version of PCloud Drive. However, the problem only started after the RStudio update.
When I search any project that's located on the cloud drive (but not on my local drives) I get "(No results found)" no matter the search.
By enabling RSTUDIO_GREP_DEBUG via
`Sys.setenv(RSTUDIO_GREP_DEBUG = 1)`
I get the following error:

> git "-c" "core.quotepath=false" "-c" "grep.lineNumber=true" "-c" "grep.column=false" "-c" "grep.patternType=default" "-c" "grep.extendedRegexp=false" "-c" "grep.fullName=false" "-C" "P:/ffa/Repos/ffaGolemApp" "grep" "-I" "--untracked" "--no-exclude-standard" "-rHn" "--color=always" "-i" "-F" "-f" "C:/Users/Adam/AppData/Local/Temp/RtmpIPzB29/rs_grep251c9a31060.txt" "--" "*.r" "*.R"
> stderr: fatal: detected dubious ownership in repository at 'P:/ffa/Repos/ffaGolemApp
> 
> 
> 'P:/ffa/Repos/ffaGolemApp' is on a file system that doesnot record ownership
> To add an exception for this directory, call:
> 
> 	git config --global --add safe.directory P:/ffa/Repos/ffaGolemApp`

I have run the git code for adding the directory as an exception, but the problem doesn't resolve and the same error appears.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
You could also try:

```
git config --global --add safe.directory '*'
```

**Comment by ValValetl** [comment]
I have the same problem. In my case, the `git config --global --add safe.directory` command did work and the path appears correctly in the .gitconfig file (and is correctly recognized by the git gui I use). However, the bug still occurs. 

**System details**
```
RStudio Edition : Desktop
RStudio Version : 2022.7.2.576
OS Version      : Windows 10 build 19044
R Version       : 4.1.2
Git version     : 2.37.3
```

**Comment by kevinushey** [comment]
> However, the bug still occurs.

To confirm, are you saying that even with this set:

```
Sys.setenv(RSTUDIO_GREP_DEBUG = 1)
```

you're still seeing the same Find in Files issue?

**Comment by ValValetl** [comment]
yes. this setting (`Sys.setenv(RSTUDIO_GREP_DEBUG = 1)`) is even necessary to see any error message regarding this bug.

**Comment by bison3** [comment]
> > However, the bug still occurs.
> 
> To confirm, are you saying that even with this set:
> 
> ```
> Sys.setenv(RSTUDIO_GREP_DEBUG = 1)
> ```
> 
> you're still seeing the same error message?

Thank you Kevin for your suggestion. Like Val, I'm also still experiencing the error.

**Comment by kevinushey** [comment]
Apparently this is a pretty recent change in Git:

https://github.com/git/git/commit/3b0bf2704980b1ed6018622bdf5377ec22289688

So presumedly everyone encountering this issue has updated to v2.30.5 or newer? I don't know why the proposed fix reported by Git isn't working for you, though.

**Comment by ValValetl** [comment]
> So presumedly everyone encountering this issue has updated to v2.30.5 or newer? 
I tried with the latest (2.37.3) git version.

**Comment by bison3** [comment]
> > So presumedly everyone encountering this issue has updated to v2.30.5 or newer?
> 
> I tried with the latest (2.37.3) git version.

As did I.

**Comment by bschulth** [comment]
Additional data points, I get `stderr: error: unknown switch 'r'`.
What's the recommended sweet spot for Git a version?

```sh
RStudio Edition : RStudio Workbench
RStudio Version : 2022.07.2 Build 576.pro12
OS Version      : Ubuntu 18.04
R Version       : 4.1.3
Git version     : 2.17.1
```

```sh
> Sys.setenv(RSTUDIO_GREP_DEBUG = 1)
git '-c' 'core.quotepath=false' '-c' 'grep.lineNumber=true' '-c' 'grep.column=false' '-c' 'grep.patternType=default' '-c' 'grep.extendedRegexp=false' '-c' 'grep.fullName=false' '-C' '/home/bschulth/r_projects/dbcrud' 'grep' '-I' '--untracked' '--no-exclude-standard' '-rHn' '--color=always' '-i' '-F' '-f' '/tmp/RtmpXZmsVP/rs_grep82b5c8f1e24.txt'
stderr: error: unknown switch `r'
usage: git grep [<options>] [-e] <pattern> [<rev>...] [[--] <path>...]

    --cached              search in index instead of in the work tree
    --no-index            find in contents not managed by git
    --untracked           search in both tracked and untracked files
    
    <snip>
```

**Comment by bschulth** [comment]
**UPDATE**, for my case, I can confirm that upgrading Git from `2.17.1` (the Ubuntu 18.04 default) to `2.24.0` restores my find in files functionality.

**Comment by kevinushey** [comment]
@bschulth thanks! I think yours is a separate issue; RStudio is passing a flag (`-r`) to `git grep` which unfortunately isn't compatible with older versions of `git`. This should be fixed in the next release of RStudio regardless, though.

**Comment by paddytobias** [comment]
I am also having the same issue, which seems to have been introduced since upgrading to RStudio 2022.07.1 recently. I have tried running the suggested `git config --global --add safe.directory '*'` and still get the same issue as reported by @bison3
