### ISSUE TITLE
Bad binding access?

### ISSUE THREAD

**Issue by DavisVaughan** [rstudio/rstudio#12456]
@romainfrancois I am guessing this might be related to those changes in the daily that caused that other crash, but I'm not sure

If I run this in a recent daily, I get this error pretty consistently. It locks up my RStudio session and I eventually have to force quit it.

It doesn't show up on older versions of RStudio or when run from the command line. It also isn't tied to `vec_match()`, I was able to reproduce with other functions too.

```r
x <- sample(1e7, 1e6)
y <- sample(1e7, 1e6)

for (i in 1:100) {
  vctrs::vec_match(x, y)
}
```

https://user-images.githubusercontent.com/19150088/208268041-41148af0-e098-47d1-b0e2-52cce17835a1.mov

**Comment by romainfrancois** [comment]
There was a problem that started on build 25. I'll check but I do think it was fixed in more recent builds.

**Comment by DavisVaughan** [comment]
I'm somewhat confident i was on the latest daily yesterday. Let me know if you can't reproduce and I'll go redownload the daily and try again to make sure

**Comment by romainfrancois** [comment]
I haven't been able to reproduce with this build RStudio 2023.03.0-daily+31 "Cherry Blossom" Daily (33e7fedb1583c9071cc4f7a8e802b82b3900a8f0, 2022-12-16) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0-daily+31 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36

I'll investigate some more. The error comes from `CAR()` : 
https://github.com/r-devel/r-svn/blob/0d65935f30dcaccfeee1dd61991bf4b1444873bc/src/include/Rinlinedfuns.h#L89

**Comment by DavisVaughan** [comment]
I can still reproduce with the same version:

RStudio 2023.03.0-daily+31 "Cherry Blossom" Daily (33e7fedb1583c9071cc4f7a8e802b82b3900a8f0, 2022-12-16) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0-daily+31 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36

R 4.2.2 if that matters

**Comment by romainfrancois** [comment]
Thanks. That's a puzzle. Probably overlooked something with: 

```c
static SEXP getActiveValue(SEXP);
static R_INLINE SEXP BINDING_VALUE(SEXP b)
{
    if (BNDCELL_TAG(b)) {
	R_expand_binding_value(b);
	return CAR0(b);
    }
    if (IS_ACTIVE_BINDING(b)) return getActiveValue(CAR(b));
    else return CAR(b);
}
```

**Comment by romainfrancois** [comment]
That may be related to this: https://github.com/r-devel/r-svn/blob/0d65935f30dcaccfeee1dd61991bf4b1444873bc/doc/notes/immbnd.md

**Comment by romainfrancois** [comment]
If this is the case, we could simply rule out "immediate bindings" i.e. they're not going to have external pointers, probably here: 

https://github.com/rstudio/rstudio/blob/33e7fedb1583c9071cc4f7a8e802b82b3900a8f0/src/cpp/session/modules/environment/SessionEnvironment.cpp#L163-L174

**Comment by romainfrancois** [comment]
cc @DavisVaughan can you have a look and see if #12478 changed this for you using a build from https://dailies.rstudio.com/rstudio/cherry-blossom/electron/macos/ ?

**Comment by DavisVaughan** [comment]
I can no longer reproduce my original issue!

RStudio 2023.03.0-daily+293 "Cherry Blossom" Daily (df7efaa7c605d91399201ad68eb607d5c16fda54, 2023-02-06) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0-daily+293 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

R 4.2.2
