### ISSUE TITLE
Error Box: Error Retrieving Help

### ISSUE THREAD

**Issue by mikecrobp** [rstudio/rstudio#12918]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Windows
    OS Version      :  Windows 10
    R Version       :  4.2.2 (2022-10-31 ucrt)

### Steps to reproduce the problem
Not possible. It is an intermittent problem. But the current incarnation stops me from typing in any new code - even though I can still type to console

### Describe the problem in detail
An error box comes up saying Error Retrieving Help Error in if (nchar(current) > nchars) {: missing value where TRUE/FALSE needed
Note 2 other users report the same behaviour in Posit Community

### Describe the behavior you expected
No error box

- [x ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x ] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
Probably from here. https://github.com/rstudio/rstudio/blob/b2d7353fdf45be8168d19db2de3dea9b6f84bc40/src/cpp/session/modules/SessionHelp.R#L465-L490

**Comment by cbeesonlynch** [comment]
I'm having the same issue after I updated R Studio - I do not have anything in my script about nchars, and it's happening randomly.

**Comment by drande09** [comment]
I'm getting this same error: 
![image](https://user-images.githubusercontent.com/57731834/228916677-af490a7f-76e7-490a-8ba7-2d408d72d350.png)
It happens pretty consistently when I try to press tab to get variable names in a mutate() call, or similar.

**Comment by mbedward** [comment]
@drande09 does it only happen with variable names containing underscores? That seems to be the pattern for me.

**Comment by kevinushey** [comment]
A reproducible example would indeed be helpful.

**Comment by drande09** [comment]
Here's the information about the data frame: 
![image](https://user-images.githubusercontent.com/57731834/229796333-47fe7b7f-661f-4d2f-b68c-68090c9e3dde.png)

https://user-images.githubusercontent.com/57731834/229797371-2608b67e-98c1-43f3-b646-dc7d27da8e95.mp4


Here is my system info: 
Windows 11

RStudio 2023.03.0+386 "Cherry Blossom" Release (3c53477afb13ab959aeb5b34df1f10c237b256c3, 2023-03-09) for Windows
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2023.03.0+386 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36

![image](https://user-images.githubusercontent.com/57731834/229796508-ad998cfd-be27-4375-bccc-0e1eb831ed34.png)

**Comment by drande09** [comment]
Yeah - actually I can confirm the underscores hypothesis holds true for me, too. I'm not getting these errors in other dataframes with camelCase variable names

**Comment by adamdoescode** [comment]
I am getting this when the autocomplete dialog comes up for a data.frame I have in memory.

**Comment by envanloo** [comment]
Same problem here after update of Rstudio. Version: 2023.03.0 Build 386. "Cherry Blossom" Release (3c53477a, 2023-03-09) for Windows. R-version: R4.1.0

No problems with same code while editing before update of Rstudio. I have the problem with the data.table p4 (see below).

When I start typing "p4$" it shows a list with all columns, when I complete until "p4$dt" the error box pops up:

"Error Retrieving Help
Error in if (nchar(current) > nchars) {:
   missing value where TRUE/FALSE needed"

While typing p4$ it starts showing the column names in a white box. You can continue typing until "dt" and then it tries to show the values of dt1 (as it is earlier in the list with column names). Also going through the list with cursor goes OK until dt1 is reached. It wants to show the values in a yellow box (Rstudio does this! New feature?) and when the first element is a NA it drops the error. So problem related to the autocomplete dialog as @adamdoescode has indicated.

> str(p4)
Classes ‘data.table’ and 'data.frame':	67 obs. of  21 variables:
 $ V1             : chr  "2022-10-31" "2022-11-01" "2022-11-02" "2022-11-03" ...
 $ V2             : chr  "16:35:13.809019" "17:01:20.903847" "10:25:19.915701" "11:39:49.761462" ...
 $ V3             : chr  "47.993" "14.012" "7.105" "15.008" ...
 $ V4             : chr  "4718" "4752" "4759" "4751" ...
 $ V5             : chr  "4766" "4767" "4766" "4766" ...
 $ Date           : chr  "2022-10-31" "2022-11-01" "2022-11-02" "2022-11-03" ...
 $ Time           : chr  "16:35:13.809019" "17:01:20.903847" "10:25:19.915701" "11:39:49.761462" ...
 $ dt             : POSIXct, format: "2022-10-31 16:35:13" "2022-11-01 17:01:20" "2022-11-02 10:25:19" "2022-11-03 11:39:49" ...
 $ plag           : chr  NA "4766" "4767" "4766" ...
 $ dt1            : POSIXct, format: NA "2022-10-31 16:35:13" "2022-11-01 17:01:20" "2022-11-02 10:25:19" ...
 $ absweightchange: num  NA 14 8 15 12 20 17 23 10 31 ...
 $ rate           : num  0 13.8 11 14.3 12.9 ...
 $ deltat         : num  0 1.018 0.725 1.052 0.934 ...
 $ ratenew        : num  0 13.8 11 14.3 12.9 ...
 $ cumET          : num  0 14 22 37 49 69 86 109 119 150 ...
 $ cumETnew       : num  0 14 22 37 49 69 86 109 119 150 ...
 $ waterbef       : num  8 42 49 41 44 36 40 33 45 25 ...
 $ wateraft       : num  56 57 56 56 56 57 56 55 56 55 ...
 $ waternew       : num  56 57 56 56 56 57 56 55 56 55 ...
 $ cumECnew       : num  38.4 49.6 55.3 67.3 77 ...
 $ Lagdate        : chr  NA "2022-10-31" "2022-11-01" "2022-11-02" ...
 - attr(*, ".internal.selfref")=<externalptr> 

The problem seems to be related to a new functionality of Rstudio, showing the content of a column in data.table. The error comes when the first element of a column is NA, as it apparently checks that. 

This is in line with the error message, but should of course not happening while showing a preview during the editing of code.

**Comment by Gangrelino** [comment]
I am having the same issue. It is not an issue with underscores in column names, I believe. I removed the underscores and the issue persisted. 
I initially thought that the problem came from NA values in a given column that you are trying to get autocomplete after the dollar sign (like in  @mikecrobp  df example above). But on my end, that does not happen on columns where I have NAs.

A traceback() call on the error from @mikecrobp example leads to this: 
```
#Error in if (nchar(current) > nchars) { : 
#missing value where TRUE/FALSE needed
traceback()
#3: .rs.getHelpColumn(what, from, envir)
#2: impl()
#1: .rs.rpc.get_help("col2", "df", 27L)

```

**Comment by proshano** [comment]
same issue

**Comment by BrendonChau** [comment]
> Probably from here.
> 
> https://github.com/rstudio/rstudio/blob/b2d7353fdf45be8168d19db2de3dea9b6f84bc40/src/cpp/session/modules/SessionHelp.R#L465-L490

Error seems to be upstream in `pillar`, `pillar_glimpse` doesn't have a method for handling POSIX date types so it returns `NA` when it should return `"NA"`. May be an issue for other types, but I haven't checked carefully. I inserted this ugly fix after line 467 to get rid of the annoying error on my machine.

```R
formatted[is.na(formatted)] <- "NA"
```

**Comment by daxiagithub** [comment]
I'm glad to see that this issue has been reported as it has been bugging me ever since I upgraded to the latest Rstudio (Version: 2023.03.0+386, Windows 11, running R 4.2.0).  The problem comes and goes, but it always happens when I type "$" after a data.frame (or alike) object to autofill a variable name.  Not sure about the "_" hypothesis mentioned before.   

Looking forward to the solutions.  Thanks!

**Comment by mikecrobp** [comment]
> Had the same problem with autocorrect. I solved it by updating R to 2023-03-15 (4.2.3) ucrt windows

I (original poster) tried this. Still got error.

**Comment by mikecrobp** [comment]
> A reproducible example would indeed be helpful.

I posted one later on in the thread

**Comment by envanloo** [comment]
It happens when you make a data.frame or data.table in which in one the columns NAs occur. And for sure when the first row contains NA.
With me it happened with a POSIXct column that was shifted one row down, causing an <NA> in the first row of that column.

Reproducible example:

StartDateTime <- as.POSIXct("2023-01-01",origin="1970-01-01")
DateTime10 <- seq(StartDateTime,StartDateTime+10)
test.df <- as.data.table(cbind(c(1:11),DateTime10,shift(DateTime10)))
test.df <- cbind(test.df,test.df$V3)
test.df$V2 <- as.POSIXct(test.df$V2)

Now, in the console type "test.df$". If you have autofill on, you will get a dropdown menu for the columns. If not, type [TAB] button to get the dropdown menu. If you know walk down with the cursor to the column V3, no problems. Go one down to the column name of the POSIXct column and you get the error.

**Comment by daxiagithub** [comment]
> It happens when you make a data.frame or data.table in which in one the columns NAs occur. And for sure when the first row contains NA. With me it happened with a POSIXct column that was shifted one row down, causing an in the first row of that column.
> 
> Reproducible example:
> 
> StartDateTime <- as.POSIXct("2023-01-01",origin="1970-01-01") DateTime10 <- seq(StartDateTime,StartDateTime+10) test.df <- as.data.table(cbind(c(1:11),DateTime10,shift(DateTime10))) test.df <- cbind(test.df,test.df$V3) test.df$V2 <- as.POSIXct(test.df$V2)
> 
> Now, in the console type "test.df$". If you have autofill on, you will get a dropdown menu for the columns. If not, type [TAB] button to get the dropdown menu. If you now walk down with the cursor to the column V3, no problems. Go one down to the column name of the POSIXct column and you get the error.

I can confirm this observation.  In one of my own data.frame objects, two POSIXct columns have NAs in the first row and both of them have this issue.  BTW, fixed the code a little bit so it can run out of box:

```
StartDateTime <- as.POSIXct("2023-01-01",origin="1970-01-01")
DateTime10 <- seq(StartDateTime,StartDateTime+10, length.out=11)
test.df <- as.data.table(cbind(c(1:11),DateTime10,shift(DateTime10)))
test.df <- cbind(test.df,test.df$V3)
test.df$V2 <- as.POSIXct(test.df$V2, origin = "1960-01-01")
```

**Comment by mikecrobp** [comment]
> > Probably from here.
> > https://github.com/rstudio/rstudio/blob/b2d7353fdf45be8168d19db2de3dea9b6f84bc40/src/cpp/session/modules/SessionHelp.R#L465-L490
> 
> Error seems to be upstream in `pillar`, `format_glimpse` doesn't have a method for handling POSIX date types so it returns `NA` when it should return `"NA"`. May be an issue for other types, but I haven't checked carefully. I inserted this ugly fix after line 467 to get rid of the annoying error on my machine.
> 
> ```r
> formatted[is.na(formatted)] <- "NA"
> ```

What do I need to do in order to use your fix? Do I need to download total RStudio source? Or is it there already on machine from my vanilla installation?

**Comment by jeffvroom** [comment]
That looks like a reasonable fix to me.  You can patch this yourself by editing the R module file.  On linux systems, it will be at this path:

`/usr/lib/rstudio-server/R/modules/SessionHelp.R` 

That change get picked up when the session restarts (and overwritten if you reinstall).

**Comment by mikecrobp** [comment]
> ```r
> formatted[is.na(formatted)] <- "NA"
> ```

Thank you.
<drive>:\Program Files\RStudio\resources\app\R\modules on Windows

**Comment by ocelhay** [comment]
What would be the path to `SessionHelp.R` on macOS?

**Comment by michaellevy** [comment]
@BrendonChau 's fix worked for me too: Adding `formatted[is.na(formatted)] <- "NA"` as line 468 in `SessionHelp.R`.

On MacOS, that file is by default in: `/Applications/RStudio.app/Contents/Resources/app/R/modules`

Like others, I ran into the problem using `$` to access a date column with underscores in the name and NA entries. R v4.3.0, RStudio Version 2023.03.0+386 (2023.03.0+386).

**Comment by ellessenne** [comment]
> @BrendonChau 's fix worked for me too: Adding `formatted[is.na(formatted)] <- "NA"` as line 468 in `SessionHelp.R`.
> 
> On MacOS, that file is by default in: `/Applications/RStudio.app/Contents/Resources/app/R/modules`
> 
> Like others, I ran into the problem using `$` to access a date column with underscores in the name and NA entries. R v4.3.0, RStudio Version 2023.03.0+386 (2023.03.0+386).

This fix worked for me as well, on:
- arm64 R 4.3.0
- macOS Ventura 13.3.1 (a)
- RStudio 2023.03.0, Build 386

**Comment by jonvanausdeln** [comment]
@sharon-wang , using your example, I also can not get it to reproduce.
Windows 11, 2023.03.0+386

**Comment by kevinushey** [comment]
Reproducing this issue maybe depend on whether the `pillar` R package is installed and loaded.

Do you have any better luck with this script?

```
library(data.table)
library(pillar)

StartDateTime <- as.POSIXct("2023-01-01",origin="1970-01-01")
DateTime10 <- seq(StartDateTime,StartDateTime+10, length.out=11)
test.df <- as.data.table(cbind(c(1:11),DateTime10,shift(DateTime10)))
test.df <- cbind(test.df,test.df$V3)
test.df$V2 <- as.POSIXct(test.df$V2, origin = "1960-01-01")

# try typing 'test.df$' and see what autocomplete produces
```

**Comment by sharon-wang** [comment]
@kevinushey spot on, thank you! I can now reproduce on MacOS 13.1 and Windows 11 with 2023.03.0+386 and in my dev environment when I disable the help column error suppression. Fix incoming soon :)

**Comment by jonvanausdeln** [comment]
Verified on Desktop 2023.05.0-daily+366
Windows 11

I was able to reproduce on Cherry Blossom, and then verify it works with latest daily Mountain-Hydrangea build.

**Comment by bknakker** [comment]
same error for me. For the specific case I'm now encountering, I have a tibble named `something_data` with one nested tibble column Vars, and the dialog comes upon typing the last character of the string 'something_data$V'  in the console.
RStudio 2023.03.1+446 "Cherry Blossom" Release (6e31ffc3ef2a1f81d377eeccab71ddc11cfbd29e, 2023-05-09)

**Comment by jonvanausdeln** [comment]
@bknakker , this should be fixed in our next release (Mountain Hydrangea). You can try the daily build if you'd like. 

https://dailies.rstudio.com/rstudio/mountain-hydrangea/ (This is for testing purposes only)

We are expecting to release in the next few weeks.

**Comment by hongdavid94** [comment]
Fantastic! Thank you @BrendonChau solution worked

**Comment by xgirouxb** [comment]
Confirmed that @BrendonChau's fix also works on linux, where default rstudio `SessionHelp.R` directory is at `/lib/rstudio/resources/app/R/modules`.

- R version 4.3.0 (2023-04-21)
- Platform: x86_64-pc-linux-gnu (64-bit)
- Running under: Linux Mint 21.1
- RStudio Cherry Blossom 2023.03.0 Build 386

**Comment by DaveEvenden** [comment]
In case it's relevant to others with the same config (a roll-back due to other issues), @BrendonChau's fix also works on R version 4.2.3 and RStudio build 446 2023.03.1, with Win 10.

I added the new line after line 467 per the change above & saved the updated SessionHelp.R script to... \Program Files\RStudio\resources\app\R\modules

**Comment by singularity24601** [comment]
Issue is still present in rstudio-2023.03.3-547-arm64.deb. Have now applied @BrendonChau's fix.

**Comment by intGRen** [comment]
Hi all, I am on Windows 11, using R version 4.5.2, and Rstudio version 2026.1.1.403 "Apple Blossom" and am getting a similar error. 

It consistently appears when I try to write anything on the console. But it will also happen when I am just coding in the regular pane

<img width="493" height="170" alt="Image" src="https://github.com/user-attachments/assets/5eb45f20-2bce-4955-b578-fe39cfe6dc28" />
