### ISSUE TITLE
RStudio Dataframe Column Navigation Limited to 50 Columns after Updating

### ISSUE THREAD

**Issue by BradyHorton** [rstudio/rstudio#13220]
### System details

    RStudio Edition :  Desktop
    RStudio Version :  RStudio 2023.06.0+421 "Mountain Hydrangea" 
    OS Version      :  Windows 11
    R Version       :  4.3

### Steps to reproduce the problem

Create a data frame with more than 50 columns and attempt to navigate with the "Cols" arrows after viewing the data frame.

### Describe the problem in detail

I am currently working on a project and analyzing a dataset that has more than 50 columns of data, and after updating to the latest version of RStudio today, I can't seem to navigate to the later columns in the data frame. I should also note that before updating this morning, the column navigation worked just fine. In other words, when viewing the data, the column navigation arrows do not seem to be working. Here is what I am referring to in RStudio:

![image](https://github.com/rstudio/rstudio/assets/135742177/099991eb-317c-410f-a0da-6af2d40354e3)

I also tried manually updating the column numbers, but even though it displayed the correct numbers, only the lower bound was updated and I could not access the data in the later columns (Beyond column 50).

### Describe the behavior you expected

Before updating to the latest version of RStudio today, the column navigation worked like normal.  I simply expected the column navigation to work as it previously has in older versions of RStudio.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by lbenz730** [comment]
I had the same issue with Rstudio version RStudio 2023.06.0+421 on R4.1.0 and had to revert to previous version of the IDE because of this issue.

**Comment by ronblum** [comment]
Thank you for raising this! Confirmed that this is failing in
- RStudio Desktop 2023.06.0+421 on MacOS .13.4 
- RStudio Desktop 2023.06.0+421 on Ubuntu 22.04
- RStudio Server 2023.06.0+421 on Ubuntu 20.04 via Chrome on MacOS 13.4

Triage: We should patch this.

**Comment by JMSteinberg** [comment]
Same behavior (clicking on arrows does not show additional columns) on windows 10

**Comment by rcarden71** [comment]
I am having same issue.

**Comment by DanyangDai** [comment]
Same issue here. 
Version 2023.06.0+421 (2023.06.0+421) on macOS 13.4. Tried the temporary fix by @Kamina from https://community.rstudio.com/t/viewer-does-not-show-more-than-50-columns/167955/10 using 
`rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L)`.

**Comment by chienc1** [comment]
Unfortunately, it still doesn't work for me with Version 2023.08.0-daily+53 (2023.08.0-daily+53) for MacOS 11+ nor the proposed 
rstudioapi::writeRStudioPreference("data_viewer_max_columns", 1000L) on MacOS 12.6.7.
The work around just gives me a blank viewer if I try to jump to the last available column since it doesn't exist in my DF and then freezes, as @kamina warns.

**Comment by jonvanausdeln** [comment]
@chienc1 , the daily you mentioned doesn't contain the initial fix.  2023.08.0-daily+55 is the first build that has the fix for column navigation.

**Comment by chienc1** [comment]
> @chienc1 , the daily you mentioned doesn't contain the initial fix. 2023.08.0-daily+55 is the first build that has the fix for column navigation.

Great! Thanks @jonvanausdeln! I just saw people saying it was working for them, but didn't know the exact build.

**Comment by jonvanausdeln** [comment]
Verified on [2023.08.0-daily+59](https://dailies.rstudio.com/version/2023.08.0-daily+59)
Windows 11, Ubuntu22

Initial bug is fixed as is the subsequent sorting issue. Also tested filtering and search, which behaved as expected.

**Comment by AliVaughan** [comment]
This is still happening for me

**Comment by jonvanausdeln** [comment]
@AliVaughan , which version are you using?

**Comment by AliVaughan** [comment]
Version 2023.06.0+421 (2023.06.0+421)

**Comment by jonvanausdeln** [comment]
@AliVaughan , okay. We have a fix undergoing testing right now and should be in a patch soon.

If you want to try it out now, there is a daily build, but note Daily builds are for testing only and not recommended for production use. https://dailies.rstudio.com/rstudio/desert-sunflower/

**Comment by sjackson1236** [comment]
using 2023.06.1+438 fixed this issue for me on MacOS Ventura 13.4.1

**Comment by samvgon** [comment]
MacOS 11+ 2023.06.1+438 fixed this for me as well on MBP M1 on Ventura 13.4.1

**Comment by mcket747econ** [comment]
This is still happening for me on Windows 11. I am using 2023.06.0+421.

**Comment by sharon-wang** [comment]
@mcket747econ There's a possible fix available in the [Daily Builds](https://dailies.rstudio.com/rstudio/mountain-hydrangea/), starting with build 2023.06.1+438.

If the fix works for you, please write a comment here letting us know! Please note that daily builds are for testing purposes only and they are not meant for production. This fix is still undergoing testing and should be available in a patch soon.

**Comment by ronblum** [comment]
@docal555 The fix restores the original behavior, which is as you describe. Can you file a new ticket, about changing the display of the last set of columns?

**Comment by docal555** [comment]
Not sure if I understand "fix restores the original behavior". To me it is logical that if you skip from 50 that it continues with 51 and not with 40 or "last column - 50". But that´s just me... Anyway, thanks for looking into it. Too much work opening a new ticket

**Comment by ronblum** [comment]
I mean that showing the last 50 columns, instead of starting at 51, is how the data viewer horizontal pagination has been since it was first introduced in 1.2.5042. Since the fix for the 50-limit bug didn't introduce this change, it's a different issue.

**Comment by BMacedoUSP-RP** [comment]
But it is just a "visual bug", right? I mean, my whole dataframe is still there just not thoroughly visible. 
It doesn't interfere on my analysis, does it?
I'm still experiencing this issue on 2023.06.0+421 (Windows 10)

**Comment by jonvanausdeln** [comment]
@BMacedoUSP-RP correct, it doesn't affect your data at all.
As mentioned in the OP< we do have a fix that will be available in an upcoming patch.
If you would like to try it, it's available in the [Daily Builds ](https://dailies.rstudio.com/rstudio/mountain-hydrangea/), starting with build 2023.06.1+438. If the fix works for you, please write a comment here letting us know! Please note that daily builds are for testing purposes only and they are not meant for production. This fix is still undergoing testing.

**Comment by docal555** [comment]
To me it is a partial fix. But maybe it is just me, who does not understand that if I have a dataframe with 89 columns and I skip to column 51 that it "sets-back" to column 40. It is like counting to 89, once you reach 51, you have to continue with 40. Higher maths?

**Comment by Weixxxxy** [comment]
I used the RStudio Desktop for MacOS 11+ (universal) ([2023.06.1+524](https://dailies.rstudio.com/version/2023.06.1+524) in [Daily Builds], the bug was fixed and it could show the full columns now.

**Comment by jonvanausdeln** [comment]
_**❗❗ There is a fix for this issue❗❗**_
The latest release now contains the fix for this issue. Please download the latest version(RStudio 2023.06.1+524) from https://posit.co/,
---
