### ISSUE TITLE
Error Message formatting bug

### ISSUE THREAD

**Issue by t-kalinowski** [rstudio/rstudio#16365]
### System details

RStudio 2025.08.0+356 "Cucumberleaf Sunflower" Release (f2fe0322610f6198e841b9c125a4b3cb0bc7551d, 2025-08-09) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2025.08.0+356 Chrome/138.0.7204.185 Electron/37.2.6 Safari/537.36, Quarto 1.7.33 (/Applications/quarto/bin/quarto)

### Steps to reproduce the problem

Output some error message to `stderr()`, then signal an error in R.

### Describe the problem in detail

If output is sent to stderr, there is a chance it gets hidden from the user if it happens right before an error is signaled

### Describe the behavior you expected

```r
not_fun_fun <- function() {
  writeLines("Error: A useful error message", stderr())
  flush.console()
  flush(stderr())
  stop("Less useful error message")
}

not_fun_fun()
```

<img width="835" height="278" alt="Image" src="https://github.com/user-attachments/assets/d649e410-c00f-48c9-bb30-571e4315ef3b" />

- [X] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by kevinushey** [comment]
This sounds similar to https://github.com/rstudio/rstudio/issues/16337. In particular, the issue indeed effects output to stderr that includes `Error:` as a prefix, as we were (over-opportunistically) trying to mark those as error outputs, without actually checking if a real, uncaught R error had occurred.

To wit -- I believe this is fixed in the daily builds for the next release, currently available from https://dailies.rstudio.com/rstudio/apple-blossom/.

**Comment by t-kalinowski** [comment]
Hmm, I tried the latest daily and still see the same behavior 

<img width="787" height="306" alt="Image" src="https://github.com/user-attachments/assets/5149f89c-7935-4b09-a29a-9b3fdde30e91" />

RStudio 2025.09.0+373 "Cucumberleaf Sunflower" Release (241e6d954d69ece7dc4e618b235c6191c1c15eff, 2025-09-04) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2025.09.0+373 Chrome/138.0.7204.185 Electron/37.2.6 Safari/537.36, Quarto 1.7.34 (/Applications/quarto/bin/quarto)

**Comment by kevinushey** [comment]
You need to try the Apple Blossom daily builds (this isn't fixed in the Cucumber Sunflower builds). https://dailies.rstudio.com/rstudio/apple-blossom/

**Comment by t-kalinowski** [comment]
Thanks! I see the fix now 😃!

RStudio 2025.11.0-daily+105 "Apple Blossom" Daily (22d14989f57e125435a86cde0c92e28af3284f9b, 2025-09-08) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) RStudio/2025.11.0-daily+105 Chrome/138.0.7204.235 Electron/37.3.1 Safari/537.36, Quarto 1.7.34 (/Applications/quarto/bin/quarto)

<img width="621" height="351" alt="Image" src="https://github.com/user-attachments/assets/cb889aad-8743-4f17-905e-0235e0654f64" />

**Comment by kevinushey** [comment]
Phew! Thanks for confirming.
