### ISSUE TITLE
Blurry font in Windows

### ISSUE THREAD

**Issue by foonwong** [rstudio/rstudio#2784]
### System details

    RStudio Edition : Desktop
    RStudio Version :   1.1.442
    OS Version      : Windows 10 1803
    R Version       : 3.3.2

### Problem
Some fonts are extremely thin and blurry. 

I am not sure if this is an rstudio problem. However, the same fonts looks bolder and smoother in notepad++ and windows notepad. 

ClearType is calibrated and used.

Hasklig (left), Monoid (right)
![hasklig left -monoid right](https://user-images.githubusercontent.com/20807463/40029592-3f8829ba-579a-11e8-8239-8b779870ae23.PNG)

Hasklig in rstudio (left), Hasklig in Notepad ++ (right)
![hasklig](https://user-images.githubusercontent.com/20807463/40029604-548e2544-579a-11e8-9f00-d033ef2fada6.PNG)

Firacode
![firacode](https://user-images.githubusercontent.com/20807463/40029634-7885af12-579a-11e8-90f0-46a46f31929d.PNG)

**Comment by jmcphers** [comment]
This issue should be resolved in the daily builds of RStudio, which use a new rendering engine. Can you give one of them a try and let us know if it improves things for you?

https://dailies.rstudio.com/

**Comment by yhwu** [comment]
Version 1.3.316 still renders blurry fonts. Have to go back to 1.1.

**Comment by vh-d** [comment]
RStudio Desktop on Ubuntu 18.04:

* current stable (1.2.5033) - fonts are **ok**
* current preview (1.3.919) - **blurry**
* current daily (1.4.70) - **blurry**

I wonder why so few people report this problem. Is it a non-issue on HiDPI screens? Is there any internal settings switch for font antialiasing in RStudio?

**Comment by Ludsfer** [comment]
Few people report this problem because they don't update their versions a frequently as some of us do...  
Latest RStudio Desktop builds
Windows 10
current daily (1.4.1065) - **blurry**

**Comment by edaustin** [comment]
I'm still getting this, it's as if the scaling isn't correct, just looks blurry under Win 10 (FHD Screen on a ThinkPad P50) and almost unusable.

Strangely, it's fine on the same machine under VMWare Workstation running a Virtual Ubuntu 20 machine (as it is on my Ubuntu Desktop PC).

So, is a Windows 10 issue for me, fine in Ubuntu...
