### ISSUE TITLE
R process freezes in Windows after running Shiny app over and over

### ISSUE THREAD

**Issue by wch** [rstudio/rstudio#2958]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.710
    OS Version      : Windows 10
    R Version       : 3.5.0

### Steps to reproduce the problem

First, install dev versions of the later and httpuv packages. (This is to avoid crashes due to bugs in those packages.) Then install Shiny (1.1.0) from CRAN.

```R
devtools::install_github("r-lib/later")
devtools::install_github("rstudio/httpuv")
install.packages("shiny")
```

When I run a shiny app, RStudio will sometimes freeze. This happens in maybe 1 out of 10 runs.

Start the app, then, after it loads, close the viewer window. Then do it again and again:

```R
shiny::runExample("01_hello")
```

When it freezes, the viewer window is sometimes empty, or sometimes has a partially-loaded application. But even when it's frozen, I'm able to visit the Shiny app with a web browser, which  means that the R process is still going.

This happens in Windows, but I haven't seen it happen on my Mac. I also haven't been able to reproduce this problem in 1.1.453.

**Comment by ronblum** [comment]
@wch I still can't reproduce it using VMWare, but I saw it in person on your laptop, so I believe you.

**Comment by kevinushey** [comment]
I'm not able to reproduce on my Windows desktop machine, either. Any chance this is an issue that was fixed in the latest CRAN release of `httpuv`?

```
> devtools::session_info()
Session info ----------------------------------------------------------------------------
 setting  value                                      
 version  R version 3.5.0 Patched (2018-06-19 r74919)
 system   x86_64, mingw32                            
 ui       RStudio (1.2.758)                          
 language (EN)                                       
 collate  English_United States.1252                 
 tz       America/Los_Angeles                        
 date     2018-06-20                                 

Packages --------------------------------------------------------------------------------
 package   * version date       source        
 base      * 3.5.0   2018-06-20 local         
 compiler    3.5.0   2018-06-20 local         
 datasets  * 3.5.0   2018-06-20 local         
 devtools    1.13.5  2018-02-18 CRAN (R 3.5.0)
 digest      0.6.15  2018-01-28 CRAN (R 3.5.0)
 graphics  * 3.5.0   2018-06-20 local         
 grDevices * 3.5.0   2018-06-20 local         
 htmltools   0.3.6   2017-04-28 CRAN (R 3.5.0)
 httpuv      1.4.4.1 2018-06-18 CRAN (R 3.5.0)
 jsonlite    1.5     2017-06-01 CRAN (R 3.5.0)
 later       0.7.3   2018-06-08 CRAN (R 3.5.0)
 magrittr    1.5     2014-11-22 CRAN (R 3.5.0)
 memoise     1.1.0   2017-04-21 CRAN (R 3.5.0)
 methods   * 3.5.0   2018-06-20 local         
 mime        0.5     2016-07-07 CRAN (R 3.5.0)
 promises    1.0.1   2018-04-13 CRAN (R 3.5.0)
 R6          2.2.2   2017-06-17 CRAN (R 3.5.0)
 Rcpp        0.12.17 2018-05-18 CRAN (R 3.5.0)
 rlang       0.2.1   2018-05-30 CRAN (R 3.5.0)
 shiny     * 1.1.0   2018-05-17 CRAN (R 3.5.0)
 stats     * 3.5.0   2018-06-20 local         
 tools       3.5.0   2018-06-20 local         
 utils     * 3.5.0   2018-06-20 local         
 withr       2.1.2   2018-03-15 CRAN (R 3.5.0)
 xtable      1.8-2   2016-02-05 CRAN (R 3.5.0)
```

**Comment by wch** [comment]
I updated to the latest CRAN version of httpuv and was able to reproduce the crash. This was with RStudio 1.2.710.

I tried with 1.2.758 and 1.2.761, but those versions of RStudio crashed immediately on startup for me. When I installed 1.2.710 again, RStudio ran OK, and again running a Shiny application crashed about 1 in 10 times.

The fact that the newer versions of RStudio wouldn't even start for me might indicate that something else is weird with my system. It is a new laptop that is only a few weeks old, though, and has very little stuff installed on it.

```
> sessioninfo::session_info()
─ Session info ──────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.5.0 (2018-04-23)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 tz       America/Chicago             
 date     2018-06-20                  

─ Packages ──────────────────────────────────────────────────────────────────
 package     * version date       source        
 clisymbols    1.2.0   2017-05-21 CRAN (R 3.5.0)
 digest        0.6.15  2018-01-28 CRAN (R 3.5.0)
 htmltools     0.3.6   2017-04-28 CRAN (R 3.5.0)
 httpuv        1.4.4.1 2018-06-18 CRAN (R 3.5.0)
 jsonlite      1.5     2017-06-01 CRAN (R 3.5.0)
 later         0.7.3   2018-06-08 CRAN (R 3.5.0)
 magrittr      1.5     2014-11-22 CRAN (R 3.5.0)
 mime          0.5     2016-07-07 CRAN (R 3.5.0)
 promises      1.0.1   2018-04-13 CRAN (R 3.5.0)
 R6            2.2.2   2017-06-17 CRAN (R 3.5.0)
 Rcpp          0.12.17 2018-05-18 CRAN (R 3.5.0)
 rlang         0.2.1   2018-05-30 CRAN (R 3.5.0)
 sessioninfo   1.0.0   2017-06-21 CRAN (R 3.5.0)
 shiny       * 1.1.0   2018-05-17 CRAN (R 3.5.0)
 withr         2.1.2   2018-03-15 CRAN (R 3.5.0)
 xtable        1.8-2   2016-02-05 CRAN (R 3.5.0)
```

**Comment by kevinushey** [comment]
Any chance that nuking your R library and reinstalling everything form scratch makes a difference?

**Comment by wch** [comment]
I deleted my personal R library and deleted R (which includes the system library), then I reinstalled all packages.

With RStudio 1.2.710, it still crashes occasionally when I run a Shiny app.

With RStudio 1.2.770, RStudio crashes immediately on startup. I tried both installing it and running it without installing (by downloading the .zip file). When I say it crashes immediately, I mean immediately: the window opens (and is gray), and a dialog comes up right away saying "RStudio has stopped working."
