### ISSUE TITLE
F2, when pressed on a function, should open the source code directly used to create the function

### ISSUE THREAD

**Issue by hzarkoob** [rstudio/rstudio#3561]
When a function object is available in the Environment, and F2 is pressed on it, it is expected that the source code from which the function is created opens up. However, this does not always happen. Instead, F2 may open another file with a similar name that does physically exist, but is not the file that has been used to create the function in question.

Because of frequent use of functions, I think it would be a particularly helpful feature to have.

PS1. It seems like the issue is related to the fact that F2 searches for the function name and tries to open it from the first place it finds it. This is an absolutely fine UNLESS the function is already loaded in the environment. Is that case, the user is most probably interested in the source code that was used to create the function. So I think F2 should open up that specific source code.

PS2. If View() is applied to a function, it does exactly what was mentioned above, i.e., it opens the the source code that was used to create the function. So it seems like all we need to do is to have F2 replicate the role of View(), which happily would also apply to the application of View() to data frames.

    RStudio Edition : Server
    RStudio Version : 1.1.423
    OS Version      : Linux
    R Version       : 3.5.1

Thank you for looking into this!

**Comment by ronblum** [comment]
@hzarkoob Thank you for the suggestion. We'll review and consider it as we work on future releases of RStudio.

**Comment by hzarkoob** [comment]
Thank you for this :)

**Comment by hzarkoob** [comment]
Hi, any updates on this? Thank you!

**Comment by ronblum** [comment]
@hzarkoob No update yet. However, in the meantime, I believe I miscategorized this: it's a bug, not an enhancement. Do you agree? Also, I can't reproduce this on RStudio Server or RStudio Desktop. Do have any sense of which file is getting chosen—for example, the first alphabetically by name, most recent file, etc.?

**Comment by hzarkoob** [comment]
@ronblum Thank you Ron. I agree. It would be more accurate to mark it as a bug. 

It seems to me like the path from which the file is selected is chosen according to alphabetic order.

PS. As mentioned above, a good point is that the function View() already works perfectly fine both on dataframes and functions. I am not sure about the implementation details, but maybe the problem can be simply addressed by having the shortcut F2 mimic the function of the View() function regardless of whether it is pressed on a dataframe or a function.

**Comment by ronblum** [comment]
@hzarkoob Great, thanks for confirming, and for the suggestion of a solution. I'm changing this to a bug.

**Comment by hzarkoob** [comment]
@ronblum Thank you for this and the great RStudio product.

**Comment by Raoul-Kima** [comment]
This bug still exists in RStudio Version 2022.07.1.

Some more info:
1. f2 prioritizes function definitions in currently opened r-scripts (from the project directory) over those in (unopened) files in the project directory.
2. But r-code in a newly created r-script that was not yet saved to a file is not prioritized.
3. if a function was sourced from a file outside the project directory, and no function definition with that name exists in the project directory, then RStudio doesn't open the file, but instead opens a viewer showing only the definition of that one function. (If a file with a definition exists in the project directory, that file is opened)
4. if a function was sourced from a file outside the project directory, and that file is opened in r-studio, it behaves the same as if the file wasn't opened. (both when a definition exists in the working directory and when it doesnt)
