### ISSUE TITLE
Display error with non-English IME (e.g. Chinese)

### ISSUE THREAD

**Issue by leovan** [rstudio/rstudio#4079]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1194
    OS Version      : macOS  10.14.2
    R Version       : 3.5.1

### Steps to reproduce the problem

Switch to a non-English IME on macOS, e.g. Pinyin - Simplified, type any Pinyin of Chinese in console and editor.

### Describe the problem in detail

When typing non-English (e.g. Chinese) characters with IME (Input Method Editor), characters are not displayed properly (see attached images) with RStudio 1.2.1194. It works fine with RStudio 1.1.463.

In console (characters are "ceshizhongwen", corresponding Chinese: 测试中文, but only got the last 3 characters "wen"), In editor (characters are "ceshizhongwen", but only got the first characters "c"):

![chinese-ime-bugs](https://user-images.githubusercontent.com/3234653/50369673-5e9c0680-05d4-11e9-97fb-fe80fbed0e2d.jpg)

After pressing the space button, I can get correct Chinese words in both console and editor. This issue bothers me especially when I typed the wrong Pinyin of Chinese, and need delete the wrong characters to get the right Chinese words. But if I press the delete button too fast, without the appropriate display, I have no idea how many characters left and I have to delete all characters.

**Comment by ronblum** [comment]
@leovan Thank you for reporting this issue. We'll review it as we work on ongoing development of RStudio.

**Comment by kevinushey** [comment]
Not for v1.3 (will hopefully be fixed with the Ace update)

**Comment by leovan** [comment]
Hi, @kevinushey and @ronblum , it's been almost one year with this issue. Since input with IME is really a basic operation for non-English users (such as Chinese), really appreciate if we can fix this issue in higher priority. Also if you know the reason for this problem, would you like to give some advice to fix it, I can try myself if possible.

**Comment by leovan** [comment]
I test with daily build v1.3.580, now it works fine in inside terminal, I believe it benefits from update of xterm.js. Yet, in editor it still has the problem. This time, it gets NONE character with IME (with v1.2.x it gets only the first character).

**Comment by kevinushey** [comment]
Interestingly, this issue specifically affects R scripts, but not other programming modes. For example, if I open a plain text file, then the IME input displays as expected in the editor.

**Comment by kevinushey** [comment]
This is even weirder for me, actually. IME input works and displays as expected in all files, _except_ for an untitled file called Untitled1. I have absolutely no idea why this might be the case.

**Comment by kevinushey** [comment]
Okay, I'm observing the following weirdness:

1. For the first-opened document in an IDE session, the IME preview text is not shown.
2. For subsequently-opened documents, IME preview is displayed without issue.
3. If one then closes the first-opened document, and then opens a new document, that most-recently-opened document will exhibit the same IME issue.

Very, very odd!

**Comment by leovan** [comment]
Hi @kevinushey , thanks so much for your reply. I test with v1.3.599 on macOS 10.15 in following cases (all test Pinyin are "ceshizhongwen", coresponding Chinese is "测试中文"):

Case 1: Open a new RStudio (with OR without an editor opened initially), input with IME in console.
Result 1: IME works **NOT** as expected for first time inputs. But the with some charactoers (no matter English or Chinese), IME works as expected.
![case-1-1](https://user-images.githubusercontent.com/3234653/68724408-5686f400-05f6-11ea-942c-0b070f6e6ef9.png)
![case-1-2](https://user-images.githubusercontent.com/3234653/68724410-5850b780-05f6-11ea-939c-2087eeaedaa0.png)
![case-1-3](https://user-images.githubusercontent.com/3234653/68724413-5ab31180-05f6-11ea-9de4-2efa56de2802.png)

Case 2: Open a new RStudio with an editor opened initially (an Untitled1 R script, or any other type script, or saved documents), or a new document (in any type of script), also close the first opened document and keep the following opend documents, input with IME in editor.
Result 2: IME works as expected in sames situations in case 1 (**with a board acound charactors**).
![Screen Shot 2019-11-13 at 09 17 21](https://user-images.githubusercontent.com/3234653/68724479-9b128f80-05f6-11ea-874e-63106d9e5f01.png)
![Screen Shot 2019-11-13 at 09 20 43](https://user-images.githubusercontent.com/3234653/68724808-81257c80-05f7-11ea-9582-fc91025111a0.png)
![Screen Shot 2019-11-13 at 09 21 12](https://user-images.githubusercontent.com/3234653/68724813-84b90380-05f7-11ea-99f6-9e1cc4e0351b.png)

Really weird for gettting diffrerent results from last time tested with v1.3.580 on macOS.

I am not famliar with the dev framework of RStudio, I believe the main panel of RStudio is a html page displayed with QtWebEngine. I noticed we use Qt 5.12.5 and the version of Chrome was 69.x. The lastest stable version of Chrome is 78.x, will this (some bugs for Chrome with IME in old version) be the reason for this problem?

**Comment by leovan** [comment]
Also I think the problem was fixed little by little, since now only in one situation the IME works NOT as expected. But I don't know why it's different from last time tested with v1.3.580 on macOS. Is there any update codes specific for this issue, or just other updates get such results?

**Comment by kevinushey** [comment]
I get the feeling that fixing this will ultimately require either an OS update (perhaps Apple will do something to fix it behind the scenes) or a Qt + WebEngine update.

**Comment by jmcphers** [comment]
Neither are likely for 1.3.

**Comment by gtritchie** [comment]
I tested the described scenario in Electron build 2022.06.0-daily+248 on macOS 12.3, using the Pinyin-Simplified IME.

The expected characters were previewed and inserted in both the Console and the Editor. I tried multiple editor tabs, both R files and RMD files.

**Comment by xiajunwen1007** [comment]
The problem still exists in the Studio 2022.06.0-daily+327 (2022.06.0-daily+327) on macOS 12.3.
<img width="893" alt="image" src="https://user-images.githubusercontent.com/49160447/166084000-d400b25e-0284-4eb5-bb22-5bd73bd033c8.png">

The reproduced method:
1. Open rstudio with no existing files
2. Create a new untitled file
3. Type with Pinyin-Simplified IME

**Comment by kevinushey** [comment]
Can you please try testing with one of the Electron builds available at https://dailies.rstudio.com/?

**Comment by xiajunwen1007** [comment]
Yes, I'm happy to test. The problem don't disappear.
<img width="896" alt="image" src="https://user-images.githubusercontent.com/49160447/166084408-72c9ea1c-63f8-4309-b41b-52a9b149cb51.png">
The version of the RStudio is 2022.06.0 Build 343.
<img width="764" alt="image" src="https://user-images.githubusercontent.com/49160447/166084434-3a31795e-e913-4a5c-a09b-d6d8a8426c2d.png">

**Comment by kevinushey** [comment]
Sorry, you still installed the Qt build. Please try the latest Electron builds. The latest macOS builds are here:

https://dailies.rstudio.com/rstudio/spotted-wakerobin/electron/macos/

**Comment by xiajunwen1007** [comment]
OK, I tested the Electron builds and the issue still exists.
<img width="972" alt="image" src="https://user-images.githubusercontent.com/49160447/166342632-5f5301cf-ba51-4c46-ae48-cacdd908be27.png">
<img width="284" alt="image" src="https://user-images.githubusercontent.com/49160447/166342638-d92fc8ea-d881-4609-aafa-c08f960f75a9.png">

**Comment by gtritchie** [comment]
Sorry to hear this is still happening for you with the Electron build. I will reactivate this issue so we can take another look. When I tried it it seemed like it was fixed, but I may have misunderstood what to look for.

**Comment by gglee4ai** [comment]
There is a similar problem in Korean language. 
In the terminal, the IME boxes appear overlapping of characters. 
In the source editor, the boxes are not visible at all or sometimes the IME boxes are also overlapped like terminal mode. However, switching between the two is arbitrary.
There is no problem in visual mode. This problem is the same for electron version. 
The information of my PC are Mac M1MAX, QT: RStudio 2022.07.2+576 and Electron: Version 2022.07.3+582 (2022.07.3+582).
<img width="1264" alt="Screen Shot 2022-12-06 at 10 41 06 AM" src="https://user-images.githubusercontent.com/48779488/205789280-c27cd102-7e1d-4173-a5c8-94eac60532af.png">
