### ISSUE TITLE
Python chunch fails to run in windows desktop version with error: This application failed to start because it could not find or load the Qt platform plugin "windows" in "".

### ISSUE THREAD

**Issue by andresrcs** [rstudio/rstudio#4182]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1242
    OS Version      : Windows 10 Pro
    R Version       : 3.5.2

### Steps to reproduce the problem
Run this simple python chunk
````
---
title: "R Notebook"
output: html_notebook
---

```{python}
import pandas
```
````
### Describe the problem in detail
When I try to run a python chunk y get this error and my R session crashes.
![image](https://user-images.githubusercontent.com/14981085/51420579-5a2a2580-1b61-11e9-940e-920edfd5e562.png)

I have python installed through Anaconda 3 distribution, this used to work normally some daily builds ago, but I can't specify which one.

**Comment by kevinushey** [comment]
This should work with the development builds of `reticulate`. What is the output of `packageVersion("reticulate")` on your machine?

Does:

    devtools::install_github("rstudio/reticulate")

make a difference?

**Comment by andresrcs** [comment]
My `reticulate` version was 1.10, I have installed the development version and now works normally, thanks.

**Comment by ronblum** [comment]
On MacOS, the current version of `reticulate` ((1.10) causes a new RStudio instance to start to open, but remains bouncing and doing nothing. It requires quitting the app to keep going. The development build works, though.

I'm leaving this marked as an open issue, to retest once a new production version `reticulate` is published.

**Comment by icalandra** [comment]
I still have the same problem, as described by @andresrcs 

Windows 10 Pro, version 1803, OS build 17134.829
Anaconda 3 with Python 3.7.3
R 3.6.0
RStudio 1.2.1335
reticulate 1.12.0.9003

The problem seems to be only with Python plotting commands, other Python calculations seem fine.
I searched quite a lot online but I cannot understand any of the answers.

Thanks for any help!

**Comment by kevinushey** [comment]
@icalandra I suspect your issue is different. @andresrcs's issue involved RStudio crashing even when `pandas` was imported; yours is explicitly around plotting.

A reproducible example would be helpful.

**Comment by icalandra** [comment]
Thanks for the answer.

Indeed, my problem seems to be different, although the error is the same, which is why I thought the problem was similar.

I can plot Python commands from a Python script or directly writing in the console. But I cannot knit it:

---
title: "Untitled"
author: "xx"
date: "28/06/2019"
output: html_document
---

```{python}
import numpy as np
from matplotlib import pyplot as plt
xs = np.linspace(0,10)
ys = 3*xs +1
```

```{python}
fig, ax = plt.subplots()
ax.plot(xs,ys)
plt.show()
```

The first chunk runs fine and exports to HTML correctly (if I remove the second chunk), but the second crashes and I get the error shown in the original thread. Any idea?
Thanks,
Ivan

**Comment by icalandra** [comment]
Oh, I didn't expect the markdown part would be interpreted; I of course inserted ```{python}...``` around the chunks.

**Comment by kevinushey** [comment]
You can use backtick code 'fences' to avoid that sort of rendering, e.g.

```````
`````
# This is some Markdown

```{r}
print("Hello!")
```
`````
```````

I've edited your post to do that (hope that's okay).

**Comment by icalandra** [comment]
@kevinushey thanks for the tip!
The real problem still remains though...

**Comment by icalandra** [comment]
Any pointer anyone?
Thanks again!

**Comment by ronblum** [comment]
@icalandra The fix for both issues—covered by #5051—is slated for the upcoming update to 1.2.

**Comment by icalandra** [comment]
Great, thanks!

**Comment by ronblum** [comment]
@icalandra You're welcome! When the next preview is available, this should be working. If you're still running into the issue then, please let us know!

**Comment by icalandra** [comment]
I will!

**Comment by ronblum** [comment]
@icalandra Have you had a chance to try out the latest preview and see if it works?

**Comment by icalandra** [comment]
Euu... how do I install it? 
I currently have reticulate 1.13.0.9000 installed and I still have the issue

**Comment by ronblum** [comment]
@icalandra I'm sorry—I meant the [RStudio preview](https://www.rstudio.com/products/rstudio/download/preview/) at https://www.rstudio.com/products/rstudio/download/preview/. (Note that Preview builds are intended for testing purposes only.)

**Comment by ronblum** [comment]
The original issue is confirmed, using the current production version of `reticulate`, 1.13. I'm leaving this in "verifying" state, for the moment, because of the second issue.

**Comment by icalandra** [comment]
I can confirm that the problem persists with the latest RStudio preview (1.2.1565).

**Comment by ronblum** [comment]
I get a different error, even though the plot is rendered. In the R Markdown pane, the log ends with
> Fatal Python error: PyEval_RestoreThread: NULL tstate

The error modal below appears, as well. There's no problem if the file only contains the first chunk when knitted, or if the chunks are running individually. So even though we're getting different results, it seems like your original issue is still there, so I'm reopening.

**Comment by linderd** [comment]
I found a walkaround to solve the problem with the help from this [stackoverflow](https://stackoverflow.com/questions/49953620/importing-matplotlib-pyplot-in-rstudio-using-reticulate)
The solution was to add this to lines to the R code:
`py_run_string("import os as os")`
`py_run_string("os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Path_to_your_anaconda/anaconda3/Library/plugins/platforms'")`

Hope I could help you

**Comment by icalandra** [comment]
The code chuncks do run, but I get an error at the end and no HTML file as a result. Did I do something wrong?

Here is my code:
``````
---
title: "Untitled"
author: "xx"
date: "28/06/2019"
output: html_document
---

```{r}
library(reticulate)
py_run_string("import os as os")
py_run_string("os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/.../Anaconda3/Library/plugins/platforms'")
```

```{python}
import numpy as np
from matplotlib import pyplot as plt
xs = np.linspace(0,10)
ys = 3*xs +1
```

```{python}
fig, ax = plt.subplots()
ax.plot(xs,ys)
plt.show()
```
``````

And here is the error:
output file: test2.knit.md
"C:/Program Files/RStudio/bin/pandoc/pandoc" +RTS -K512m -RTS test2.utf8.md --to html4 --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output test2.html --email-obfuscation none --self-contained --standalone --section-divs --template "C:\Users\calandra\Documents\R\win-library\3.6\rmarkdown\rmd\h\default.html" --no-highlight --variable highlightjs=1 --variable "theme:bootstrap" --include-in-header "C:\Users\calandra\AppData\Local\Temp\Rtmp2bgJSj\rmarkdown-str29544bf85fbb.html" --mathjax --variable "mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML" 
Access violation in generated code when executing data at 0x7a48e89
 Attempting to reconstruct a stack trace...
   Frame	Code address
 * 0x57adaf0	0x7a48e89
 * 0x57adaf8	0x1d40101 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x1940101
 * 0x57adb00	0xd70
 * 0x57adb08	0x22e
 * 0x57adb10	0x58d4510
 * 0x57adb18	0x5
 * 0x57adb20	0x73020d0000
 * 0x57adb28	0x22e
 * 0x57adb30	0xc68
 * 0x57adb38	0x7aa5c09
 * 0x57adb40	0x7a08491
 * 0x57adb48	0x20
 * 0x57adb50	0x61
 * 0x57adb58	0x7af6fa1
 * 0x57adb60	0x7af80e8
 * 0x57adb68	0x7af81a8
 * 0x57adb70	0x7af8180
 * 0x57adb78	0x7aed6d1
 * 0x57adb80	0x1
 * 0x57adb88	0x57
 * 0x57adb90	0x7a794d0
 * 0x57adb98	0x4f
 * 0x57adba0	0x7a2df08
 * 0x57adba8	0x7ad8481
 * 0x57adbb0	0x4b61721 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x4761721
 * 0x57adbb8	0x49f2be2 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f2be2
 * 0x57adbc0	0x4b616f1 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x47616f1
 * 0x57adbc8	0x423fbc8 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3e3fbc8
 * 0x57adbd0	0x7ac0540
 * 0x57adbd8	0x7ac0509
 * 0x57adbe0	0x49f0aba C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f0aba
 * 0x57adbe8	0x49f0aba C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f0aba
 * 0x57adbf0	0x423fba8 C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x3e3fba8
 * 0x57adbf8	0x49f0aba C:\PROGRA~1\RStudio\bin\pandoc\pandoc.exe+0x45f0aba
 * 0x57adc00	0x7ac0680
   ... (maximum recursion depth reached.)
Error: pandoc document conversion failed with error 11
Execution halted

**Comment by icalandra** [comment]
I just tried again with the latest preview release of RStudio (1.2.1572) and @linderd solution works, without errors:

``````
---
title: "Untitled"
author: "xx"
date: "28/06/2019"
output: html_document
---

```{r}
library(reticulate)
py_run_string("import os as os")
py_run_string("os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/calandra/Anaconda3/Library/plugins/platforms'")
```

```{python}
import numpy as np
from matplotlib import pyplot as plt
xs = np.linspace(0,10)
ys = 3*xs +1
```

```{python}
fig, ax = plt.subplots()
ax.plot(xs,ys)
plt.show()
```
``````

So it seems to all work correctly now, thank you all for your help!

**Comment by icalandra** [comment]
Thanks!

**Comment by ichsan2895** [comment]
Hello, I have the same problems with Rstudio 1.1. It will be error if I use matplotlib/seaborn graph to "output : html_document".

I will look for preview version of RStudio 1.2

**Comment by ichsan2895** [comment]
> I just tried again with the latest preview release of RStudio (1.2.1572) and @linderd solution works, without errors:
> 
> ```
> ---
> title: "Untitled"
> author: "xx"
> date: "28/06/2019"
> output: html_document
> ---
> 
> ```{r}
> library(reticulate)
> py_run_string("import os as os")
> py_run_string("os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/calandra/Anaconda3/Library/plugins/platforms'")
> ```
> 
> ```{python}
> import numpy as np
> from matplotlib import pyplot as plt
> xs = np.linspace(0,10)
> ys = 3*xs +1
> ```
> 
> ```{python}
> fig, ax = plt.subplots()
> ax.plot(xs,ys)
> plt.show()
> ```
> ```
> 
> So it seems to all work correctly now, thank you all for your help!

Wow, this really sollve my problems. Hopefully It will be fixed without write this specific commands `py_run_string("os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/calandra/Anaconda3/Library/plugins/platforms'")`

**Comment by matanmazor** [comment]
I'm still getting the same error :(
Running on Windows, tried with my local python installation and using the reticulate's miniconda option.

**Comment by ivan-paleo** [comment]
This runs without problem on my system:

``````
---
title: "Untitled"
author: "xx"
date: "28/06/2019"
output: html_document
---

```{r}
library(reticulate)
```

```{python}
import numpy as np
from matplotlib import pyplot as plt
xs = np.linspace(0,10)
ys = 3*xs +1
```

```{python}
fig, ax = plt.subplots()
ax.plot(xs,ys)
plt.show()
```
``````

`sessionInfo()`
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)
Matrix products: default
locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):
 [1] digest_0.6.25    crayon_1.3.4     dplyr_1.0.1      R6_2.4.1         lifecycle_0.2.0  magrittr_1.5    
 [7] evaluate_0.14    pillar_1.4.6     rlang_0.4.7      vctrs_0.3.2      generics_0.0.2   ellipsis_0.3.1  
[13] rmarkdown_2.3    tools_4.0.2      glue_1.4.1       purrr_0.3.4      tinytex_0.25     rsconnect_0.8.16
[19] yaml_2.2.1       xfun_0.16        compiler_4.0.2   pkgconfig_2.0.3  htmltools_0.5.0  knitr_1.29      
[25] tidyselect_1.1.0 tibble_3.0.3    

`RStudio.Version()$version`
[1] ‘1.3.1073’

**Comment by ivan-paleo** [comment]
> 
> 
> Wanted to mention that I was getting this error but `environ` solution worked for me. I'm on Windows with `reticulate 1.16` and RStudio 1.4.733.

@alexpghayes How did you get RStudio 1.4.733? RStudio [Preview](https://rstudio.com/products/rstudio/download/preview/) is v1.3.1075-1. Is it a typo? Could it be that you are using an older version then?

**Comment by kevinushey** [comment]
@ivan-paleo: v1.4 daily builds are available from https://dailies.rstudio.com. These builds are primarily intended for testing, and may be unstable.

**Comment by estevaobotelho** [comment]
> I just tried again with the latest preview release of RStudio (1.2.1572) and @linderd solution works, without errors:
> 
> ```
> ---
> title: "Untitled"
> author: "xx"
> date: "28/06/2019"
> output: html_document
> ---
> 
> ```{r}
> library(reticulate)
> py_run_string("import os as os")
> py_run_string("os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = 'C:/Users/calandra/Anaconda3/Library/plugins/platforms'")
> ```
> 
> ```{python}
> import numpy as np
> from matplotlib import pyplot as plt
> xs = np.linspace(0,10)
> ys = 3*xs +1
> ```
> 
> ```{python}
> fig, ax = plt.subplots()
> ax.plot(xs,ys)
> plt.show()
> ```
> ```
> 
> So it seems to all work correctly now, thank you all for your help!

Thank you so much all of you! It helps me too.

**Comment by ivan-paleo** [comment]
> 
> 
> @ivan-paleo: v1.4 daily builds are available from https://dailies.rstudio.com. These builds are primarily intended for testing, and may be unstable.

Thank you for the info and the link!
