### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by slowkow** [rstudio/rstudio#4520]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.3.74
    OS Version      : macOS 10.13.6
    R Version       : 3.5.1

### Steps to reproduce the problem

Open RStudio.app

### Describe the problem in detail

The RStudio app fails to launch:

![image](https://user-images.githubusercontent.com/209714/55041183-53f17300-5002-11e9-842e-167d389db448.png)

After I click "Reload", it starts running as expected.

### Extra details

Here are some fragments of the diagnostics report that might be helpful.

```
Log file: rdesktop.log
--------------------------------------------------

23 Jul 2018 11:42:32 [rdesktop] ERROR system error 60 (Operation timed out); OCCURRED AT: rstudio::core::Error rstudio::core::waitWithTimeout(const boost::function<WaitResult ()> &, int, int, int) /Users/vagrant/workspace/IDE/macos/src/cpp/core/WaitUtils.cpp:63; LOGGED FROM: rstudio::core::Error rstudio::desktop::SessionLauncher::launchNextSession(bool) /Users/vagrant/workspace/IDE/macos/src/cpp/desktop/DesktopSessionLauncher.cpp:331
25 Jul 2018 23:42:33 [rdesktop] ERROR Main window closed unexpectedly; LOGGED FROM: auto rstudio::desktop::MainWindow::closeEvent(QCloseEvent *)::(anonymous class)::operator()(QVariant) const /Users/vagrant/workspace/IDE/macos/src/cpp/desktop/DesktopMainWindow.cpp:270
19 Sep 2018 16:26:15 [rdesktop] ERROR Main window closed unexpectedly; LOGGED FROM: auto rstudio::desktop::MainWindow::closeEvent(QCloseEvent *)::(anonymous class)::operator()(QVariant) const /Users/vagrant/workspace/IDE/macos/src/cpp/desktop/DesktopMainWindow.cpp:270
11 Mar 2019 15:26:50 [rdesktop] ERROR Main window closed unexpectedly; LOGGED FROM: auto rstudio::desktop::MainWindow::closeEvent(QCloseEvent *)::(anonymous class)::operator()(QVariant) const /Users/vagrant/workspace/IDE/macos/src/cpp/desktop/DesktopMainWindow.cpp:281
27 Mar 2019 00:06:59 [rdesktop] ERROR Main window closed unexpectedly; LOGGED FROM: auto rstudio::desktop::MainWindow::closeEvent(QCloseEvent *)::(anonymous class)::operator()(QVariant) const /Users/vagrant/workspace/IDE/macos-v1.3/src/cpp/desktop/DesktopMainWindow.cpp:281

```

```
Log file: rsession-slowikow.log
--------------------------------------------------

05 Apr 2018 19:29:54 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
06 Apr 2018 23:47:19 [rsession-slowikow] ERROR system error 41 (Protocol wrong type for socket) [request-uri=/graphics/b39b1086-1926-4d77-a3c1-14c40155d2e1.png]; OCCURRED AT: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:93; LOGGED FROM: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:98
25 Apr 2018 18:40:39 [rsession-slowikow] ERROR system error 41 (Protocol wrong type for socket) [request-uri=/graphics/b497169e-43cf-466a-a829-46d32beeed56.png]; OCCURRED AT: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:93; LOGGED FROM: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:98
25 Apr 2018 18:40:42 [rsession-slowikow] ERROR system error 41 (Protocol wrong type for socket) [request-uri=/graphics/6221f5d1-e4a4-482c-9e22-a99d2fadc525.png]; OCCURRED AT: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:93; LOGGED FROM: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:98
01 May 2018 19:21:46 [rsession-slowikow] ERROR system error 41 (Protocol wrong type for socket) [request-uri=/help/library/ggrepel/doc/ggrepel.html]; OCCURRED AT: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:93; LOGGED FROM: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:98
11 May 2018 17:56:02 [rsession-slowikow] ERROR r error 4 (R code execution error) [errormsg=Error in library(packageName, lib.loc = lib, character.only = TRUE) : |||  ‘ggrepel’ is not a valid installed package|||, context=Error restoring session data (loading package ggrepel)]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::(anonymous namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) /Users/vagrant/workspace/IDE/macos/src/cpp/r/RExec.cpp:162; LOGGED FROM: void rstudio::r::session::search_path::(anonymous namespace)::loadPackage(const std::string &, const std::string &) /Users/vagrant/workspace/IDE/macos/src/cpp/r/session/RSearchPath.cpp:198
11 May 2018 18:02:51 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
11 May 2018 18:16:27 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
11 May 2018 18:19:20 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
13 May 2018 23:15:42 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
10 Jun 2018 19:08:48 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
10 Jun 2018 19:41:41 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
11 Jun 2018 17:37:16 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
11 Jun 2018 18:02:12 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
11 Jun 2018 18:03:37 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
11 Jun 2018 18:07:04 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
11 Jun 2018 18:12:09 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
11 Jun 2018 18:13:09 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
11 Jun 2018 20:38:10 [rsession-slowikow] ERROR system error 41 (Protocol wrong type for socket) [request-uri=/graphics/cb47511a-4f09-4d3b-a1f5-07041cf74b2b.png]; OCCURRED AT: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:93; LOGGED FROM: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:98
11 Jun 2018 20:39:13 [rsession-slowikow] ERROR system error 41 (Protocol wrong type for socket) [request-uri=/graphics/ebe2a940-9974-4a12-af28-b127a75b0299.png]; OCCURRED AT: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:93; LOGGED FROM: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:98
12 Jun 2018 16:24:19 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
19 Jul 2018 16:00:01 [rsession-slowikow] ERROR system error 41 (Protocol wrong type for socket) [request-uri=/rmd_output/4/index_files/resizing.mp4]; OCCURRED AT: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:93; LOGGED FROM: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:98
23 Jul 2018 00:04:24 [rsession-slowikow] ERROR r error 4 (R code execution error) [errormsg=Error in match.arg(units, c("in", "px", "cm", "mm")) : |||  reached elapsed time limit|||]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::evaluateString(const std::string &, SEXP *, sexp::Protect *) /Users/vagrant/workspace/IDE/macos/src/cpp/r/RExec.cpp:305; LOGGED FROM: pDevDesc rstudio::r::session::graphics::handler::shadow::(anonymous namespace)::shadowDevDesc(pDevDesc) /Users/vagrant/workspace/IDE/macos/src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp:149
28 Aug 2018 15:09:53 [rsession-slowikow] ERROR system error 22 (Invalid argument); OCCURRED AT: rstudio::core::Error rstudio::core::system::(anonymous namespace)::readPipe(int, std::string *, bool *) /Users/vagrant/workspace/IDE/macos/src/cpp/core/system/PosixChildProcess.cpp:129; LOGGED FROM: void rstudio::core::system::AsyncChildProcess::reportError(const rstudio::core::Error &) /Users/vagrant/workspace/IDE/macos/src/cpp/core/include/core/system/ChildProcess.hpp:239
30 Aug 2018 17:18:30 [rsession-slowikow] ERROR system error 41 (Protocol wrong type for socket) [request-uri=/graphics/cdbfd6e8-3bd4-441e-9c65-900c073f0ff9.png]; OCCURRED AT: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:93; LOGGED FROM: virtual void rstudio::session::HttpConnectionImpl<rstudio_boost::asio::ip::tcp>::sendResponse(const core::http::Response &) [ProtocolType = rstudio_boost::asio::ip::tcp] /Users/vagrant/workspace/IDE/macos/src/cpp/session/http/SessionHttpConnectionImpl.hpp:98
03 Sep 2018 16:01:48 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionClientEventService.cpp:351
08 Oct 2018 13:48:47 [rsession-slowikow] ERROR r error 4 (R code execution error) [errormsg=there is no package called ‘rsconnect’]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::executeSafely(boost::function<void ()>) /Users/vagrant/workspace/IDE/macos/src/cpp/r/RExec.cpp:224; LOGGED FROM: void rstudio::session::(anonymous namespace)::processEvents() /Users/vagrant/workspace/IDE/macos/src/cpp/session/SessionHttpMethods.cpp:98
30 Nov 2018 01:18:39 [rsession-slowikow] ERROR r error 4 (R code execution error) [errormsg=Error in loadNamespace(name) : there is no package called 'xml2'|||]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::<anonymous namespace>::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::<anonymous>::EvalType) /Users/rstudio/rstudio/src/cpp/r/RExec.cpp:159; LOGGED FROM: rstudio::core::Error rstudio::session::modules::r_addins::<anonymous namespace>::executeRAddin(const json::JsonRpcRequest &, json::JsonRpcResponse *) /Users/rstudio/rstudio/src/cpp/session/modules/SessionRAddins.cpp:467
19 Dec 2018 01:32:31 [rsession-slowikow] ERROR r error 4 (R code execution error) [errormsg=Error in loadNamespace(name) : there is no package called ‘blogdown’|||]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::<anonymous namespace>::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::<anonymous>::EvalType) /Users/rstudio/rstudio/src/cpp/r/RExec.cpp:159; LOGGED FROM: void rstudio::session::<anonymous namespace>::initWebsiteOutputDir() /Users/rstudio/rstudio/src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp:95
21 Dec 2018 00:05:09 [rsession-slowikow] ERROR r error 7 (Unexpected data type); OCCURRED AT: rstudio::core::Error rstudio::r::sexp::extract(SEXP, std::vector<std::string> *) /Users/rstudio/rstudio/src/cpp/r/RSexp.cpp:827; LOGGED FROM: json::Array rstudio::session::projects::websiteOutputFormatsJson() /Users/rstudio/rstudio/src/cpp/session/projects/SessionProjects.cpp:891
23 Dec 2018 20:23:17 [rsession-slowikow] ERROR jsonrpc error 9 (Parameter type mismatch) [description=no such parameter 'ordinal']; OCCURRED AT: core::Error rstudio::core::json::readObject(const json::Object &, const std::string &, T *) [T = int] /Users/vagrant/workspace/IDE/macos/src/cpp/core/include/core/json/JsonRpc.hpp:540; LOGGED FROM: void rstudio::session::modules::r_addins::(anonymous namespace)::AddinRegistry::loadFromFile(const core::FilePath &) /Users/vagrant/workspace/IDE/macos/src/cpp/session/modules/SessionRAddins.cpp:180
01 Jan 2019 19:21:03 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/rstudio/rstudio/src/cpp/session/SessionClientEventService.cpp:351
01 Jan 2019 19:22:42 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/rstudio/rstudio/src/cpp/session/SessionClientEventService.cpp:351
02 Jan 2019 01:11:33 [rsession-slowikow] ERROR r error 4 (R code execution error) [errormsg=no applicable method for 'depth' applied to an object of class "NULL"]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::executeSafely(boost::function<void ()>) /Users/rstudio/rstudio/src/cpp/r/RExec.cpp:212; LOGGED FROM: void rstudio::session::<anonymous namespace>::processEvents() /Users/rstudio/rstudio/src/cpp/session/SessionHttpMethods.cpp:91
02 Jan 2019 01:11:37 [rsession-slowikow] ERROR r error 4 (R code execution error) [errormsg=no applicable method for 'depth' applied to an object of class "NULL"]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::executeSafely(boost::function<void ()>) /Users/rstudio/rstudio/src/cpp/r/RExec.cpp:212; LOGGED FROM: void rstudio::session::<anonymous namespace>::processEvents() /Users/rstudio/rstudio/src/cpp/session/SessionHttpMethods.cpp:91
03 Jan 2019 03:01:57 [rsession-slowikow] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: void rstudio::session::ClientEventService::run() /Users/rstudio/rstudio/src/cpp/session/SessionClientEventService.cpp:351
06 Feb 2019 15:28:47 [rsession-slowikow] ERROR r error 4 (R code execution error) [errormsg=Error in x[[n]] : |||  attempt to select less than one element in integerOneIndex|||]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::<anonymous namespace>::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, sexp::Protect *, rstudio::r::exec::<anonymous>::EvalType) /Users/rstudio/rstudio/src/cpp/r/RExec.cpp:159; LOGGED FROM: rstudio::core::Error rstudio::session::modules::r_addins::<anonymous namespace>::executeRAddin(const json::JsonRpcRequest &, json::JsonRpcResponse *) /Users/rstudio/rstudio/src/cpp/session/modules/SessionRAddins.cpp:467
11 Feb 2019 22:25:31 [rsession-slowikow] ERROR system error 22 (Invalid argument); OCCURRED AT: rstudio::core::Error rstudio::core::system::<anonymous namespace>::readPipe(int, std::string *, bool *) /Users/rstudio/rstudio/src/cpp/core/system/PosixChildProcess.cpp:124; LOGGED FROM: void rstudio::core::system::AsyncChildProcess::reportError(const rstudio::core::Error &) /Users/rstudio/rstudio/src/cpp/core/system/ChildProcess.hpp:239
19 Feb 2019 19:07:27 [rsession-slowikow] ERROR jsonrpc error 9 (Parameter type mismatch) [description=no such parameter 'ordinal']; OCCURRED AT: core::Error rstudio::core::json::readObject(const json::Object &, const std::string &, T *) [T = int] /Users/vagrant/workspace/IDE/macos/src/cpp/core/include/core/json/JsonRpc.hpp:540; LOGGED FROM: void rstudio::session::modules::r_addins::(anonymous namespace)::AddinRegistry::loadFromFile(const core::FilePath &) /Users/vagrant/workspace/IDE/macos/src/cpp/session/modules/SessionRAddins.cpp:180

```

**Comment by jmcphers** [comment]
This should be resolved in our most recent 1.3 build for macOS, 1.3.92 -- let us know if it isn't!

**Comment by gtsambos** [comment]
Hi @jmcphers, unfortunately I don't think this has fixed the issue -- I've tried a few of the most recent daily builds on Mac OS X 10.14.5 and the same bug happens -- (but unlike for the OP, pressing "reload" doesn't fix the issue for me)

**Comment by dsmmcken** [comment]
"This site can’t be reached 127.0.0.1 refused to connect."

This is a misleading error message. As it seems it can also mean R isn't installed or working correctly on your machine.

I thought the fault was with rstudio, but my R installation had somehow become broken. Re-installing R fixed it for me. If you've install R with brew, a `brew upgrade r` or `brew reinstall r` may fix it for you.

**Comment by kevinushey** [comment]
We're tracking improvements to our startup diagnostics / error reporting here: https://github.com/rstudio/rstudio/issues/2097
