### ISSUE TITLE
Rstudio 1.2.1335 libssl version error in Debian 10 (wants 1.0.2 instead 1.1)

### ISSUE THREAD

**Issue by eutanatos** [rstudio/rstudio#4670]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335-amd64 for Debian 9+
    OS Version      : Debian 10 Buster
    R Version       : 

### Steps to reproduce the problem
>wget https://download1.rstudio.org/desktop/debian9/x86_64/rstudio-1.2.1335-amd64.deb
>dpkg -i rstudio-1.2.1335-amd64.deb
>rstudio
rstudio: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory

### Describe the problem in detail
Rstudio wants libssl1.0.2 but Debian 10 have libssl1.1:
>apt search libssl
libssl1.0.0/now 1.0.2l-1~bpo8+1 amd64 [installed, local]
  Secure Sockets Layer toolkit - shared libraries
libssl1.1/testing,now 1.1.1b-1 amd64 [installed]
  Secure Sockets Layer toolkit - shared libraries

### Describe the behavior you expected
real support of Debian 10 by RStudio Desktop.

### Update. Temporary ways to solve problem:
- use Ubuntu Bionic build, it's linked against libssl.so.1.1 (tnx for this solution to @jmcphers, @dongzhuoer);
- revert back to 1.0.153 (https://support.rstudio.com/hc/en-us/articles/206569407-Older-Versions-of-RStudio) and it works fine if you don't need any of the new features (tnx for this solution to @quoctran98);
- install libssl1.0.2 from the stretch repository (it's a little tricky and i don't like this way, but you should know. Tnx for this solution to @david-cortes).

**Comment by david-cortes** [comment]
You have to install `libssl1.0.2`, which is a separate package (`apt-get install libssl1.0.2`)

**Comment by eutanatos** [comment]
> You have to install `libssl1.0.2`, which is a separate package (`apt-get install libssl1.0.2`)

Debian 10 Buster does not have libssl1.0.2, only libssl1.1

**Comment by quoctran98** [comment]
I have this same problem but you can revert back to 1.0.153 (https://support.rstudio.com/hc/en-us/articles/206569407-Older-Versions-of-RStudio) and it works fine if you don't need any of the new features.

**Comment by david-cortes** [comment]
> > You have to install `libssl1.0.2`, which is a separate package (`apt-get install libssl1.0.2`)
> 
> Debian 10 Buster does not have libssl1.0.2, only libssl1.1

You're right, it's not in buster anymore, but in the meantime you can still install it from the stretch repository.

**Comment by dongzhuoer** [comment]
Thanks to @jmcphers, you may try the Ubuntu Bionic build, https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.2.1335-amd64.deb

**Comment by jmcphers** [comment]
You'll probably want the desktop version, though.

https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.1335-amd64.deb

**Comment by eutanatos** [comment]
> You'll probably want the desktop version, though.
> 
> https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.2.1335-amd64.deb

Thank you! Better to have support in .deb for Debian, but this solution works. I hope the problem goes away in the next version Rstudio.

**Comment by paulmenzel** [comment]
Please reopen, as the issue is still present. Could updated packages please be provided. The download page explicitly says Debian 9*+*, which includes Debian 10 in my understanding. If not, it’s confusing, and should be updated.

**Comment by ronblum** [comment]
@paulmenzel The names have now been updated on the download pages—see #5037—so this is resolved.

@kevinushey Is there anything left to do, or can we close the issue?

**Comment by paulmenzel** [comment]
@ronblum, thank you for the update. The issue is indeed resolved from my point of view.

**Comment by ronblum** [comment]
@paulmenzel In that case, excellent—thank you!

**Comment by kevinushey** [comment]
Thanks! I think we can close this now -- the issue was scoped specifically to updating the download links for Debian 10, so I think we should be good to go here.

**Comment by melissaboiko** [comment]
Still getting this on Debian 10, rstudio-1.3.1056-amd64.deb (marked as for "Debian 10" at [the webpage](https://rstudio.com/products/rstudio/download/#download)), as of Jul 2020.

```bash
$ ldd /usr/bin/rstudio|grep -i libssl
libssl.so.1.0.2 => not found
$ rstudio
rstudio: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory

```

**Comment by ronblum** [comment]
@melissaboiko This looks like the error that occurs when the Debian 9 version is installed on Debian 10. Can you double check and use this package https://download1.rstudio.org/desktop/bionic/amd64/rstudio-1.3.1056-amd64.deb ? It's the same file name but the Ubuntu 18/Debian 10 version, with a different signature.

**Comment by melissaboiko** [comment]
It worked! I must have made a mistake and gotten the older package somehow. Sorry for the trouble.

**Comment by ronblum** [comment]
@melissaboiko No problem! I make the same mistake. :) I'm glad you're all set!

**Comment by andrie** [comment]
I still get this same problem when attempting to install the latest **daily** on Debian 10.

https://dailies.rstudio.com/rstudioserver/oss/bionic/x86_64/

```
wget https://s3.amazonaws.com/rstudio-ide-build/server/debian9/x86_64/rstudio-server-1.4.673-amd64.deb
sudo dpkg -i rstudio-server-1.4.673-amd64.deb
```

And I get:

```
/usr/lib/rstudio-server/bin/rserver: error while loading shared libraries: libssl.so.1.0.2: cannot open shared object file: No such file or directory
```

I'm using the Dockerfile at https://github.com/rocker-org/rstudio-daily

**Comment by ronblum** [comment]
@andrie Try this one. The "Debian 9+" build is actually just for Debian 9, and "Ubuntu 18+" is for both Ubuntu 18+ and Debian 10. I'll put in a request to update the page, similar to what's on the current and preview downloads.

https://s3.amazonaws.com/rstudio-ide-build/server/bionic/amd64/rstudio-server-1.4.673-amd64.deb
