### ISSUE TITLE
Spell checker should not run on strings in R chunks

### ISSUE THREAD

**Issue by philturk** [rstudio/rstudio#5009]
While I know there is at least one workaround, it would be nice if the ABC + check button contained an option to ignore R code chunks when checking the spelling of an R Markdown document.  Or perhaps this feature could be set as a global option in Spelling.  

Many thanks for listening.

**Comment by ronblum** [comment]
@philturk Thank you for the suggestion. Can you provide a reproducible example of the current behavior? Also, what version/environment are you currently using? Thanks! 

    RStudio Edition : 
    RStudio Version : 
    OS Version      : 
    R Version       :

**Comment by philturk** [comment]
Hi Ron, I am suggesting that RStudio add the capability of skipping R code chunks when spell checking an R Markdown document.  Sorry I wasn't clear.

**Comment by ronblum** [comment]
@philturk Oh, your description was clear—no problem there. I haven't been able to reproduce the problem, though—the spellcheck is skipping R code chunks when I try. I'm wondering if you could provide a reproducible example—by pasting the Rmd code here or attaching a file—plus the RStudio version environment you're working with, so that I can try and reproduce the issue under the same conditions as you. Thanks!

**Comment by philturk** [comment]
Hi Ron:

Pasted below is an extremely simple example that demonstrates the behavior.  I am using RStudio Desktop, Version 1.2.1511, on a Mac, with R version 3.5.3 ("Great Truth").

Best,

-- Phil
---
title: "Untitled"
output: html_document
---

Whn I do a spell check, using 'ABC + check', this sentence is correctly flagged (because I deliberately added a typo), but then the three colors for the line in the R code chunk are also checked when I don't want them to be.  

```{r}
colors_to_try <- c("#003da7", "#ee7624", "#003da7")
```

**Comment by ronblum** [comment]
@philturk Thank you! This is very helpful. The spellchecker is treating anything within quotes as text to check. Here's a simple example, based on what you provided:

````
---
title: "When v. Whn"
output: html_document
---

when
whn

```{r}
double_quotes <- c("#whn") # Checked
double_quotes <- c("whn") # Checked
single_quotes <- c('whn') # Checked
withno_quotes <- c(whn) # Ignored
whn # Ignored
```

````

Anything in the R chunk that's within quotes is checked, outside is ignored. The question is, when is the value a word to be checked and when is it a non-word—such as a color hex code—to be ignored? As currently implemented, it's the former. 

I'm marking this as an enhancement, to see if there's a way to distinguish between the two cases, or provide the ability to choose the behavior. Thank you for raising the issue and providing the code!

By the way,  I was able to get at your code by getting the raw text of the comment, which was easy enough. But to include code with backticks and not have it rendered, include the code within an additional backtick. For example, 
````
```{r}
````
is wrapped by four backticks, e.g.
`````
````
```{r}
````
`````
And I did this by wrapping the code in five backticks.

**Comment by philturk** [comment]
Many thanks, Ron, for your due diligence.  Have a good weekend.

**Comment by jmcphers** [comment]
We should fix this; it's pretty annoying for R Markdown documents.

**Comment by jmcphers** [comment]
Example from a doc I'm working on:

![image](https://user-images.githubusercontent.com/470418/68236693-83b22180-ffba-11e9-85dc-fc6df0b01001.png)

**Comment by dfalty** [comment]
Verified fixed 1.3.867

**Comment by lnalborczyk** [comment]
I still have a similar issue with Quarto (.qmd) documents in RStudio v2022.07.1, where comments within code chunks are checked by the spell checker. Can this be configured somehow? When working on Quarto slides (for instance), I'd like the spell checker to only check textual content on the slides, not comments in the code chunks.

**Comment by ronblum** [comment]
@lnalborczyk Can you open a separate issue for adding this option, is an enhancement request? It would be useful to separate it out from this ticket, since it's a little different from this enhancement. Thanks!

**Comment by lnalborczyk** [comment]
Sure!

**Comment by ronblum** [comment]
Thanks!
