### ISSUE TITLE
Indefinite redirect with RStudio Server 1.3.1056 (Water Lily) on Databricks

### ISSUE THREAD

**Issue by falaki** [rstudio/rstudio#7319]
I switched to 1.3.1056 (Water Lily) for Ubuntu Bionic  

1. Running rstudio-server verify-installation runs with no issues. 
2. When trying to log in, user gets into a seemingly infinite redirection loop. 

We see the following error on `rstudio-server status`:  
```
ERROR session hadabend; LOGGED FROM: rstudio::core::Error {anonymous}::rInit(const rstudio::r::session::RInitInfo&) src/cpp/session/SessionMain.cpp
```

### System details

    RStudio Edition : Server
    RStudio Version : 1.3.1056 (Water Lily)
    OS Version      : Ubuntu 18.04, x86_64-pc-linux-gnu (64-bit)
    R Version       : 3.6.3 (2020-02-29) 

### Steps to reproduce the problem
Install Preview version on Databricks and try to login based on [these instructions](https://docs.databricks.com/spark/latest/sparkr/rstudio.html#use-rstudio-server-open-source).

```
  apt-get update
  apt-get install -y gdebi-core
  cd /tmp
  # You can find new releases at https://rstudio.com/products/rstudio/download-server/debian-ubuntu/.
  wget https://s3.amazonaws.com/rstudio-ide-build/server/bionic/amd64/rstudio-server-1.3.1056-amd64.deb -O rstudio-server.deb
  sudo gdebi -n rstudio-server.deb
```

### Describe the problem in detail
As above.

### Describe the behavior you expected
When installing v1.2.5033  users can log in with no issues.

- [x] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ ] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jmcphers** [comment]
`hadabend` (had abnormal end) suggests a crash. Are you seeing crash notifications in the UI? Have you tried turning on diagnostics for more detailed logs?

https://docs.rstudio.com/ide/server-pro/r-sessions.html#diagnosing-session-launch-failures

**Comment by falaki** [comment]
> `hadabend` (had abnormal end) suggests a crash. Are you seeing crash notifications in the UI? Have you tried turning on diagnostics for more detailed logs?
> 
> https://docs.rstudio.com/ide/server-pro/r-sessions.html#diagnosing-session-launch-failures

This is for RStudio server open source.

**Comment by R-Hannibal** [comment]
@falaki - thank you so much again for bringing this issue to our attention.

We think this issue may have been fixed by a commit we made in our upcoming 1.3 patch release of RStudio. If you get the chance, will you try this in our [preview build](https://rstudio.com/products/rstudio/download/preview/) and let us know if the issue is still occurring for you there?

**Comment by falaki** [comment]
@R-Hannibal thanks for the note. I just tested [this preview binary](https://s3.amazonaws.com/rstudio-ide-build/server/bionic/amd64/rstudio-server-1.3.1087-amd64.deb) on the latest Databricks Runtime and I am still encountering the indefinite loop behavior.

**Comment by R-Hannibal** [comment]
Thanks for checking that @falaki. Really appreciate your patience and help as we try to address this issue. Need to ask for some more information as we try and pin this bug down:

- If you can enable diagnostics and provide a diagnostic log file, that would be great (linking the [document w/ the instructions](https://docs.rstudio.com/ide/server-pro/r-sessions.html#diagnosing-session-launch-failures), the document states pro, but should work on Open Source as well).
- Grab a HAR file (instructions per browser available [HERE](https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting)).

If you can grab those files add add them to the ticket, it will help us to diagnose the issue. Thanks again.

**Comment by falaki** [comment]
I could not enable diagnostics.
```
# rstudio-server version
1.3.1087 (Apricot Nasturtium) for Ubuntu Bionic
# rstudio-server restart
Error reading /etc/rstudio/rserver.conf: unrecognised option 'rsession-diagnostics-enabled'
```

The HAR file is attached.
[Rstudio.har.zip](https://github.com/rstudio/rstudio/files/5176735/Rstudio.har.zip)

**Comment by R-Hannibal** [comment]
@falaki - Sorry for the delay in response, these environment specific issues are difficult to pin down (we have not had any other users report the issue which leads us to believe it is something specific to your environment.

Any info on your proxy or auth setup will also help.

Please let us know if the issue is still occurring for you on our latest release (https://rstudio.com/products/rstudio/download/).

**Comment by falaki** [comment]
@R-Hannibal  sorry for late reply. Somehow I missed this notification. I just tried the latest version 1.4.1106. I am still observing indefinite redirects. I see the following warning on the browser (chrome) console:

```
[Deprecation] Synchronous XMLHttpRquest on the main thread lpfulllib.js:1 is deprecated because of its detremental effects to end user's experience. For more help, check https://xhr.spec.whatwq.org/.
```

Here is the new HAR file.
[Rstudio2.har.zip](https://github.com/rstudio/rstudio/files/6185929/Rstudio2.har.zip)


We are using an extension of  Jetty's [ProxyServlet](http://archive.eclipse.org/jetty/8.0.0.RC0/apidocs/org/eclipse/jetty/servlets/ProxyServlet.html).

**Comment by danieljohansso** [comment]
Just wanted to add that we are also experiencing the same issue in our team. We were in contact with Microsoft support and it seems to be an issue with the Databricks environment. DB Runtime currently does not support anything above 1.2.

**Comment by falaki** [comment]
After some investigation with help from @jmcphers we found that RStudio and Databricks both use the same cookie header name `X-CSRF-Token`. After successful authentication, the Databricks proxy overwrites this header with the Databricks value and this surprises the RStudio server and sends the client back to the auth page. The fix can be as simple as renaming the RStudio header to something more specific e.g., `X-RStudio-CSRF-Token`

**Comment by deka108** [comment]
Hi, 

I saw that RStudio already has `X-RS-RID` so in my solution prototype [here](https://github.com/deka108/rstudio/commit/1b99233d23a95e1eac1931a2c059f1cc829b7732), I renamed `X-CSRF-Token` to `X-RS-CSRF-Token`

Is the patch reasonable?

**Comment by jmcphers** [comment]
I opened this as a new issue with some analysis of what's going on:

https://github.com/rstudio/rstudio/issues/9768

**Comment by jmcphers** [comment]
I think this is fixed now that we have renamed the `X-CSRF-Token` header. You can confirm the fix in a daily build; please feel free to reopen if you still see the issue.

https://dailies.rstudio.com/
