### ISSUE TITLE
ctrl-z undo shortcut doesn't work in visual markdown editor

### ISSUE THREAD

**Issue by jon-mellon** [rstudio/rstudio#7588]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.4.673
    OS Version      : Windows 10
    R Version       : 4.0.0

### Steps to reproduce the problem
Type some text or code in R markdown. Press ctrl-Z. Nothing happens. 

### Describe the problem in detail
The undo shortcut keys don't work in visual markdown editor. They do work in the standard markdown view and the menu option for undo works. 

### Describe the behavior you expected
The same as if you went to:
edit-> undo

- [x ] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [x ] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [ x] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [ x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by jjallaire** [comment]
Thanks for reporting this! It should be fixed in the latest build (v1.4.708).

**Comment by cderv** [comment]
I can confirm that this does not work on 1.4.708 on windows 10.

Inside visual editor, 

* In code chunk, it works
* Outside of chunks, for markdown text, it does not work
    * CTRL+Z does nothing
    * Edit > Undo does work

**Comment by ronblum** [comment]
@cderv Can you try one of the [most recent dailies](https://dailies.rstudio.com)? It's probable that the fix didn't get picked up until the next daily build.

**Comment by cderv** [comment]
Nope it is still not working with 1.4.718 on windows 10. But... 

I tried something that may precise the issue: 

If I type text outside a chunk in visual mode
* CTRL+Z does not work when my cursor is still the text part (ouside chunk)
* It works if I put the cursor inside a chunk or in the yaml header box. 

Maybe that helps...

**Comment by cderv** [comment]
@ronblum still not working on windows 10 with 1.4.756 : CTRL+Z does not work, but Edit > Undo does.

**Comment by R-Hannibal** [comment]
Adding the duplicate label here to reflect this is the same issue as [7960](https://github.com/rstudio/rstudio/issues/7960). The follow-up investigation will occur on that ticket.
