### ISSUE TITLE
Crashing when building and reinstalling an R package

### ISSUE THREAD

**Issue by csgillespie** [rstudio/rstudio#8131]
### System details

    RStudio Edition :  IDS
    RStudio Version : 1.4.904
    OS Version      :  Ubuntu 20.04
    R Version       :  4.0.2

### Steps to reproduce the problem

Building and reinstalling a package (I also generate docs using roxygen2 with this step)

It's not completely reproducible. It's regular, but not everytime

### Describe the problem in detail

1. Working on a package - just plain R code, no vignettes. Pretty basic. Pkg passes all checks.
2. CTRL +B
3. Rstudio crashes and I have to restart (it doesn't completely exit, it usually closes the project)
4. Sometimes (not this time), it deletes the contains of the package folder

This has been happening on my system for a while. With different versions of R and RStudio. I can't get it 100% reproducible.

It does happen on other packages.

### Describe the behavior you expected

Not crashing ;)

[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5411414/diagnostics-report.txt)

- [X ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [X] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by csgillespie** [comment]
RStudio crashed again. This time

 * The contains of the directory is has been deleted (hidden files and all)
 * I get this message in the console
```
Warning message:
File monitoring failed for project at "/data/ncsg3/github/csgillespie/oysteR"
Error 2 (inotify_add_watch: No such file or directory)
Features disabled: R source file indexing, Diagnostics
```
 * The contents of the directory are (thankfully) recoverable at `..//00LOCK-oysteR/oysteR`
 * New report included
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/5415419/diagnostics-report.txt)

**Comment by kevinushey** [comment]
Thanks for the bug report -- unfortunately, I don't see any smoking guns in the diagnostics report and we haven't had any reports of this sort of issue thus far.

Just in case, do you still see this behavior if you remove your `.Rprofile` or other custom startup code?

**Comment by csgillespie** [comment]
I'll try and narrow it down. I think the likely suspect may be i3, but who knows

**Comment by kevinushey** [comment]
What is i3?

**Comment by csgillespie** [comment]
https://i3wm.org/

**Comment by csgillespie** [comment]
@ronblum @kevinushey I'm still getting the same issue (using last night's dallie). However, I have noticed that whenever RStudio crashes & restarts, I always have the same error in the diagnostic log

```
26 Nov 2020 16:11:34 [rsession-ncsg3] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: std::__cxx11::string rstudio::session::ClientEventService::clientId() src/cpp/session/SessionClientEventService.cpp:134
```

Is that any help? Happy to be a guinea pig for debugging

**Comment by mikebessuille** [comment]
Have you tried this in 1.3?

**Comment by csgillespie** [comment]
@mikebessuille Trying 1.3 now. I'll let you know when/if I get a crash

**Comment by csgillespie** [comment]
@mikebessuille v1.3.1093

Still crashing with build and install. With a very similar error message
```
30 Nov 2020 22:10:03 [rsession-ncsg3] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument
```

BTW, this is a completely different R package I'm working on, so it's not the package.

---
For info, my error log also contains this

> 30 Nov 2020 22:08:31 [rsession-ncsg3] ERROR r error 7 (Unexpected data type); OCCURRED AT rstudio::core::Error rstudio::r::sexp::extractFunctionInfo(SEXP, rstudio::core::r_util::FunctionInformation*, bool, bool) src/cpp/r/RSexp.cpp:1744; LOGGED FROM: rstudio::core::r_util::FunctionInformation rstudio::session::modules::rparser::{anonymous}::getInfoAssociatedWithFunctionAtCursor(rstudio::core::r_util::token_cursor::RTokenCursor, rstudio::session::modules::rparser::ParseStatus&) src/cpp/session/modules/SessionRParser.cpp:1158

multiple times

**Comment by kevinushey** [comment]
Thanks! Based on this error:

```
26 Nov 2020 16:11:34 [rsession-ncsg3] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: std::__cxx11::string rstudio::session::ClientEventService::clientId() src/cpp/session/SessionClientEventService.cpp:134
```

One suspicion: do you see this crash more often if you try to execute code (e.g. in the R console, or in the chunk of an R Markdown document) while building your package?

**Comment by kevinushey** [comment]
My guess here is that we're running into a case where:

The `rsession` process is shutting down, and so it's starting to clean up static variables. For example, the client event service object, which lives here:

https://github.com/rstudio/rstudio/blob/fc8f151b583ae780610fe11d851b9aa6624ad4a0/src/cpp/session/SessionClientEventService.cpp#L55-L59

And cleaning that up would imply cleaning up the `mutex_` object used there:

https://github.com/rstudio/rstudio/blob/fc8f151b583ae780610fe11d851b9aa6624ad4a0/src/cpp/session/SessionClientEventService.cpp#L128-L138

However, other threads are still live and attempting to use this object. Perhaps the service thread itself is still trying to handle requests; e.g. here?

https://github.com/rstudio/rstudio/blob/fc8f151b583ae780610fe11d851b9aa6624ad4a0/src/cpp/session/SessionClientEventService.cpp#L258-L265

Although if this were the case, I'd expect some kind of warning about us being unable to join / interrupt the service thread during shutdown. (Unless we were forcing shutdown before the service thread could properly clean up...)

If this is indeed the case, one potential fix would be to have a thread-local copy of the `clientId_` variable, I think?

**Comment by csgillespie** [comment]
> One suspicion: do you see this crash more often if you try to execute code (e.g. in the R console, or in the chunk of an R Markdown document) while building your package?

My gut feeling is yes. I've often felt the more R sessions I have, the more frequent the crash. But only having one session, it still crashes

**Comment by kevinushey** [comment]
Unfortunately I don't see a safe way of resolving this in 1.4, and without a reproducible example it's really hard for us to confirm any sort of fix :-/

The fact that you're the only user encountering this issue thus far makes me think it could be something unique to your environment -- hopefully we'll learn more if others encounter this issue.

**Comment by csgillespie** [comment]
I understand. Happy to run a branch that prints out a very verbose log if that's helpful.

**Comment by csgillespie** [comment]
A few more updates on this issue:

 * It occurs even when I have a single version of RStudio running, and no other R sessions open
 * I've tried using the source build instead of the .deb version (no difference)
 
I still get the error:

> 29 Dec 2020 10:37:49 [rsession-ncsg3] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: std::__cxx11::string rstudio::session::ClientEventService::clientId() src/cpp/session/SessionClientEventService.cpp:134

**Comment by kevinushey** [comment]
The fact that thus far no other users have reported this issue makes me think there could be something unique to your environment that is causing this issue. (That doesn't discount it being an RStudio issue; just that perhaps it's not triggered in "typical" environments.)

Do you still see the issue if you use a different window manager? Do you have any custom .Rprofile / .Renviron that could be affecting behavior here? Anything else "unique" to your environment?

**Comment by csgillespie** [comment]
I've ruled out my Rprofile (went vanilla and still had issues). I can't imagine it's my Renviron (nothing fancy).

I do have some customisations in my bash profile, so I'll look at that next. 

I noticed yesterday that:

 - I had two RStudio sessions open in different projects
 -  I was building a docker container in one RStudio project
 -  I could see the output (in a glitchy way) in the other RStudio ide

**Comment by kevinushey** [comment]
> I could see the output (in a glitchy way) in the other RStudio ide

Can you clarify what you mean? Do you mean that some output from the Build + Reload appeared in the other IDE instance?

**Comment by csgillespie** [comment]
> I could see the output (in a glitchy way) in the other RStudio ide
>
> Can you clarify what you mean? Do you mean that some output from the Build + Reload appeared in the other IDE instance?

In IDE 1, docker build was doing it's stuff in the RStudio terminal

When I switch to IDE2, I could see the docker output in IDE 2's
terminal. It wasn't a perfect view, more it flashed on and off a few
times. Sort of like the "Matrix". Does that make sense?

**Comment by kevinushey** [comment]
Interesting -- that sounds more like a weird rendering / display artifact than output actually being mis-directed to the wrong IDE instance. Does that sound correct to you? Or does the output "persist" on the other IDE instance? Can it be interacted with?

**Comment by csgillespie** [comment]
> Interesting
For you perhaps ;)

> that sounds more like a weird rendering / display artifact than output actually being mis-directed to the wrong IDE instance. 


> Does that sound correct to you?

Yes

>  Or does the output "persist" on the other IDE instance? Can it be interacted with?

I can't interact. It's only happened when running the docker build command - perhaps because that's a long running command

----

Something that is reproducible (for me) is

https://storyxpress.co/video/kjizwi1eugvkoskl5

**Comment by csgillespie** [comment]
Minor update. I tried switching my terminal to zsh (which I have never used, so hopefully no config issues). Still crashing :(

Next step, try a different windows/tiling manager

**Comment by csgillespie** [comment]
Still having this issue. Tried the daily and it actually makes things worse.

I have to disable building a package with {devtools} as this makes the issue worse.

Anecdotally, I know of a few people having this issue (at Jumping Rivers). However, we all have a similar set-up: Ubuntu, xps13 dells.

**Comment by kevinushey** [comment]
Still, until we can reproduce this issue locally, we don't really have a hope of resolving this (and thus far we have been unsuccessful in reproducing locally).

The fact that others in your organization (but thus far nobody outside your organization) is experiencing this issue makes me think there might be something unique to your environment that could be causing this.

**Comment by gerasy1987** [comment]
In case this might be useful, I have the same issue with building R package in RStudio for a while now on Elementary OS (Ubuntu derivative) on Dell XPS 13 9300

**Comment by csgillespie** [comment]
@gerasy1987 This makes sense to me. I think it could be related to a hardware issue.

> The fact that others in your organization (but thus far nobody outside your organization)

@kevinushey While we are in the same organization, each person (depending on role) is in charge of their laptop. For example, 
we don't have a list of Ubuntu packages we must use/install. Other than use an LTS version of Ubuntu. Even the version of RStudio differs (i dabble with dailies and preview), but most don't.

**Comment by MeganBeckett** [comment]
Hi there, I have also been having this issue. 

I'm on Ubuntu 20.04 on a Lenovo Thinkpad, running R 4.1 in RStudio 1.4. 

Whenever I rebuild an R package that I'm working on, the session crashes and disconnects. Rstudio then starts a new session but I have to close that as it's not the same project anymore, just a blank session and reopen the project again.

**Comment by kevinushey** [comment]
@MeganBeckett: do you also see this in other R packages, or is it specific to this package? Any other information you can provide that might help us reproduce this locally?

**Comment by andodet** [comment]
@kevinushey @MeganBeckett currently facing the same problem while developing a package. It seems that it is way more prone to happen when the package hasn't been rebuilt for a while.

**Comment by kevinushey** [comment]
Again, I apologize, but unless you can help us reproduce the issue locally we will not be able to resolve this.

**Comment by andodet** [comment]
@kevinushey sorry for not being more specific - what kind of info/logs would be beneficial in this scenario?

**Comment by jamieRowen** [comment]
I have also started experiencing this issue, no helpful log info at present I am afraid but perhaps things to note:

RStudio Pro version: 1.2.5033-1
R version: 4.0.3
OS: ubuntu 20.04

I had multiple instances of RStudio open, with only one open it seems to be have disappeared for the moment.
Deselecting devtools from build options seems to improve it (although not perfect) (devtools version 2.4.1)
During this time I was also getting a lot of lazy load database corrupt messages in the console too.

**Comment by csgillespie** [comment]
@kevinushey I realise that these bug reports are really frustrating at your end as you have nothing to work with.

I'm happy to run a "test" version of RStudio with extra logging if that's helpful?

**Comment by kevinushey** [comment]
The challenge here is I'm not even sure what extra logging would be useful. :-/

I can trial some fixes and get those into the next daily builds if you'd be willing to test.

**Comment by kevinushey** [comment]
The only other thing I can think of that would help is a stack trace; e.g. if you could attach `gdb` to the `rsession` process and see if you're able to catch a stack trace when the process exits (assuming it's terminating abnormally for some reason).

Looking in my logs, I apparently saw this some time back:

> 01 May 2021 06:54:42 [rsession-kevin] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: std::__cxx11::string rstudio::session::ClientEventService::clientId() src/cpp/session/SessionClientEventService.cpp:134

but I have no recollection of what I was doing at that time :-/

**Comment by kevinushey** [comment]
I'm not positive if this is the same thing, but I can reproduce an RStudio crash that occurs if the session is interrupted while building + restarting. First, kick off a package build; then, in a separate terminal, try running:

```
while true; do kill -INT $(pgrep -nx rsession); done
```

You should see the session crash. In some occasions, the aforementioned error:

> 25 Jun 2021 23:36:20 [rsession-kevin] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: std::__cxx11::string rstudio::session::ClientEventService::clientId() src/cpp/session/SessionClientEventService.cpp:134

shows up.

@csgillespie, do you _always_ see the previously mentioned error when a session crashes, or only sometimes? Is it possible you were trying to execute (and interrupt) R code while your package was building? Does the crash occur if try to build the package, but avoid interacting with the session thereafter?

I also see a similar-ish crash if I try to install + restart while RStudio has a child process running; e.g.

```
system("sleep 100", wait = FALSE)
```

Although in that case I get a separate error in the logs:

> 26 Jun 2021 00:07:02 [rsession-kevin] ERROR system error 98 (Address already in use); OCCURRED AT rstudio::core::Error rstudio::core::http::initTcpIpAcceptor(rstudio::core::http::SocketAcceptorService<rstudio_boost::asio::ip::tcp>&, const string&, const string&) src/cpp/session/http/SessionPosixHttpConnectionListener.cpp:103; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2048

**Comment by csgillespie** [comment]
Thanks @kevinushey I'll try and answer your comments/queries:

The error I get a lot is:

26 Jun 2021 10:53:40 [rsession-ncsg3] ERROR Unexpected exception: boost: mutex lock failed in pthread_mutex_lock: Invalid argument; LOGGED FROM: std::__cxx11::string rstudio::session::ClientEventService::clientId() src/cpp/session/SessionClientEventService.cpp:134

My gut feeling is when I use {devtools} for building packages, the number of threads generated is large. RStudio seems to miss some of these when restarting. Not using {devtools}, there are still multiple R processes generated, but as the number is significantly less, RStudio  is more stable.

> while true; do kill -INT $(pgrep -nx rsession); done

This does cause the session to crash. The difference is the session "hangs" until I kill the while loop

> Attach gdb to session

What's the best way of doing this?

**Comment by kevinushey** [comment]
> My gut feeling is when I use {devtools} for building packages, the number of threads generated is large. RStudio seems to miss some of these when restarting. Not using {devtools}, there are still multiple R processes generated, but as the number is significantly less, RStudio is more stable.

As far as I know, devtools shouldn't be creating any new threads; we're just running it in a separate R child process when performing the build. (Unless that process is for some reason not shutting down cleanly after build and install...)

To attach `gdb` to the `rsession`, you can do something like (from the terminal):

```
sudo gdb -p $(pgrep -nx rsession)
```

Then run `continue` to tell `gdb` to allow the `rsession` to continue executing. Then, try running Install and Restart, and see if `gdb` managed to capture a crash or similar. If a crash occurs, you should see gdb catch something like `SIGSEGV` or `SIGBUS`; at that point you can execute `bt` to get a backtrace.

I'd recommend watching something like https://www.youtube.com/watch?v=bWH-nL7v5F4 if you need a quick introduction to `gdb`.

**Comment by kevinushey** [comment]
It might also be useful to know if you have any child processes running; something like:

```
system(paste("ps --forest -g", Sys.getpid()))
```

since it's possible that running child processes could inhibit RStudio's shutdown in a install + restart.

(See other options in https://superuser.com/questions/363169/ps-how-can-i-recursively-get-all-child-process-for-a-given-pid if the above doesn't work)

**Comment by csgillespie** [comment]
Quick update while I'm still investigating. 

Just ran `top` and noticed I have `rstudio` and `rsession` running in the background. But I don't have any RStudio/rsession's open & haven't done all day. 

Thought: I wonder if sleep/hibernate is doing something odd?

**Comment by JanMarvin** [comment]
FYI the bind error also appears when restarting with active commands in a subshell. (That was kinda not obvious to me.)
```R
system("firefox &")
rstudioapi::restartSession()
```

**Comment by floswald** [comment]
I have the same issue on an imac.

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.7
```

**Comment by csgillespie** [comment]
I installed the "Rstudio preview electron" version a few days ago, which seemed to fix the issue. However, this version no longer appears on the website

**Comment by ronblum** [comment]
The preview is available at https://dailies.rstudio.com/ (we're working on the preview downloads on the new site). The MacOS version, 2022.12.0, is entirely Electron and is the only version available.

Please note that now that MacOS 13 is out, we only support MacOS 11 and above.

**Comment by floswald** [comment]
identical behaviour on a new M1 macbook pro and Rstudio Version 2022.12.0-preview+314 (2022.12.0-preview+314)

```
> sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6
```

![Screenshot 2022-11-06 at 18 51 55](https://user-images.githubusercontent.com/1021558/200186753-a518d847-22c2-4793-9a83-8bd32ea279b0.png)

**Comment by csgillespie** [comment]
This may (or may not help). But i notice that RStudio seems to leave running rsession processes. I don't have RStudio open, but `top` shows three sessions.

The "R tmp" directories for this sessions are empty except for the directory `rs-graphics-XXX`

**Comment by kevinushey** [comment]
Again, a gdb backtrace would be helpful here.

**Comment by MalditoBarbudo** [comment]
Having the same issue, in arch linux, with daily (electron) and stable builds with same errors in the rsession log (is how I found this issue).

`gdb` backtrace is not available. In case is of any help this is the gdb output during a crash:

```
> sudo gdb -p $(pgrep -nx rsession)

GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 35653
[New LWP 35654]
[New LWP 35655]
[New LWP 35656]
[New LWP 35657]
[New LWP 35659]
[New LWP 35663]
[New LWP 35664]
[New LWP 35675]
[New LWP 35755]
[New LWP 35756]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
0x00007fb4938894ae in ?? () from /usr/lib/libc.so.6
(gdb) continue
Continuing.
[Detaching after fork from child process 35834]
[Detaching after fork from child process 35853]
[Thread 0x7fb40d5fc6c0 (LWP 35657) exited]
[Thread 0x7fb40e5fe6c0 (LWP 35655) exited]
[Thread 0x7fb3e0f3b6c0 (LWP 35756) exited]
[Detaching after vfork from child process 35897]
[Thread 0x7fb3e17ff6c0 (LWP 35755) exited]
[Thread 0x7fb4072bc6c0 (LWP 35664) exited]
[Thread 0x7fb407abd6c0 (LWP 35663) exited]
[Thread 0x7fb40cdfb6c0 (LWP 35659) exited]
[Thread 0x7fb40ddfd6c0 (LWP 35656) exited]
[Thread 0x7fb40edff6c0 (LWP 35654) exited]
[Thread 0x7fb491835880 (LWP 35653) exited]
[Thread 0x7fb3f3bff6c0 (LWP 35675) exited]
[New process 35653]
[Inferior 1 (process 35653) exited with code 0144]
(gdb) bt
No stack.
```

The first two detachs after `(gdb) continue` occurs when I start the devtools clean and install and the package is built with no problems. After that the session crash when restarting the session and loading the package resulting in the rest of the `gdb` output. No stack seems to be available as there isn't any `SIG*` signal.
This occurs with all packages I'm developing and also when restarting the session manually (with Ctrl+Alt+F10 or the menu option).

The timing of the crash, always after building the package correctly and restarting the session (or just simply restarting the session) seems to indicate (at least for me) that there is a problem removing the previous session (the process always stays after a crash) and when creating the new session it fails to connect.

Also, just in case is of any help, after the crash and clicking the `reconnect` button, when both rsession processes are still executing in the system (the crashed and the new one), killing any of them results in RStudio popup indicating that the R session has been aborted. This could indicate that both rsession processes, the old and the new are somewhat attached to RStudio generating a conflict and the crash?

**Comment by MalditoBarbudo** [comment]
Looking better at `gdb` output, seems like is trying to create a new process with the same PID as the previous rsession?

```
Attaching to process 35653

...

(gdb) continue
Continuing.

...

[New process 35653]
[Inferior 1 (process 35653) exited with code 0144]
```

**Comment by kevinushey** [comment]
On the off chance it's related, we did recently fix an issue in the latest daily builds of RStudio where attempting to restart R while a process was running in the background would cause a crash. That is, this should work as expected now:

```
system("sleep 300 &")
rstudioapi::restartSession()
```

**Comment by MalditoBarbudo** [comment]
Running `daily-397` (waiting for `daily-401` to be packaged for AUR) but the crashes still happen randomly when restarting R session (by "install and reload" or manually), with same errors.

```
system("sleep 300 &")
rstudioapi::restartSession()
```

shows similar results, sometimes crashes, sometimes don't.

**Comment by kevinushey** [comment]
Weird -- it works every time for me; running with a development build on Ubuntu 22.04...

**Comment by MalditoBarbudo** [comment]
My bad, sorry. Seems like i had something weird in my system yesterday. 
After a clean reinstall, still in `daily-397`, no crash in all day, restarting very often the session while working in a couple of packages, while before updating to the latest dailies the crashes were almost every time for the past months.

No crashes either with 
```
system("sleep 300 &")
rstudioapi::restartSession()
```

So it seems that at least for me, the issue is solved in the latest dailies.

@kevinushey thanks a lot for all the hard work

**Comment by kevinushey** [comment]
Awesome, thank you for confirming!

@csgillespie, any chance you can check whether the issue persists for you in the latest daily builds as well?

**Comment by csgillespie** [comment]
```
"Desert Sunflower" Daily (0a4293de, 2023-09-07) for Ubuntu Jammy
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.09.0-daily+410 Chrome/114.0.5735.289 Electron/25.5.0 Safari/537.36
```

I can run 
```
rstudioapi::restartSession()
```
Multiple times without any issue. 

If I run 
```
system("sleep 300 &")
```
once. Then **every** subsequent run of `restartSession()` results in the message (in the console)

>  Error: Unable to establish connection with R session when executing `console_input`

**Comment by kevinushey** [comment]
Thanks -- are you also still seeing the crash you described originally?

**Comment by csgillespie** [comment]
Yep. Still getting the crashes.
