### ISSUE TITLE
Rstudio consistently-but-randomly slowing down & crashing when viewing Stan files

### ISSUE THREAD

**Issue by mike-lawrence** [rstudio/rstudio#9055]
Sorry for not having a reprex ready, but despite multiple other Stan users reporting similar behaviour in both the [discourse](https://discourse.mc-stan.org/t/problems-with-crashing-r-session/20994) forum and on the Stan slack, I'm having trouble making this happen in a reproducible way. 

For me, I'm running RStudio 1.4.1106 with R 4.0.3 on Ubuntu 20.04.2, and I have RStan 2.21.2 installed though I don't use it and instead use CmdStanR 0.3.0.9000. 

Any tips for working out what's going on?

**Comment by ronblum** [comment]
@mike-lawrence and @carloszarzar Thank you for raising the issue, including the example and Discourse reference! I'll mark this for review as part of our ongoing development of RStudio.

**Comment by spinkney** [comment]
This seems to be something in the lintr that rstudio uses for stan. I've reproduced this problem on linux and windows.

The way to do it is start with a stan script in Rstudio. Make a change and save. Continue doing this. Saving the file will start to slow down considerably. At some point Rstudio will crash. Using R 4.04 and Rstudio 1.4.1103.

Example stan file
```stan
data {
  int<lower=0> N;
  vector[N] y;
}
transformed data {
  real a = y[1];
  real b = a;
  //... continue adding a line and resaving the file 
}
parameters {
  real mu;
  real<lower=0> sigma;
}
model {
  y ~ normal(mu, sigma);
}
```

**Comment by SteveBronder** [comment]
I think it might depend on the file size for how often it crashes. I've had larger files crash after just saving 3 to 4 times

**Comment by mike-lawrence** [comment]
Using @spinkney 's example (though I didn't want the model to be getting bigger, so I kept just the first line in the `transformed data` section and alphebetically incremented the variable name there), here's the approximate time in seconds that it takes from clicking save to the time the UI shows the file as saved:
b:  <1
c: 5
d: 8
e: 5
f: 8
g: crash

(just from one run)

Note that before the crash, even quitting Rstudio takes a noticeably long time to actually complete.

**Comment by SteveBronder** [comment]
Also posting the discourse post on the Stan forums about this below

https://discourse.mc-stan.org/t/weird-error-in-r-studio-console-whenever-i-open-up-a-stan-file/19912

**Comment by kevinushey** [comment]
RStudio uses `rstan::stanc_builder()` to collect diagnostics:

https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/stan/SessionStan.R#L145

so presumedly that is failing or crashing with your files for some reason.

**Comment by stephensrmmartin** [comment]
Specs: i5-6500 (4 cores); 16gb ddr4; 1tb nvme drive.

I can reproduce the crash, and can confirm a drastic slowdown. Using Sean's code, I incremented through the alphabet, down to aa, bb, cc. There is a massive slowdown when saving; to the point where it's taking ~ 1 minute just to save the file. Moreover, once it's done saving, my CPU usage for the rsession (which is otherwise untouched, empty, no workspace, just the initial prompt) is about 60-140%; ram usage got up to around 10-20%. 

Using R 4.0.4 on arch; with a recent git version of rstudio-desktop (from a few days ago).

**Comment by kevinushey** [comment]
Can you collect a profile (via `Rprof()`) to figure out what the R session is doing during the hang?

**Comment by SteveBronder** [comment]
Looking at the stanc code, does a v8 instance need to be cleanup up when you use it in a function?

https://github.com/stan-dev/rstan/blob/ae36e6f9842e9e16ef79700ce86a122bfa9c5b10/rstan/rstan/R/stanc.R#L140

In stanc_beta where I'm guessing the error is coming from

```R
  ctx <- V8::v8()
  ctx$source("https://github.com/stan-dev/stanc3/releases/download/nightly/stanc.js")
  model_cppcode <- try(ctx$call("stanc", model_name, paste(model_code, collapse = "\n")), silent = TRUE)
```

**Comment by stephensrmmartin** [comment]
Some notes:

- Stan file complexity is irrelevant; I experienced slowdowns just by removing a space, saving, and adding a space, saving, repeatedly. Note again, this doesn't happen when I just repeatedly call stanc_builder.
- The R session hangs even after it saves, but eventually becomes responsive again.

Rprof output after a few of these things:

```
> summaryRprof()
$by.self
                          self.time self.pct total.time total.pct
".Call"                       83.52    64.11      83.52     64.11
"readLines"                   22.68    17.41      22.68     17.41
"stanc"                       10.12     7.77     129.78     99.62
"open.connection"              7.96     6.11       7.96      6.11
"paste"                        3.86     2.96      26.54     20.37
"system2"                      0.66     0.51       0.66      0.51
"close.connection"             0.56     0.43       0.56      0.43
"system"                       0.08     0.06       0.10      0.08
".local"                       0.06     0.05       0.06      0.05
"putconst"                     0.06     0.05       0.06      0.05
"stopifnot"                    0.06     0.05       0.06      0.05
"cmp"                          0.04     0.03       0.20      0.15
"parse_string"                 0.04     0.03       0.04      0.03
"rstan_options"                0.04     0.03       0.04      0.03
"tryCatch"                     0.02     0.02     130.16     99.91
"tryCatchOne"                  0.02     0.02     130.14     99.89
"try"                          0.02     0.02     119.68     91.86
"stanc_beta"                   0.02     0.02     119.62     91.82
"context_eval"                 0.02     0.02     109.96     84.40
"cmpCallSymFun"                0.02     0.02       0.12      0.09
"lapply"                       0.02     0.02       0.10      0.08
"textConnection"               0.02     0.02       0.04      0.03
".rs.objectsOnSearchPath"      0.02     0.02       0.02      0.02
"%in%"                         0.02     0.02       0.02      0.02
"apply"                        0.02     0.02       0.02      0.02
"as.character"                 0.02     0.02       0.02      0.02
"as.list"                      0.02     0.02       0.02      0.02
"c"                            0.02     0.02       0.02      0.02
"checkCall"                    0.02     0.02       0.02      0.02
"cmpBuiltinArgs"               0.02     0.02       0.02      0.02
"file.exists"                  0.02     0.02       0.02      0.02
"findCenvVar"                  0.02     0.02       0.02      0.02
"get0"                         0.02     0.02       0.02      0.02
"grep"                         0.02     0.02       0.02      0.02
"isTRUE"                       0.02     0.02       0.02      0.02
"lazyLoadDBfetch"              0.02     0.02       0.02      0.02
"ls"                           0.02     0.02       0.02      0.02
"match.arg"                    0.02     0.02       0.02      0.02
"new_handle"                   0.02     0.02       0.02      0.02
"paste0"                       0.02     0.02       0.02      0.02
"strsplit"                     0.02     0.02       0.02      0.02

$by.total
                               total.time total.pct self.time self.pct
"<Anonymous>"                      130.18     99.92      0.00     0.00
"tryCatch"                         130.16     99.91      0.02     0.02
"tryCatchOne"                      130.14     99.89      0.02     0.02
"doTryCatch"                       130.14     99.89      0.00     0.00
"tryCatchList"                     130.14     99.89      0.00     0.00
"withCallingHandlers"              129.88     99.69      0.00     0.00
".rs.stan.runDiagnostics"          129.86     99.68      0.00     0.00
"rstan::stanc_builder"             129.80     99.63      0.00     0.00
"stanc"                            129.78     99.62     10.12     7.77
"try"                              119.68     91.86      0.02     0.02
"stanc_beta"                       119.62     91.82      0.02     0.02
"context_eval"                     109.96     84.40      0.02     0.02
"evaluate_js"                      109.96     84.40      0.00     0.00
"get_str_output"                   109.96     84.40      0.00     0.00
"ctx$source"                        95.56     73.35      0.00     0.00
".Call"                             83.52     64.11     83.52    64.11
"paste"                             26.54     20.37      3.86     2.96
"join"                              26.52     20.36      0.00     0.00
"ctx$call"                          23.12     17.75      0.00     0.00
"get_json_output"                   23.00     17.65      0.00     0.00
"readLines"                         22.68     17.41     22.68    17.41
"curl_connection"                    7.98      6.13      0.00     0.00
"curl"                               7.98      6.13      0.00     0.00
"open.connection"                    7.96      6.11      7.96     6.11
"open"                               7.96      6.11      0.00     0.00
"system2"                            0.66      0.51      0.66     0.51
"get_CXX"                            0.66      0.51      0.00     0.00
"close.connection"                   0.56      0.43      0.56     0.43
"close"                              0.56      0.43      0.00     0.00
"cmpfun"                             0.24      0.18      0.00     0.00
"compiler:::tryCmpfun"               0.24      0.18      0.00     0.00
"h"                                  0.22      0.17      0.00     0.00
"tryInline"                          0.22      0.17      0.00     0.00
"cmp"                                0.20      0.15      0.04     0.03
"cmpCall"                            0.20      0.15      0.00     0.00
"genCode"                            0.20      0.15      0.00     0.00
"cmpCallSymFun"                      0.12      0.09      0.02     0.02
"cmpSymbolAssign"                    0.12      0.09      0.00     0.00
"FUN"                                0.12      0.09      0.00     0.00
"system"                             0.10      0.08      0.08     0.06
"lapply"                             0.10      0.08      0.02     0.02
"make_context"                       0.10      0.08      0.00     0.00
"pkgbuild::with_build_tools"         0.10      0.08      0.00     0.00
"reset"                              0.10      0.08      0.00     0.00
"v8"                                 0.10      0.08      0.00     0.00
".rs.getCompletionsSearchPath"       0.08      0.06      0.00     0.00
"cb$putconst"                        0.08      0.06      0.00     0.00
"cmpCallArgs"                        0.08      0.06      0.00     0.00
"Reduce"                             0.08      0.06      0.00     0.00
"vapply"                             0.08      0.06      0.00     0.00
".local"                             0.06      0.05      0.06     0.05
"putconst"                           0.06      0.05      0.06     0.05
"stopifnot"                          0.06      0.05      0.06     0.05
"asJSON"                             0.06      0.05      0.00     0.00
"cb$putcode"                         0.06      0.05      0.00     0.00
"findLocalsList"                     0.06      0.05      0.00     0.00
"findLocalsList1"                    0.06      0.05      0.00     0.00
"fromJSON"                           0.06      0.05      0.00     0.00
"funEnv"                             0.06      0.05      0.00     0.00
"make.functionContext"               0.06      0.05      0.00     0.00
"parse_and_simplify"                 0.06      0.05      0.00     0.00
"Rd2HTML"                            0.06      0.05      0.00     0.00
"toJSON"                             0.06      0.05      0.00     0.00
"parse_string"                       0.04      0.03      0.04     0.03
"rstan_options"                      0.04      0.03      0.04     0.03
"textConnection"                     0.04      0.03      0.02     0.02
"base::try"                          0.04      0.03      0.00     0.00
"parseJSON"                          0.04      0.03      0.00     0.00
"writeBlock"                         0.04      0.03      0.00     0.00
"writeContent"                       0.04      0.03      0.00     0.00
"writeLink"                          0.04      0.03      0.00     0.00
"writeSection"                       0.04      0.03      0.00     0.00
"writeWrapped"                       0.04      0.03      0.00     0.00
".rs.objectsOnSearchPath"            0.02      0.02      0.02     0.02
"%in%"                               0.02      0.02      0.02     0.02
"apply"                              0.02      0.02      0.02     0.02
"as.character"                       0.02      0.02      0.02     0.02
"as.list"                            0.02      0.02      0.02     0.02
"c"                                  0.02      0.02      0.02     0.02
"checkCall"                          0.02      0.02      0.02     0.02
"cmpBuiltinArgs"                     0.02      0.02      0.02     0.02
"file.exists"                        0.02      0.02      0.02     0.02
"findCenvVar"                        0.02      0.02      0.02     0.02
"get0"                               0.02      0.02      0.02     0.02
"grep"                               0.02      0.02      0.02     0.02
"isTRUE"                             0.02      0.02      0.02     0.02
"lazyLoadDBfetch"                    0.02      0.02      0.02     0.02
"ls"                                 0.02      0.02      0.02     0.02
"match.arg"                          0.02      0.02      0.02     0.02
"new_handle"                         0.02      0.02      0.02     0.02
"paste0"                             0.02      0.02      0.02     0.02
"strsplit"                           0.02      0.02      0.02     0.02
"::"                                 0.02      0.02      0.00     0.00
"?"                                  0.02      0.02      0.00     0.00
".make_numeric_version"              0.02      0.02      0.00     0.00
">="                                 0.02      0.02      0.00     0.00
"addVar"                             0.02      0.02      0.00     0.00
"append"                             0.02      0.02      0.00     0.00
"as.numeric_version"                 0.02      0.02      0.00     0.00
"assign"                             0.02      0.02      0.00     0.00
"cmpBuiltin"                         0.02      0.02      0.00     0.00
"cmpCa                               0.02      0.02      0.00     0.00
"cmpDotInternalCall"                 0.02      0.02      0.00     0.00
"cmpForBody"                         0.02      0.02      0.00     0.00
"cmpPrim2"                           0.02      0.02      0.00     0.00
"cmpSubsetDispatch"                  0.02      0.02      0.00     0.00
"constantFold"                       0.02      0.02      0.00     0.00
"constantFoldCall"                   0.02      0.02      0.00     0.00
"eval"                               0.02      0.02      0.00     0.00
"find.package"                       0.02      0.02      0.00     0.00
"findLocals1"                        0.02      0.02      0.00     0.00
"getExportedValue"                   0.02      0.02      0.00     0.00
"getFoldFun"                         0.02      0.02      0.00     0.00
"getInlineInfo"                      0.02      0.02      0.00     0.00
"help"                               0.02      0.02      0.00     0.00
"index.search"                       0.02      0.02      0.00     0.00
"isBaseVar"                          0.02      0.02      0.00     0.00
"numeric_version"                    0.02      0.02      0.00     0.00
"Ops.numeric_version"                0.02      0.02      0.00     0.00
"RdTags"                             0.02      0.02      0.00     0.00
"simplify"                           0.02      0.02      0.00     0.00
"strwrap"                            0.02      0.02      0.00     0.00
"urlify"                             0.02      0.02      0.00     0.00
"writeHref"                          0.02      0.02      0.00     0.00

$sample.interval
[1] 0.02
```

**Comment by stephensrmmartin** [comment]
Ok, I once again got it to crash, just by deleting a space, saving, adding the space, saving, etc, repeatedly until it crashed.

Rprof is below.
The last thing in the Rprof.out file is `"tryCatch" ".rs.stan.runDiagnostics" "<Anonymous>" 
"re`

After it saves, the R session can be unresponsive for nearly a minute; so -- A minute or so to save, then another minute before the R console can return anything at all.

```
$by.self
                          self.time self.pct total.time total.pct
".Call"                      467.40    67.12     467.40     67.12
"readLines"                   96.66    13.88      96.72     13.89
"stanc"                       52.46     7.53     694.36     99.72
"open.connection"             48.00     6.89      48.00      6.89
"paste"                       19.08     2.74     115.68     16.61
"system2"                      5.48     0.79       5.50      0.79
"close.connection"             2.56     0.37       2.56      0.37
"system"                       1.24     0.18       1.28      0.18
"strsplit"                     0.70     0.10       0.70      0.10
"stopifnot"                    0.20     0.03       0.40      0.06
"stanc_beta"                   0.14     0.02     641.70     92.15
"grep"                         0.14     0.02       0.14      0.02
"parse_string"                 0.12     0.02       0.12      0.02
"rstan_options"                0.12     0.02       0.12      0.02
"file.exists"                  0.08     0.01       0.08      0.01
"options"                      0.08     0.01       0.08      0.01
"doTryCatch"                   0.06     0.01     695.00     99.81
"try"                          0.06     0.01     641.80     92.17
"get_str_output"               0.06     0.01     582.28     83.62
"match.arg"                    0.06     0.01       0.16      0.02
"eval"                         0.06     0.01       0.10      0.01
"textConnection"               0.06     0.01       0.10      0.01
".local"                       0.06     0.01       0.08      0.01
"isTRUE"                       0.06     0.01       0.06      0.01
"putconst"                     0.06     0.01       0.06      0.01
"FUN"                          0.04     0.01       0.46      0.07
"lapply"                       0.04     0.01       0.24      0.03
"cmp"                          0.04     0.01       0.22      0.03
"new_handle"                   0.04     0.01       0.18      0.03
"asJSON"                       0.04     0.01       0.12      0.02
"scan"                         0.04     0.01       0.08      0.01
"unique.default"               0.04     0.01       0.08      0.01
"makeRestartList"              0.04     0.01       0.06      0.01
"c"                            0.04     0.01       0.04      0.01
"is.factor"                    0.04     0.01       0.04      0.01
"requireNamespace"             0.04     0.01       0.04      0.01
"sub"                          0.04     0.01       0.04      0.01
"tryCatch"                     0.02     0.00     695.02     99.81
"tryCatchList"                 0.02     0.00     695.00     99.81
"tryCatchOne"                  0.02     0.00     695.00     99.81
"withCallingHandlers"          0.02     0.00     694.68     99.76
"context_eval"                 0.02     0.00     582.24     83.61
"curl_connection"              0.02     0.00      48.22      6.92
"close"                        0.02     0.00       2.58      0.37
"toJSON"                       0.02     0.00       0.26      0.04
"...elt"                       0.02     0.00       0.20      0.03
"fromJSON"                     0.02     0.00       0.18      0.03
"handle_setopt"                0.02     0.00       0.14      0.02
"cmpCallSymFun"                0.02     0.00       0.12      0.02
"%in%"                         0.02     0.00       0.04      0.01
"as.list"                      0.02     0.00       0.04      0.01
"getExportedValue"             0.02     0.00       0.04      0.01
"simplify"                     0.02     0.00       0.04      0.01
".rs.objectsOnSearchPath"      0.02     0.00       0.02      0.00
"$"                            0.02     0.00       0.02      0.00
"$<-"                          0.02     0.00       0.02      0.00
"apply"                        0.02     0.00       0.02      0.00
"as.character"                 0.02     0.00       0.02      0.00
"as.integer"                   0.02     0.00       0.02      0.00
"as.list.default"              0.02     0.00       0.02      0.00
"checkCall"                    0.02     0.00       0.02      0.00
"cmpBuiltinArgs"               0.02     0.00       0.02      0.00
"deparse_vector"               0.02     0.00       0.02      0.00
"file.remove"                  0.02     0.00       0.02      0.00
"findCenvVar"                  0.02     0.00       0.02      0.00
"get_model_strcode"            0.02     0.00       0.02      0.00
"get0"                         0.02     0.00       0.02      0.00
"getOption"                    0.02     0.00       0.02      0.00
"grepl"                        0.02     0.00       0.02      0.00
"lazyLoadDBfetch"              0.02     0.00       0.02      0.00
"legitimate_model_name"        0.02     0.00       0.02      0.00
"ls"                           0.02     0.00       0.02      0.00
"match.fun"                    0.02     0.00       0.02      0.00
"mode"                         0.02     0.00       0.02      0.00
"paste0"                       0.02     0.00       0.02      0.00
"path.expand"                  0.02     0.00       0.02      0.00
"re                            0.02     0.00       0.02      0.00
"shQuote"                      0.02     0.00       0.02      0.00
"sys.parent"                   0.02     0.00       0.02      0.00
"Sys.time"                     0.02     0.00       0.02      0.00

$by.total
                                        total.time total.pct self.time
"<Anonymous>"                               695.32     99.85      0.00
"tryCatch"                                  695.02     99.81      0.02
"doTryCatch"                                695.00     99.81      0.06
"tryCatchList"                              695.00     99.81      0.02
"tryCatchOne"                               695.00     99.81      0.02
".rs.stan.runDiagnostics"                   694.96     99.80      0.00
"withCallingHandlers"                       694.68     99.76      0.02
"rstan::stanc_builder"                      694.58     99.75      0.00
"stanc"                                     694.36     99.72     52.46
"try"                                       641.80     92.17      0.06
"stanc_beta"                                641.70     92.15      0.14
"get_str_output"                            582.28     83.62      0.06
"evaluate_js"                               582.28     83.62      0.00
"context_eval"                              582.24     83.61      0.02
"ctx$source"                                497.36     71.42      0.00
".Call"                                     467.40     67.12    467.40
"ctx$call"                                  136.54     19.61      0.00
"get_json_output"                           135.92     19.52      0.00
"paste"                                     115.68     16.61     19.08
"join"                                      115.58     16.60      0.00
"readLines"                                  96.72     13.89     96.66
"curl_connection"                            48.22      6.92      0.02
"curl"                                       48.22      6.92      0.00
"open.connection"                            48.00      6.89     48.00
"open"                                       48.00      6.89      0.00
"system2"                                     5.50      0.79      5.48
"get_CXX"                                     5.50      0.79      0.00
"close"                                       2.58      0.37      0.02
"close.connection"                            2.56      0.37      2.56
"pkgbuild::with_build_tools"                  1.30      0.19      0.00
"system"                                      1.28      0.18      1.24
"summaryRprof"                                0.92      0.13      0.00
"strsplit"                                    0.70      0.10      0.70
"reset"                                       0.50      0.07      0.00
"v8"                                          0.50      0.07      0.00
"FUN"                                         0.46      0.07      0.04
"make_context"                                0.46      0.07      0.00
"stopifnot"                                   0.40      0.06      0.20
"vapply"                                      0.32      0.05      0.00
"cmpfun"                                      0.28      0.04      0.00
"compiler:::tryCmpfun"                        0.28      0.04      0.00
"toJSON"                                      0.26      0.04      0.02
"lapply"                                      0.24      0.03      0.04
".rs.stan.copySourceDatabaseToTempfile"       0.24      0.03      0.00
"cmp"                                         0.22      0.03      0.04
"cmpCall"                                     0.22      0.03      0.00
"genCode"                                     0.22      0.03      0.00
"h"                                           0.22      0.03      0.00
"tryInline"                                   0.22      0.03      0.00
"...elt"                                      0.20      0.03      0.02
".rs.getSourceDocumentProperties"             0.20      0.03      0.00
"new_handle"                                  0.18      0.03      0.04
"fromJSON"                                    0.18      0.03      0.02
"match.arg"                                   0.16      0.02      0.06
"context_validate"                            0.16      0.02      0.00
"parse_and_simplify"                          0.16      0.02      0.00
"this$validate"                               0.16      0.02      0.00
"grep"                                        0.14      0.02      0.14
"handle_setopt"                               0.14      0.02      0.02
"cmpSymbolAssign"                             0.14      0.02      0.00
"parse_string"                                0.12      0.02      0.12
"rstan_options"                               0.12      0.02      0.12
"asJSON"                                      0.12      0.02      0.04
"cmpCallSymFun"                               0.12      0.02      0.02
"parseJSON"                                   0.12      0.02      0.00
"Reduce"                                      0.12      0.02      0.00
"eval"                                        0.10      0.01      0.06
"textConnection"                              0.10      0.01      0.06
"curl_options"                                0.10      0.01      0.00
"file.exists"                                 0.08      0.01      0.08
"options"                                     0.08      0.01      0.08
".local"                                      0.08      0.01      0.06
"scan"                                        0.08      0.01      0.04
"unique.default"                              0.08      0.01      0.04
".rs.getCompletionsSearchPath"                0.08      0.01      0.00
"cb$putconst"                                 0.08      0.01      0.00
"cmpCallArgs"                                 0.08      0.01      0.00
"findLocalsList"                              0.08      0.01      0.00
"findLocalsList1"                             0.08      0.01      0.00
"fix_options"                                 0.08      0.01      0.00
"funEnv"                                      0.08      0.01      0.00
"make.functionContext"                        0.08      0.01      0.00
"isTRUE"                                      0.06      0.01      0.06
"putconst"                                    0.06      0.01      0.06
"makeRestartList"                             0.06      0.01      0.04
".signalSimpleWarning"                        0.06      0.01      0.00
"cb$putcode"                                  0.06      0.01      0.00
"Rd2HTML"                                     0.06      0.01      0.00
"withRestarts"                                0.06      0.01      0.00
"c"                                           0.04      0.01      0.04
"is.factor"                                   0.04      0.01      0.04
"requireNamespace"                            0.04      0.01      0.04
"sub"                                         0.04      0.01      0.04
"%in%"                                        0.04      0.01      0.02
"as.list"                                     0.04      0.01      0.02
"getExportedValue"                            0.04      0.01      0.02
"simplify"                                    0.04      0.01      0.02
"::"                                          0.04      0.01      0.00
"base::try"                                   0.04      0.01      0.00
"writeBlock"                                  0.04      0.01      0.00
"writeContent"                                0.04      0.01      0.00
"writeLink"                                   0.04      0.01      0.00
"writeSection"                                0.04      0.01      0.00
"writeWrapped"                                0.04      0.01      0.00
".rs.objectsOnSearchPath"                     0.02      0.00      0.02
"$"                                           0.02      0.00      0.02
"$<-"                                         0.02      0.00      0.02
"apply"                                       0.02      0.00      0.02
"as.character"                                0.02      0.00      0.02
"as.integer"                                  0.02      0.00      0.02
"as.list.default"                             0.02      0.00      0.02
"checkCall"                                   0.02      0.00      0.02
"cmpBuiltinArgs"                              0.02      0.00      0.02
"deparse_vector"                              0.02      0.00      0.02
"file.remove"                                 0.02      0.00      0.02
"findCenvVar"                                 0.02      0.00      0.02
"get_model_strcode"                           0.02      0.00      0.02
"get0"                                        0.02      0.00      0.02
"getOption"                                   0.02      0.00      0.02
"grepl"                                       0.02      0.00      0.02
"lazyLoadDBfetch"                             0.02      0.00      0.02
"legitimate_model_name"                       0.02      0.00      0.02
"ls"                                          0.02      0.00      0.02
"match.fun"                                   0.02      0.00      0.02
"mode"                                        0.02      0.00      0.02
"paste0"                                      0.02      0.00      0.02
"path.expand"                                 0.02      0.00      0.02
"re                                           0.02      0.00      0.02
"shQuote"                                     0.02      0.00      0.02
"sys.parent"                                  0.02      0.00      0.02
"Sys.time"                                    0.02      0.00      0.02
"?"                                           0.02      0.00      0.00
".make_numeric_version"                       0.02      0.00      0.00
".rs.getCompletionsLibraryContext"            0.02      0.00      0.00
".rs.getCompletionsNAMESPACE"                 0.02      0.00      0.00
">="                                          0.02      0.00      0.00
"addVar"                                      0.02      0.00      0.00
"append"                                      0.02      0.00      0.00
"as.numeric_version"                          0.02      0.00      0.00
"assign"                                      0.02      0.00      0.00
"cmpBuiltin"                                  0.02      0.00      0.00
"cmpDotInternalCall"                          0.02      0.00      0.00
"cmpForBody"                                  0.02      0.00      0.00
"cmpPrim2"                                    0.02      0.00      0.00
"cmpSubsetDispatch"                           0.02      0.00      0.00
"constantFold"                                0.02      0.00      0.00
"constantFoldCall"                            0.02      0.00      0.00
"deparse"                                     0.02      0.00      0.00
"file"                                        0.02      0.00      0.00
"find.package"                                0.02      0.00      0.00
"findLocals1"                                 0.02      0.00      0.00
"formals"                                     0.02      0.00      0.00
"getFoldFun"                                  0.02      0.00      0.00
"getInlineInfo"                               0.02      0.00      0.00
"help"                                        0.02      0.00      0.00
"index.search"                                0.02      0.00      0.00
"isBaseVar"                                   0.02      0.00      0.00
"normalizePath"                               0.02      0.00      0.00
"numeric_version"                             0.02      0.00      0.00
"Ops.numeric_version"                         0.02      0.00      0.00
"RdTags"                                      0.02      0.00      0.00
"strwrap"                                     0.02      0.00      0.00
"sys.function"                                0.02      0.00      0.00
"table"                                       0.02      0.00      0.00
"urlify"                                      0.02      0.00      0.00
"writeHref"                                   0.02      0.00      0.00
"writeLines"                                  0.02      0.00      0.00
                                        self.pct
"<Anonymous>"                               0.00
"tryCatch"                                  0.00
"doTryCatch"                                0.01
"tryCatchList"                              0.00
"tryCatchOne"                               0.00
".rs.stan.runDiagnostics"                   0.00
"withCallingHandlers"                       0.00
"rstan::stanc_builder"                      0.00
"stanc"                                     7.53
"try"                                       0.01
"stanc_beta"                                0.02
"get_str_output"                            0.01
"evaluate_js"                               0.00
"context_eval"                              0.00
"ctx$source"                                0.00
".Call"                                    67.12
"ctx$call"                                  0.00
"get_json_output"                           0.00
"paste"                                     2.74
"join"                                      0.00
"readLines"                                13.88
"curl_connection"                           0.00
"curl"                                      0.00
"open.connection"                           6.89
"open"                                      0.00
"system2"                                   0.79
"get_CXX"                                   0.00
"close"                                     0.00
"close.connection"                          0.37
"pkgbuild::with_build_tools"                0.00
"system"                                    0.18
"summaryRprof"                              0.00
"strsplit"                                  0.10
"reset"                                     0.00
"v8"                                        0.00
"FUN"                                       0.01
"make_context"                              0.00
"stopifnot"                                 0.03
"vapply"                                    0.00
"cmpfun"                                    0.00
"compiler:::tryCmpfun"                      0.00
"toJSON"                                    0.00
"lapply"                                    0.01
".rs.stan.copySourceDatabaseToTempfile"     0.00
"cmp"                                       0.01
"cmpCall"                                   0.00
"genCode"                                   0.00
"h"                                         0.00
"tryInline"                                 0.00
"...elt"                                    0.00
".rs.getSourceDocumentProperties"           0.00
"new_handle"                                0.01
"fromJSON"                                  0.00
"match.arg"                                 0.01
"context_validate"                          0.00
"parse_and_simplify"                        0.00
"this$validate"                             0.00
"grep"                                      0.02
"handle_setopt"                             0.00
"cmpSymbolAssign"                           0.00
"parse_string"                              0.02
"rstan_options"                             0.02
"asJSON"                                    0.01
"cmpCallSymFun"                             0.00
"parseJSON"                                 0.00
"Reduce"                                    0.00
"eval"                                      0.01
"textConnection"                            0.01
"curl_options"                              0.00
"file.exists"                               0.01
"options"                                   0.01
".local"                                    0.01
"scan"                                      0.01
"unique.default"                            0.01
".rs.getCompletionsSearchPath"              0.00
"cb$putconst"                               0.00
"cmpCallArgs"                               0.00
"findLocalsList"                            0.00
"findLocalsList1"                           0.00
"fix_options"                               0.00
"funEnv"                                    0.00
"make.functionContext"                      0.00
"isTRUE"                                    0.01
"putconst"                                  0.01
"makeRestartList"                           0.01
".signalSimpleWarning"                      0.00
"cb$putcode"                                0.00
"Rd2HTML"                                   0.00
"withRestarts"                              0.00
"c"                                         0.01
"is.factor"                                 0.01
"requireNamespace"                          0.01
"sub"                                       0.01
"%in%"                                      0.00
"as.list"                                   0.00
"getExportedValue"                          0.00
"simplify"                                  0.00
"::"                                        0.00
"base::try"                                 0.00
"writeBlock"                                0.00
"writeContent"                              0.00
"writeLink"                                 0.00
"writeSection"                              0.00
"writeWrapped"                              0.00
".rs.objectsOnSearchPath"                   0.00
"$"                                         0.00
"$<-"                                       0.00
"apply"                                     0.00
"as.character"                              0.00
"as.integer"                                0.00
"as.list.default"                           0.00
"checkCall"                                 0.00
"cmpBuiltinArgs"                            0.00
"deparse_vector"                            0.00
"file.remove"                               0.00
"findCenvVar"                               0.00
"get_model_strcode"                         0.00
"get0"                                      0.00
"getOption"                                 0.00
"grepl"                                     0.00
"lazyLoadDBfetch"                           0.00
"legitimate_model_name"                     0.00
"ls"                                        0.00
"match.fun"                                 0.00
"mode"                                      0.00
"paste0"                                    0.00
"path.expand"                               0.00
"re                                         0.00
"shQuote"                                   0.00
"sys.parent"                                0.00
"Sys.time"                                  0.00
"?"                                         0.00
".make_numeric_version"                     0.00
".rs.getCompletionsLibraryContext"          0.00
".rs.getCompletionsNAMESPACE"               0.00
">="                                        0.00
"addVar"                                    0.00
"append"                                    0.00
"as.numeric_version"                        0.00
"assign"                                    0.00
"cmpBuiltin"                                0.00
"cmpDotInternalCall"                        0.00
"cmpForBody"                                0.00
"cmpPrim2"                                  0.00
"cmpSubsetDispatch"                         0.00
"constantFold"                              0.00
"constantFoldCall"                          0.00
"deparse"                                   0.00
"file"                                      0.00
"find.package"                              0.00
"findLocals1"                               0.00
"formals"                                   0.00
"getFoldFun"                                0.00
"getInlineInfo"                             0.00
"help"                                      0.00
"index.search"                              0.00
"isBaseVar"                                 0.00
"normalizePath"                             0.00
"numeric_version"                           0.00
"Ops.numeric_version"                       0.00
"RdTags"                                    0.00
"strwrap"                                   0.00
"sys.function"                              0.00
"table"                                     0.00
"urlify"                                    0.00
"writeHref"                                 0.00
"writeLines"                                0.00

$sample.interval
[1] 0.02

$sampling.time
[1] 696.34
```

**Comment by kevinushey** [comment]
Thanks; the diagnostic output makes it clear that `stanc_builder()` is the culprit. Is there a less-expensive way for us to retrieve diagnostics from a `.stan` file?

**Comment by stephensrmmartin** [comment]
New notes:

# .rs.stan.runDiagostics

I ran `.rs.stan.runDiagnostics("file.stan", TRUE)` and `.rs.stan.runDiagnostics("file.stan", FALSE)` 100x in a loop. No crashes.

# stanc_builder

I ran stanc_builder also in a loop 100x. No crashes.

# Modifying file, then running fns

I wrote a QnD script that just modifies the file with or without spaces on a particular line, then calls `.rs.stan.runDiagnostics("file.stan", FALSE)`. It does this 100x.

```
base_stan_file <- "testStan.stan"

global_flag <- FALSE

modify_file <- function(file){
  f <- file(file, open = "r+w")
  contents <- readLines(f)
  contents[30] <- ifelse(global_flag, "//MAGIC//","  //MAGIC//")
  global_flag <<- !global_flag
  writeLines(contents, f)
  close(f)
}

for(p in 1:100) {
  modify_file(base_stan_file)
  .rs.stan.runDiagnostics(base_stan_file, FALSE)
}
```

Where line 30 of the `testStan.stan` file literally just has "   //MAGIC//"

It didn't crash. I even ran it again, with another 100 just to be sure.

# Summary

This only seems to happen when saving *from* the Rstudio Stan editor pane. By itself, stanc_builder is fine; by itself, .rs.stan.runDiagnostics is fine; when modifying the file, saving, and running .rs.stan.runDiagnostics, it is fine.

**Comment by helske** [comment]
I raised the same issue with latest `rstan` + Rstudio some time ago: https://github.com/stan-dev/rstan/issues/899#issuecomment-779661760. Downgrading `rstan` fixed this Rstudio still tends to crash occasionally due to some other Stan issue I guess (has been doing this for a year now actually).

**Comment by mikebessuille** [comment]
Will be mitigated by https://github.com/rstudio/rstudio/issues/9065

**Comment by mikebessuille** [comment]
Should be retested once 9065 is done.

**Comment by mike-lawrence** [comment]
> Will be mitigated by #9065

@mikebessuille Hm, what's the timeline of #9065? I ask because this bug, which I believe @stephensrmmartin has very adeptly localized specifically to an interaction between RStudio & V8, makes RStudio pretty much unusable for working with Stan files at present, which is going to affect a non-negligible % of users.

**Comment by mikebessuille** [comment]
Moving to cmdstanr is a non-trivial amount of work, and doesn't fit into 1.5 which is already over-subscribed.  i expect we'll be able to fix this in the 2nd half of 2021.

**Comment by stephensrmmartin** [comment]
Are you confident that moving to cmdstan will work? Is there a known reason for why it is failing as-is specifically with rstudio + saving?

Because - again - The stanc_builder is fine by itself, the .rs.stan.runDiagnostics is fine by itself. Editing a file, and re-running .rst.stan.runDiagnostics in repeatedly in a a loop is fine by itself. It specifically fails when editing a .stan file from within an rstudio pane and saving it. This seems to me to be an issue of RStudio, not rstan per se. I am not as familiar with the rstudio codebase as you of course, but I am curious why cmdstan would fix it, if the rstan functionality does not itself seem to cause a problem?

**Comment by mike-lawrence** [comment]
> Moving to cmdstanr is a non-trivial amount of work, and doesn't fit into 1.5 which is already over-subscribed. i expect we'll be able to fix this in the 2nd half of 2021.

Right, hence my concern in tying the further investigation of this bug to the implementation of #9065, which I personally didn't intend to be related to this. As @stephensrmmartin says, given his sleuthing, it's likely that we'll be in the same place then as now, with something substantial broken for a lot of users in the interim.

**Comment by mikebessuille** [comment]
No i'm not certain it's a problem in stan, but that seems likely.  Kevin is the expert but is unavailable; he'll comment when he's back.

**Comment by nicokist** [comment]
I have experienced this problem, it can make RStudio (Which I love! Thanks guys!) basically unusable.

RStudio seems to be hitting `stanc_builder` very often (10s of times if you select the model code without changing anything). Each run of `stanc_builder` takes about a second, with outliers of over 2 seconds. 

90% of this time is spent inside stanc_beta, where about 0.6 seconds is spent initializing the V8 object with stanc.js. I'm pretty sure it's hitting github each time.

Using a local copy of stanc.js or caching the `ctx` object really helps, bringing it down to about 0.25 seconds, which is already a much better experience.

Is there an easy way to make RStudio only run this code once, and only when the file is saved? Even 0.25 seconds is still too much for RStudio to want to call `stanc_builder` multiple times for every keypress.

**Comment by carloszarzar** [comment]
Hello guys.

Apparently, I believe the problem is really in RStudio because I run (the example is given from https://github.com/rstudio/rstudio/issues/9055#issuecomment-790679994) on R-base software (R root) and the stan program works without any crashing RStudio session. And I can say that it runs even faster than RStudio.

Some discussions on the subject can also be found on the stan forum https://discourse.mc-stan.org/t/problems-with-crashing-r-session/20994/61

**Comment by mikebessuille** [comment]
Okay, we'll have another look at this.

**Comment by carloszarzar** [comment]
look. Interestingly I managed to run my example script without any problems now in RStudio.
I don't know how, but two attempts went well, both on r-base and 2 times too on RStudio today. 
I even installed Linux Ubuntu 20.04 (as a dual Boot) this weekend to assess if the problem was only on Windows. But I'm having trouble installing RStan and its dependencies on Linux, which I'm working on resolving.

**Comment by kevinushey** [comment]
I think the underlying bug here is actually much more simple. Every time the document is saved, a new save handler is being registered for the diagnostics run, which implies that for a long-running RStudio session you end up in a state where the diagnostics engine is being run many, many times in a row on each save.

I think that is worth fixing for 1.4-JR; moving to cmdstanr or something else is probably something for later. I'll file a separate bug report for that.

**Comment by carloszarzar** [comment]
Perhaps that could be the problem. I am cleaning up my history and my .rds files before running my scripts, to evaluate the improvement regarding the problem.

**Comment by kevinushey** [comment]
If I'm correct, you would only see this issue after working with a particular Stan file for a long time in RStudio; it would not manifest immediately after opening.

**Comment by nicokist** [comment]
This seems to have worked for me! The slowdown has gone away, and RStudio is calling on stanc_builder much less.  🎉

**Comment by ebuhle** [comment]
Glad to hear this has been fixed! I'm currently experiencing this problem and, as others have said, it is making RStudio pretty much unusable.

However, I'm not sure how to get the patched version. It looks like the latest [preview version](https://rstudio.com/products/rstudio/download/preview/) is from 2021-02-11, whereas #9107 was merged six days ago. I don't see a way to install the development build from GitHub. Any tips would be appreciated.

**Comment by gtritchie** [comment]
@ebuhle 
> However, I'm not sure how to get the patched version. It looks like the latest [preview version](https://rstudio.com/products/rstudio/download/preview/) is from 2021-02-11, whereas #9107 was merged six days ago. I don't see a way to install the development build from GitHub. Any tips would be appreciated.

You can try the latest daily build. These should be considered (potentially) less stable than the preview releases as they have received less testing.

https://dailies.rstudio.com/

**Comment by ebuhle** [comment]
Aha! I suspected that was somewhere, but didn't know where. Thanks!

**Comment by ronblum** [comment]
Verified in RStudio Desktop 1.4.1650 on MacOS 11.3:
- Using @spinkney's example above.
- First tried out in version 1.4.1106 by literally just adding a blank line and saving multiple times—each time saving took a little longer and longer and longer.
- Confirmed fixed by repeating the same i n1.4.1650.

**Comment by zhengchencai** [comment]
Hi there, 

I am also facing this issue.  It’s so painful to write a stan model, as long as I write more than around 10 new lines, Rstudio will crash. And the saving time for the stan code will also take longer up to around 10s while I am approaching the crash point.

What I noticed is that the memory usage can go up to ~1.5GiB while I am only modifying the stan code and nothing is loaded in the environment. Seems Rstudio is automatically saving the code with a certain frequency. Could you please  This issue just comes back after I updated rstan since I need some math functions in the new release. It’s now so painful to write a stan model, as long as I write more than around 10 new lines, Rstudio will crash. And the saving time for the stan code will also take longer up to around 10s while I am approaching the crash point.

What I noticed is that the memory usage can go up to ~1.5GiB while I am only modifying the stan code and nothing is loaded in the environment. Seems Rstudio is automatically saving the code with a certain frequency. Could you please help?
![image](https://user-images.githubusercontent.com/29985544/114062942-1452f800-9866-11eb-84c7-d44ffa987dce.png)

**Comment by stephensrmmartin** [comment]
> Hi there,
> 
> I am also facing this issue. It’s so painful to write a stan model, as long as I write more than around 10 new lines, Rstudio will crash. And the saving time for the stan code will also take longer up to around 10s while I am approaching the crash point.
> 
> What I noticed is that the memory usage can go up to ~1.5GiB while I am only modifying the stan code and nothing is loaded in the environment. Seems Rstudio is automatically saving the code with a certain frequency. Could you please This issue just comes back after I updated rstan since I need some math functions in the new release. It’s now so painful to write a stan model, as long as I write more than around 10 new lines, Rstudio will crash. And the saving time for the stan code will also take longer up to around 10s while I am approaching the crash point.
> 
> What I noticed is that the memory usage can go up to ~1.5GiB while I am only modifying the stan code and nothing is loaded in the environment. Seems Rstudio is automatically saving the code with a certain frequency. Could you please help?
> ![image](https://user-images.githubusercontent.com/29985544/114062942-1452f800-9866-11eb-84c7-d44ffa987dce.png)

Use a daily build of rstudio that contains a fix.

https://github.com/rstudio/rstudio/issues/9055#issuecomment-804439954

**Comment by ebuhle** [comment]
> Use a daily build of rstudio that contains a fix.
> 
> [#9055 (comment)](https://github.com/rstudio/rstudio/issues/9055#issuecomment-804439954)

I know this issue has been closed and that was the official solution, but I've tried two recent daily builds (currently 1.4.1662) and I'm still encountering these problems when editing Stan files. Crashes have been less frequent than before the fix, but saving edits is still excruciatingly slow and bogs down RStudio. It also appears to slow down with repeated saves, although I haven't rigorously timed a reproducible example.

Anyone else still experiencing this?

**Comment by zhengchencai** [comment]
> > Use a daily build of rstudio that contains a fix.
> > [#9055 (comment)](https://github.com/rstudio/rstudio/issues/9055#issuecomment-804439954)
> 
> I know this issue has been closed and that was the official solution, but I've tried two recent daily builds (currently 1.4.1662) and I'm still encountering these problems when editing Stan files. Crashes have been less frequent than before the fix, but saving edits is still excruciatingly slow and bogs down RStudio. It also appears to slow down with repeated saves, although I haven't rigorously timed a reproducible example.
> 
> Anyone else still experiencing this?

Yes, that is the issue I am facing and I've tried nightly build, it solved the problem in some level but not fully. After updating rstan, Rstudio is crashing more frequenly.

**Comment by carloszarzar** [comment]
Yes, I also face the same problem. I am using RStudio Version 1.4.1103 and one way I found to solve the problem is to delete the history (.Rhistory) before using the Stan program.

**Comment by ebuhle** [comment]
> After updating rstan, Rstudio is crashing more frequenly.

Which version are you using? I've been on 2.21.2 since its release last summer.

> one way I found to solve the problem is to delete the history (.Rhistory) before using the Stan program.

Interesting. Will try this.

**Comment by zhengchencai** [comment]
> > After updating rstan, Rstudio is crashing more frequenly.
> 
> Which version are you using? I've been on 2.21.2 since its release last summer.
> 
> > one way I found to solve the problem is to delete the history (.Rhistory) before using the Stan program.
> 
> Interesting. Will try this.

Mine is 2.26 from github.

**Comment by ebuhle** [comment]
> > one way I found to solve the problem is to delete the history (.Rhistory) before using the Stan program.
> 
> Interesting. Will try this.

This doesn't seem to have any effect for me, unfortunately.

**Comment by nicokist** [comment]
Does running `rstan_options(javascript=FALSE)` help?

**Comment by ebuhle** [comment]
> Does running `rstan_options(javascript=FALSE)` help?

Why yes, it does! Thank you! I wasn't even aware of this option. Does it affect anything else? The curious thing is that I don't even have **rstan** loaded in my current session -- I typically don't while working on my Stan-dependent packages -- but I guess RStudio is [calling](https://github.com/rstudio/rstudio/issues/9055#issuecomment-791583704) `rstan::stanc_builder()` behind the scenes.

Again, thanks; this appears to be a lifesaver!

**Comment by zhengchencai** [comment]
> rstan_options(javascript=FALSE)

Thanks. I tried it and launched a fit and then got crashed. Am I suppose to restart Rstudio?
![image](https://user-images.githubusercontent.com/29985544/114082421-b7623c80-987b-11eb-9dc3-fcba9a143928.png)

**Comment by zhengchencai** [comment]
> > rstan_options(javascript=FALSE)
> 
> Thanks. I tried it and launched a fit and then got crashed. Am I suppose to restart Rstudio?
> ![image](https://user-images.githubusercontent.com/29985544/114082421-b7623c80-987b-11eb-9dc3-fcba9a143928.png)

So I reboot the PC and set this option ```rstan_options(javascript=FALSE)```, still crashed while just editing .stan file :(

**Comment by stephensrmmartin** [comment]
This seems different to me. Can you absolutely ensure that you're starting with a clean workspace? I suspect it's trying to load previously compiled models (?).

Also, can you revert back to the CRAN version of rstan just to rule that out?

**Comment by zhengchencai** [comment]
> This seems different to me. Can you absolutely ensure that you're starting with a clean workspace? I suspect it's trying to load previously compiled models (?).
> 
> Also, can you revert back to the CRAN version of rstan just to rule that out?

Thanks a lot for replying. I indeed reboot PC so I suppose the workspace was clean. What I can see is every time I edit the stan code a bit like add two lines, it will increase the memory usage few tens or hundreds MiB without loading any data. Sorry I would not like to revert back to the CRAN version since I do need some build-in functions it doesn't have. Besides, I've been going back and forth with Rstudio nightly build versions and stan versions since two weeks ago this issue first appeared. Worse case I will go back to simple r console.

**Comment by helske** [comment]
I just updated to recent development version of `rstan` and installed daily Rstudio, and this problem seems to persist on Windows 10, although slightly less often than before (earlier crashes happened pretty much every time I saved stan file). I used `javascript=FALSE` and emptied `.Rhistory` as well, no difference.

**Comment by zhengchencai** [comment]
Just to update. I downgraded Rstudio to 1.3 and switched to cmdstanr. After working for a week, I only had 5 crashes. I did not use javascript=FALSE

**Comment by maxbiostat** [comment]
Just wanted to chime in to say that I'm experiencing these slowdowns (for saving and checking) with Rstudio 1.5.52, 4.0.4 and Ubuntu 20.04.1.

**Comment by carloszarzar** [comment]
Hi guys. Really this R Studio bug is pretty annoying. A trick that might help momentarily is to use the root R (without RStudio) when running the stan model. It seems to me that a newer version tried to fix it but I'm not sure if it was successful.

Regards!!!!

**Comment by mikebessuille** [comment]
We believe this is a bug in Stan, not RStudio.  We might be able to introduce a workaround, being tracked here https://github.com/rstudio/rstudio/issues/9282 but the ideal solution is to fix the source of this memory leak in Stan.

**Comment by mike-lawrence** [comment]
> We believe this is a bug in Stan, not RStudio. 

Presumably you mean rstan? Though I guess it's noteable that even with an [overwrite of rstudio_stanc in the rstan namespace via assignInNamespace](https://github.com/mike-lawrence/aria/blob/main/aria/R/enable_rstudio_syntax_compile.R), I still seem to get occasional lockup/crashes. Maybe I need to check what else is calling stanc_builder; possibly whatever is doing the real-time syntax hints in the editor?

**Comment by SteveBronder** [comment]
Would anyone have time to try the rstan in the branch below?

https://github.com/stan-dev/rstan/issues/945#issuecomment-861559316

I _think_ that fixes the error, which seems to have something to do with `v8$source()`

**Comment by cm421** [comment]
@mike-lawrence, you're exactly right. RStudio uses the output from `stanc_builder` to provide the syntax hints every time a file is saved. Since an autosave is triggered after every 1-2 second pause while editing a `.stan` file, and each call to `stanc_builder` uses an additional ~40MB of memory, this can chew through a lot of memory very quickly. My working theory is that this is what's causing most (hopefully all) of the crashes/slowdowns seen in this thread. 

This fix that @SteveBronder has put together in `rstan` seems to drastically improve the memory usage for me on both MacOS and Ubuntu, I would love to hear how it affects the slowdowns and crashes you're seeing

**Comment by SteveBronder** [comment]
Just to update I think we figured out a solution, if folks can try out the rstan/Stanheaders branches below to see if the issue persists that would be wonderful

```
  remotes::install_git("https://github.com/stan-dev/rstan", subdir = "StanHeaders", ref = "experimental")
  remotes::install_git("https://github.com/stan-dev/rstan", subdir = "rstan/rstan", ref = "experimental")

  # OR

  remotes::install_github("stan-dev/rstan/StanHeaders@experimental")
  remotes::install_github("stan-dev/rstan/rstan/rstan@experimental")
```

**Comment by carloszarzar** [comment]
Good morning everybody. Sorry for the delay in feedback. A first test quickly carried out seems to me that the problem still persists. I installed it through this command sent below and ran my models and the session ended again in RStudio Version 1.4.1103, R version 4.0.4 (2021-02-15), Windows 10. I haven't tested it on Linux yet.

''' remotes::install_github("stan-dev/rstan/rstan/rstan@experimental") '''

**Comment by kevinushey** [comment]
@carloszarzar: can you please update to the latest RStudio release (1.4.1717)?

**Comment by cm421** [comment]
@carloszarzar For what it's worth, I had to remove the old `rstan` and `StanHeaders` first for it to work for me: https://github.com/stan-dev/rstan/wiki/Installing-RStan-from-Source

Specifically:
```
remove.packages("rstan")
remove.packages("StanHeaders")
if (file.exists(".RData")) file.remove(".RData")
```

**Comment by carloszarzar** [comment]
Ok. I updated RStudio to version 1.4.1717 (@kevinushey ). Then I followed @cm421 's suggestion removing the packages and reinstalling them with the command:

`remotes::install_github("stan-dev/rstan/StanHeaders@experimental")
remotes::install_github("stan-dev/rstan/rstan/rstan@experimental")
`
But there was an error installing the StanHeaders package.

```
Error: Failed to install 'StanHeaders' from GitHub:
  Command failed (128)
```
Below is the complete error output.
```
"C:\PROGRA~1\Git\cmd\git.exe" clone --depth 1 --no-hardlinks --recurse-submodules --branch develop https://github.com/stan-dev/stan.git C:\Users\CARLOS~1\AppData\Local\Temp\RtmpUDbrmV\remotes1d907e9b1a6e/stan-dev-rstan-1dc4cdd/StanHeaders/../StanHeaders/inst/include/upstream
Error: Failed to install 'StanHeaders' from GitHub:
  Command failed (128)
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\CARLOS~1\AppData\Local\Temp\RtmpUDbrmV\file1d901ce635d6.tar.gz" -C "C:/Users/CARLOS~1/AppData/Local/Temp/RtmpUDbrmV/remotes1d907e9b1a6e"’ returned error code 2
2: In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command '"C:\PROGRA~1\Git\cmd\git.exe" clone --depth 1 --no-hardlinks --recurse-submodules --branch develop https://github.com/stan-dev/stan.git C:\Users\CARLOS~1\AppData\Local\Temp\RtmpUDbrmV\remotes1d907e9b1a6e/stan-dev-rstan-1dc4cdd/StanHeaders/../StanHeaders/inst/include/upstream' had status 128
```

**Comment by cm421** [comment]
I was having the same problem with `install_github` on Windows as well, so I tried `install_git` and was able to get that to work (note it's using `devtools`, so you'll need to install that if it isn't already):
```
devtools::install_git("https://github.com/stan-dev/rstan.git", subdir="StanHeaders", ref="experimental")
devtools::install_git("https://github.com/stan-dev/rstan.git", subdir="rstan/rstan", ref="experimental")
```

I think one of the problems `install_github` was running into was file paths that were too long. I did have long file paths enabled for my machine while running both those commands, so if those don't work for you, and you're getting messages that indicate you're hitting the file name limit, you can try enabling long file paths:
1. In your system registry (https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=cmd)
2. In git: `git config --system core.longpaths true`

**Comment by carloszarzar** [comment]
For me install_git doesn't work. It keeps running and doesn't finish. The only one that returns anything (in this case an error) is install_github. Apparently not a long path problem. Thanks @cm421

**Comment by cm421** [comment]
I should have emphasized the slow part. `install_git` is _very_ slow, and if you're running it in RStudio you won't get much feedback while it's running, so it may seem like it's frozen.

Please try restarting R/RStudio and re-running the command and let it run to completion. It took about 1.5 hours for mine to run, so maybe set it and leave it to run during lunch or at the end of the day

**Comment by carloszarzar** [comment]
Ok @cm421 . I'll present the step-by-step (following your last suggestion) I made and the error outputs generated.

`
remove.packages("rstan")
remove.packages("StanHeaders")
if (file.exists(".RData")) file.remove(".RData")
`
# StanHeaders package
`
devtools::install_git("https://github.com/stan-dev/rstan.git", subdir="StanHeaders", ref="experimental")
`
Here I returned the following error.

`
Downloading git repo https://github.com/stan-dev/rstan.git
"C:\PROGRA~1\Git\cmd\git.exe" clone --depth 1 --no-hardlinks --recurse-submodules --branch develop https://github.com/stan-dev/stan.git C:\Users\CARLOS~1\AppData\Local\Temp\RtmpWE5Qd1\file27981fe76823/StanHeaders/../StanHeaders/inst/include/upstream
Error: Failed to install 'unknown package' from Git:
  Command failed (1)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command '"C:\PROGRA~1\Git\cmd\git.exe" clone --depth 1 --no-hardlinks --recurse-submodules --branch develop https://github.com/stan-dev/stan.git C:\Users\CARLOS~1\AppData\Local\Temp\RtmpWE5Qd1\file27981fe76823/StanHeaders/../StanHeaders/inst/include/upstream' had status 1
`
# RStan package

`
devtools::install_git("https://github.com/stan-dev/rstan.git", subdir="rstan/rstan", ref="experimental")
`
Here I returned the following error.
`
Downloading git repo https://github.com/stan-dev/rstan.git
"C:\PROGRA~1\Git\cmd\git.exe" clone --depth 1 --no-hardlinks --recurse-submodules --branch develop https://github.com/stan-dev/stan.git C:\Users\CARLOS~1\AppData\Local\Temp\RtmpWE5Qd1\file27987dbb19e0/rstan/rstan/../../StanHeaders/inst/include/upstream
Error: Failed to install 'unknown package' from Git:
  Command failed (1)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command '"C:\PROGRA~1\Git\cmd\git.exe" clone --depth 1 --no-hardlinks --recurse-submodules --branch develop https://github.com/stan-dev/stan.git C:\Users\CARLOS~1\AppData\Local\Temp\RtmpWE5Qd1\file27987dbb19e0/rstan/rstan/../../StanHeaders/inst/include/upstream' had status 1
`

Thank you for your attention and help.

**Comment by bwavila** [comment]
I am assuming this did not get resolved in versions:
Rstan 2.26.23
StanHeaders 2.26.28

because I am having the same problems and the only thing that fixes it is installing the experimental builds.

**Comment by kevinushey** [comment]
> and the only thing that fixes it is installing the experimental builds.

Do you mean the experimental builds of rstan, or of RStudio?

**Comment by bwavila** [comment]
> > and the only thing that fixes it is installing the experimental builds.
> 
> Do you mean the experimental builds of rstan, or of RStudio?

Sorry.  The only thing that "fixed" my problem was installing the experimental builds of StanHeaders and Rstan.
