### ISSUE TITLE
RStudio build351 doesn't start on other user session on macOS 11.6

### ISSUE THREAD

**Issue by bresnico** [rstudio/rstudio#9945]
### System details

    RStudio Edition :  Desktop
    RStudio Version : 2021.09.0+351
    OS Version      : MacOS 11.6
    R Version       : 4.1.1 (via Homebrew)

### Steps to reproduce the problem

1. install new RStudio 2021.09.0+351  from .dmg : ok
2. start new RStudio in current macOS session : ok, everything is fine in that only macOS session.
3. log in another macOS session (standard user) : ok
4. start RStudio in that other macOS session : fail.
5. create a new "blank" standard user session in macOS and try again to launch RStudio in that clean environment : fail.

### Describe the problem in detail

RStudio doesn't even seem to start in other sessions than the one where I installed RStudio (e.g. I'm unable to run RStudio diagnostics via Terminal in other sessions). MacOS crash report appears right away:

Process:               RStudio [44917]
Path:                  /Applications/RStudio.app/Contents/MacOS/RStudio
Identifier:            org.rstudio.RStudio
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        ??? [1]
Responsible:           RStudio [44917]
User ID:               505

Date/Time:             2021-10-12 12:31:32.308 +0200
OS Version:            macOS 11.6 (20G165)
Report Version:        12
Anonymous UUID:        BCD870D0-C8A1-DC0E-2122-54C4A7BE23A9

Sleep/Wake UUID:       555DFEEA-3A54-4706-BFF2-D611603C9A17

Time Awake Since Boot: 55000 seconds
Time Since Wake:       19000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 1FB62A50-25C7-3F72-8054-A70CD3CA5953
Library not loaded: @rpath/QtWebEngine.framework/Versions/5/QtWebEngine
  Referenced from: /Applications/RStudio.app/Contents/MacOS/RStudio
  Reason: no suitable image found.  Did find:
	/Applications/RStudio.app/Contents/MacOS/../Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine: open() failed with errno=13
	/Applications/RStudio.app/Contents/MacOS/../Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine: stat() failed with errno=1

Binary Images:
       0x10094f000 -        0x100beafff + (0) <A2169503-07C8-37D9-A9C7-DDF2DB8F8AC4> 
       0x108fef000 -        0x10903efff +libRosettaRuntime (203.58) <858715C8-01F6-3F86-B9AE-F058CB4E085C> /Library/Apple/*/libRosettaRuntime
       0x200e8c000 -        0x200f27fff  dyld (852.2) <0CC19410-FD43-39AE-A32A-50273F8303A4> /usr/lib/dyld
    0x7ffdffc2e000 -     0x7ffdffc5dfff  runtime (203.58) <BBDCFB04-7B39-3FDE-90D3-A6E55EE628E7> /usr/libexec/rosetta/runtime

Model: MacBookPro17,1, BootROM 6723.140.2, proc 8:4:4 processors, 16 GB, SMC 
Graphics: kHW_AppleM1Item, Apple M1, spdisplays_builtin
Memory Module: LPDDR4
AirPort: spairport_wireless_card_type_airport_extreme, wl0: Aug 18 2021 22:48:53 version 18.50.40.11.7.8.123 FWID 01-3ed0e3a2
Bluetooth: Version 8.0.5d7, 3 services, 27 devices, 1 incoming serial ports
Network Service: USB 10/100/1000 LAN, Ethernet, en6
USB Device: USB 3.1 Bus
USB Device: USB 3.1 Bus
USB Device: Dell dock
USB Device: USB 10/100/1000 LAN
USB Device: Dell dock
USB Device: Hub
USB Device: Dell dock
USB Device: Dell dock
USB Device: Dell dock
USB Device: Dell dock
USB Device: USB Audio
USB Device: Hub
USB Device: C922 Pro Stream Webcam
USB Device: Yeti Stereo Microphone
USB Device: Dell KB216 Wired Keyboard
USB Device: DELL Laser Mouse
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

RStudio diagnostic file was generated in the only session where the app works (see attached).

### Describe the behavior you expected

I expected RStudio to start in the 3 macOS sessions in my computer.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
[diagnostics-report.txt](https://github.com/rstudio/rstudio/files/7329218/diagnostics-report.txt)

**Comment by redmeades** [comment]
@mikebessuille I have seen this same issue today on a Homebrew based installation of this version - MacOS 11.6 on M1.

Reverted to 1.4.1717 via dmg and that is working.

The previous Homebrew version (1.4.1717) was also working on 11.5.1.

**Comment by kevinushey** [comment]
```
Dyld Error Message:
dyld: Using shared cache: 1FB62A50-25C7-3F72-8054-A70CD3CA5953
Library not loaded: @rpath/QtWebEngine.framework/Versions/5/QtWebEngine
Referenced from: /Applications/RStudio.app/Contents/MacOS/RStudio
Reason: no suitable image found. Did find:
/Applications/RStudio.app/Contents/MacOS/../Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine: open() failed with errno=13
/Applications/RStudio.app/Contents/MacOS/../Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine: stat() failed with errno=1
```

`errno=13` corresponds to a permission error; `errno=1` corresponds to similar "operation not permitted" error.

Unfortunately it's not clear to me why these permission errors are occurring, and I don't have an M1 machine to test or verify right now.

**Comment by kevinushey** [comment]
On my system, I see:

```
$ stat /Applications/RStudio.app/Contents/MacOS/../Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine
16777220 139466411 -rwx--x--x 1 kevinushey admin 0 414752 "Oct 20 09:51:29 2021" "Sep 20 16:16:54 2021" "Oct  8 14:12:27 2021" "Sep 20 16:16:54 2021" 4096 816 0 /Applications/RStudio.app/Contents/MacOS/../Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine
```

Note that it's owned by my own user account. How was RStudio installed on your machine? Was it installed by your user account, or by a separate administrator account?

**Comment by mikebessuille** [comment]
We'll fix this for Prairie Trillium; then the fix will be available shortly in previews.  If we get a lot of customers running into this, we can cherry pick the patch into a 2021.09.2 patch if needed.

**Comment by stevemaser** [comment]
We are running into this with 2021.09 here as well -- on 10.15 through Monterey.   The application will not launch with root:admin permissions (which is how Munki will deploy apps by default), either.

**Comment by jamesez** [comment]
For customers who make RStudio available via managed installation systems (e.g., Jamf, Workspace One, or Munki, say) - this version is broken because the "installer" is `root`.

**Comment by R-Hannibal** [comment]
@astayleraz - Looks like this issue is M1 specific if you have a chance to `qa repro` it 👍.

**Comment by kevinushey** [comment]
@R-Hannibal are you sure? I'm fairly certain this affects both M1 and Intel Macs.

**Comment by stevemaser** [comment]
> @R-Hannibal are you sure? I'm fairly certain this affects both M1 and Intel Macs.

We see this problem on everything from 10.15 and up (we aren't testing things against 10.14 any more...)

**Comment by R-Hannibal** [comment]
@kevinushey - apologies, I was going off of your comment [HERE](https://github.com/rstudio/rstudio/issues/9945#issuecomment-947856257) that the issue was M1 specific in some way. If that's not the case then anyone on the team should be able to attempt the repro.

**Comment by kevinushey** [comment]
I followed up in https://github.com/rstudio/rstudio/issues/9945#issuecomment-948124945 to indicate the issue is reproducible on my (Intel) system.

**Comment by jamesez** [comment]
We see the 'incorrect' permissions looking at the downloadable dmg from the RStudio site.

**Comment by aja08379** [comment]
Zendesk #68089 also refers.

**Comment by stevemaser** [comment]
Build 372 has the same problem:

Process:               RStudio [15039]
Path:                  /Applications/RStudio.app/Contents/MacOS/RStudio
Identifier:            org.rstudio.RStudio
Version:               2021.09.1+372 (2021.09.1+372)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           RStudio [15039]
User ID:               503

Date/Time:             2021-11-10 11:08:17.063 -0500
OS Version:            macOS 11.6.1 (20G224)
Report Version:        12
Anonymous UUID:        CED25F1A-B57B-A34A-B1F9-48F00170091C


Time Awake Since Boot: 6700 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  dyld: Using shared cache: 80896B32-9EB1-3A10-A7C5-449B15305DE2
Library not loaded: @rpath/QtWebEngine.framework/Versions/5/QtWebEngine
  Referenced from: /Applications/RStudio.app/Contents/MacOS/RStudio
  Reason: no suitable image found.  Did find:
	/Applications/RStudio.app/Contents/MacOS/../Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine: open() failed with errno=13
	/Applications/RStudio.app/Contents/MacOS/../Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine: stat() failed with errno=1

Binary Images:
       0x103f49000 -        0x1041dcfff +org.rstudio.RStudio (2021.09.1+372 - 2021.09.1+372) <DE1A9B2E-8769-328B-92BB-241A24EDE711> /Applications/RStudio.app/Contents/MacOS/RStudio
       0x106519000 -        0x1065b4fff  dyld (852.2) <14C5D17F-5032-37A2-9CD8-F437EB4A3992> /usr/lib/dyld

**Comment by kevinushey** [comment]
We haven't addressed the issue yet so you won't see any fixes in the latest daily builds.

**Comment by gtritchie** [comment]
Working on the fix now, sorry for the delay!

**Comment by gtritchie** [comment]
I found what happened. When we setup the M1 builder, Qt 5.12.10 got installed (we were supposed to be using 5.12.8).

The file permissions inside the Qt installation on the build machine are wrong on the files in question.

I’m installing Qt 5.12.10 locally to see if that’s a Qt issue that was introduced in 5.12.10, or something that got accidentally mucked up on the build machine.

Either way, question is if we should go back to 5.12.8, which we thought we were still using or manually chmod files in the Qt installed on the builder…

This was missed because CMakeLists.txt for desktop has this:

      set(QT_CANDIDATES 5.12.8 5.12.11 5.12.10)

And the install-dependencies-osx script doesn’t install Qt 5.12.8 when run on an M1 Mac.

**Comment by gtritchie** [comment]
I have fixed the permissions on the builder, and running a new build.

**Comment by gtritchie** [comment]
This is now working as of daily build `RStudio-2022.01.0-daily+218.dmg`.

**Comment by kevinushey** [comment]
I can confirmed the issue is resolved in the latest daily builds:

```
$ /Applications/RStudio.app/Contents/MacOS/RStudio --version
2022.01.0-daily+235

$ stat /Applications/RStudio.app/Contents/MacOS/../Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine
16777234 4183960 -rwxr-xr-x 1 kevin admin 0 414752 "Nov 23 14:20:27 2021" "Nov 23 14:00:12 2021" "Nov 23 14:20:27 2021" "Nov 23 14:00:12 2021" 4096 816 0 /Applications/RStudio.app/Contents/MacOS/../Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine
```

**Comment by wimleers** [comment]
Also just ran into this; thankfully the specifics of the macOS Problem Report made it easy to find this ticket. Unfortunately checking for updates says there _are no updates._ 

**Can you please do a patch release?**

**Comment by wimleers** [comment]
I tried:
```
sudo chmod -R a+rx /Applications/RStudio.app/Contents/Frameworks
```
And confirmed with `ls -al` that it was applied correctly.

It's still crashing. Stack trace attached.
[crash after chmod.txt](https://github.com/rstudio/rstudio/files/7692187/crash.after.chmod.txt)

**Comment by mikebessuille** [comment]
@wimleers try the latest daily build at https://dailies.rstudio.com/.

**Comment by wimleers** [comment]
I know. But:

> Daily builds are intended for testing purposes, and are not recommended for general use. For stable builds, please visit rstudio.com.

I'm trying to not use dev builds; my partner needs this for school.

**Comment by mikebessuille** [comment]
yes that's fair.  The fix will probably make it into a Ghost Orchid patch at some point, but probably not before the next release (Prairie Trillium), or at least not much before.  That release should be out in early 2022.  While we can't support the dev builds of the new release yet, I can say that it's pretty stable.

**Comment by jmcphers** [comment]
You can get a Ghost Orchid build with a patch here:

https://dailies.rstudio.com/rstudio/ghost-orchid/

**Comment by ronblum** [comment]
Verified that this works correctly by installing RStudio Desktop 2021.09.2+380 in the shared `/Applications` directory as one user, then logging in as a second user and trying to run it.
